### ISSUE TITLE
[REQUEST] Add the ability to manually indicate the episode number or to add episode 

### ISSUE THREAD

**Issue by jamartinh** [takuseno/d3rlpy#10]
**Is your feature request related to a problem? Please describe.**
It seems that episodes are created by observing terminals, this is not clearly defined in the docs however makes sense.

**Describe the solution you'd like**
For even more clear control over this please add a method to append episode or add episode instead of a whole datasets ad the same time.

**Comment by takuseno** [comment]
@jamartinh Thank you for your request! So, is this what you want?
```py
# create empty dataset, which is not currently supported
dataset = MDPDataset()

# add episode, which is not currently supported
dataset.append_episode(episode)
```

**Comment by jamartinh** [comment]
At this time what I am doing inside a Loop:
Loop:
```
 if dataset is None:
        dataset = MDPDataset(observations, actions, rewards, terminals)
        dataset.build_episodes()
    else:
        dataset.extend(MDPDataset(observations, actions, rewards, terminals)) 
```

I guessed that I shall call build_episodes since without it it gave me an error. But still note sure if this is the right way to do it.

**Comment by takuseno** [comment]
@jamartinh Thank you for your information. Could you give me the error? That is not supposed to raise errors. Also I just wonder if you're working on online training, or offline training with incrementally growing dataset?

**Comment by jamartinh** [comment]
@takuseno One thing with the current implementation is that if you use discrete actions, the you get an assertion error if you add a new episode with an action not in the previous episodes.

**Comment by takuseno** [comment]
@jamartinh I see. I did not expect that situation. Let me take it into account.
