### ISSUE TITLE
How to use multi gpu?

### ISSUE THREAD

**Issue by yuxu1997** [takuseno/d3rlpy#104]
Hello, @takuseno ,i want to use multi gpu to train the model, but i don't know how to set the parameter.
I found that “use_gpu” could be set as bool, int or d3rlpy.gpu.Device. Is this the parameter for choosing multi gpu?

**Comment by takuseno** [comment]
@yuxu1997 Sorry for the late response. Currently, there is no support for multiple GPUs. This is because, in the most of cases, we don't use a large dataset nor large neural network models in RL. If I had multiple GPUs, I'm inclining to run multiple experiments instead.

**Comment by takuseno** [comment]
Please feel free to reopen this if you have further discussions.
