### ISSUE TITLE
Custom environment

### ISSUE THREAD

**Issue by amirmirzaeinia** [takuseno/d3rlpy#105]
**Describe the bug**
I used to use online learning but this is new for me. I assume that the input data such as observation, actions and reward can define the custom environment. I am not sure what could be the point of env and scorer in training and fit function? could you please clarify this?

thank you

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**

**Comment by takuseno** [comment]
@amirmirzaeinia Thanks for the issue. d3rlpy supports OpenAI gym-style environments that have `step` and `reset` methods and `observation_space` and `action_space` attributes. As an example, `CartPole-v0` implementation might be good for you.
https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py

**Comment by amirmirzaeinia** [comment]
@takuseno thank you for reply. 
I found these env description. but my question is how do you make your environment when the  tabular datasets of custom environment is just available? do you use MDPDataset in Dataset? thank you

**Comment by takuseno** [comment]
@amirmirzaeinia Sorry, I couldn't fully understand your question. It sounds like you want to create your own dataset with your custom environment. This documentation might be useful.
https://d3rlpy.readthedocs.io/en/v0.91/tips.html#create-your-own-dataset

**Comment by amirmirzaeinia** [comment]
@takuseno I see that each Algo has two separate methods to Instantiate implementation object with MDPDataset object and with OpenAI Gym. thank you

**Comment by takuseno** [comment]
Please feel free to reopen this if you have further discussion.
