### ISSUE TITLE
[BUG]use MOPO to train in walker2d( problem)

### ISSUE THREAD

**Issue by icomeaman** [takuseno/d3rlpy#109]
**Describe the bug**
hi Takuma Seno:
I try to use MOPO to train in walker2d of Mujoko. but every time it stoped at Epoch 5/100 or Epoch 6/100. I don't know why.
have you ever meet this problem.could you help me?
here is the params.json file:

{
  "action_scaler": null,
  "actor_encoder_factory": {
    "type": "default",
    "params": {
      "activation": "relu",
      "use_batch_norm": false,
      "dropout_rate": null
    }
  },
  "actor_learning_rate": 0.0001,
  "actor_optim_factory": {
    "optim_cls": "Adam",
    "betas": [
      0.9,
      0.999
    ],
    "eps": 1e-08,
    "weight_decay": 0,
    "amsgrad": false
  },
  "batch_size": 100,
  "critic_encoder_factory": {
    "type": "default",
    "params": {
      "activation": "relu",
      "use_batch_norm": false,
      "dropout_rate": null
    }
  },
  "critic_learning_rate": 0.0003,
  "critic_optim_factory": {
    "optim_cls": "Adam",
    "betas": [
      0.9,
      0.999
    ],
    "eps": 1e-08,
    "weight_decay": 0,
    "amsgrad": false
  },
  "gamma": 0.99,
  "generated_maxlen": 1250000,
  "initial_temperature": 1.0,
  "lam": 5.0,
  "n_critics": 2,
  "n_frames": 1,
  "n_steps": 1,
  "q_func_factory": {
    "type": "mean",
    "params": {
      "bootstrap": false,
      "share_encoder": false
    }
  },
  "real_ratio": 0.05,
  "rollout_batch_size": 50000,
  "rollout_horizon": 5,
  "rollout_interval": 1000,
  "scaler": null,
  "target_reduction_type": "min",
  "tau": 0.005,
  "temp_learning_rate": 0.0003,
  "temp_optim_factory": {
    "optim_cls": "Adam",
    "betas": [
      0.9,
      0.999
    ],
    "eps": 1e-08,
    "weight_decay": 0,
    "amsgrad": false
  },
  "update_actor_interval": 1,
  "use_gpu": 0,
  "algorithm": "MOPO",
  "observation_shape": [
    17
  ],
  "action_size": 6
}
**To Reproduce**
Epoch 5/100:  93%|▉| 185231/198936 [55:37<04:56, 46.15it/s, critic_loss=7.18e+3, actor_loss=-3082021-08-04 10:12.35 [debug    ] 250000 transitions are generated. fake_transitions=1250000 real_transitions=994684
Epoch 5/100:  94%|▉| 186231/198936 [56:01<04:35, 46.07it/s, critic_loss=7.25e+3, actor_loss=-3252021-08-04 10:13.02 [debug    ] 250000 transitions are generated. fake_transitions=1250000 real_transitions=994684
Epoch 5/100:  94%|▉| 187231/198936 [56:28<04:15, 45.80it/s, critic_loss=7.33e+3, actor_loss=-3432021-08-04 10:13.26 [debug    ] 250000 transitions are generated. fake_transitions=1250000 real_transitions=994684
Epoch 5/100:  95%|▉| 188231/198936 [57:11<03:51, 46.20it/s, critic_loss=7.44e+3, actor_loss=-364Killed

**Expected behavior**

**Additional context**

**Comment by takuseno** [comment]
@icomeaman Thanks for reporting this issue. It looks like the program causes the out-of-memory error. I'll take a look at it. Could you share your machine information (e.g. OS, CPU, RAM, GPU)?

**Comment by icomeaman** [comment]
thank you, I use the workstation of my university. I am not clear  the hardware configuration of it.  I will send you later.

**Comment by icomeaman** [comment]
@takuseno 
here is my hardware configuration :
OS:         OS ubuntu 20.04
RAM:      65783828 kB
CPU:      model name      : Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
GPU:      NVIDIA Corporation TU102 [GeForce RTX 2080 Ti] (rev a1)

and I use batch_size=100, should I turn the batch size down?

**Comment by icomeaman** [comment]
when I turn the batch_size = 5 or 10  , it has a error:

File "pretrain-mopo.py", line 32, in <module>
    mopo.fit(dataset.episodes,
  File "/home/ws/uzfka/.env/venv_new/lib/python3.8/site-packages/d3rlpy/base.py", line 382, in fit
    results = list(
  File "/home/ws/uzfka/.env/venv_new/lib/python3.8/site-packages/d3rlpy/base.py", line 566, in fitter
    range(len(iterator)),
  File "/home/ws/uzfka/.env/venv_new/lib/python3.8/site-packages/d3rlpy/iterators/round_iterator.py", line 54, in __len__
    return len(self._transitions) // self._real_batch_size
ZeroDivisionError: integer division or modulo by zero
