### ISSUE TITLE
[QUESTION] bug title

### ISSUE THREAD

**Issue by jamartinh** [takuseno/d3rlpy#11]
Hi, I am doing something wrong ?

I have a continuous action space with values from 0 to 100.
I created first an MDPDataset with actions recorder in the range 0 to 100 but the output was allways the same value 1.

Now I created the same but with values in [0,1] and after many many  epochs the algo always predicts 1 for each step.

I tested this with CQL and BEAR with same behavior.
Any clues ?

```
cql = CQL(use_gpu=True)
bear = BEAR(q_func_type = 'iqn', use_gpu=True)
```

Thanks !

**Comment by takuseno** [comment]
@jamartinh Thanks for reporting an issue! Currently, every algorithm for continuous control assumes that action-space is normalized between -1.0 and 1.0. Thus, you need to normalize the actions in the dataset, and unnormalize prediction at deployment. I'll consider supporting an arbitrary range of action-space. 

Thank you!
