### ISSUE TITLE
[DOC TYPO] Typo in equation describing td_error_scorer

### ISSUE THREAD

**Issue by pstansell** [takuseno/d3rlpy#111]
I think there is a typo in the equation that defines the TD error in `td_error_scorer()` in `scorer.py`.

Currently it reads (I've simplified due to lack of equation support here)

 `TD_error = E[ Q(s_t,a_t) - (r_t + \gamma\max_a Q(s_{t+1},a))^2 ]`

whereas I think both Q's should be inside the square and the r should be indexed by t+1 instead of t, that is,

 `TD_error = E[ ( Q(s_t,a_t) - (r_{t+1} + \gamma\max_a Q(s_{t+1},a)) )^2 ]`

**Comment by takuseno** [comment]
@pstansell Thanks for reporting this! It's fixed in this commit.
https://github.com/takuseno/d3rlpy/commit/688cc4beb8c02c83ada5f780018d0a5c416afa05

**Comment by pstansell** [comment]
Shouldn't the square be around both Q's also?  That is, instead of

`Q - (r + max Q)^2`

shouldn't it be

`(Q - (r + max Q))^2`

**Comment by takuseno** [comment]
ooops, thanks. It's fixed now.
https://github.com/takuseno/d3rlpy/commit/ca7714d5deecdb5cddc3ff4233aa767360904b1c
![image](https://user-images.githubusercontent.com/5235131/129447834-845b48e7-3b50-4c81-8881-4a71f1dfda53.png)

**Comment by pstansell** [comment]
Perfect, thanks.
