### ISSUE TITLE
[DOC TYPO] missing t suffix in equation

### ISSUE THREAD

**Issue by pstansell** [takuseno/d3rlpy#113]
Hello @takuseno, I think I spotted a very minor typo in the first equation on this page
https://d3rlpy.readthedocs.io/en/latest/references/generated/d3rlpy.algos.CQL.html
I think the `s` in the second occurrence of `Q(s,a)` should be suffixed with a `t` in the same way as it is in the first occurrence, ie, `Q(s_t,a)`.

**Comment by takuseno** [comment]
@pstansell Thanks for reporting this. It's fixed in the latest commit.
https://github.com/takuseno/d3rlpy/commit/8297443672742b292c03425646fb3fdd046e95dc
