### ISSUE TITLE
[BUG] episode[0] index out of range

### ISSUE THREAD

**Issue by asdqsczser** [takuseno/d3rlpy#127]
observations = np.random.random((1000, 4))
    # 1000 steps of actions with shape of (4,)
    actions = np.random.random((1000, 4))
    # 1000 steps of rewards
    rewards = np.random.random(1000)
    # 1000 steps of terminal flags
    terminals = np.random.randint(2, size=1000)
    dataset = MDPDataset(observations, actions, rewards, terminals)
    # automatically splitted into d3rlpy.dataset.Episode objects
    dataset.episodes
    # each episode is also splitted into d3rlpy.dataset.Transition objects
    episode = dataset.episodes[0]
    print(episode[0])

Traceback (most recent call last):
  File "batchrl_trainer.py", line 28, in <module>
    print(episode[0])
  File "d3rlpy/dataset.pyx", line 786, in d3rlpy.dataset.Episode.__getitem__
IndexError: list index out of range

**Comment by jamartinh** [comment]
@asdqsczser I guess you need 1 transition per episode, that means terminals cannot contains the sequence [...1,1..], that is, an episode needs 1 transition which is composed by two observations at leats.

So if you try:

```
terminals[0] = 0
terminals[1:] =np.ceil(np.diff(np.gradient(np.gradient(np.gradient(terminals)**2)**2,1)**2))
```
That will work

**Comment by takuseno** [comment]
@jamartinh Thanks! Yes, you're right.

@asdqsczser Please feel free to reopen this issue since it seems to be solved.
