### ISSUE TITLE
Saving and loading models with action scalers

### ISSUE THREAD

**Issue by osogami** [takuseno/d3rlpy#128]
I have a question about how to save and load models with action scalers.

I would like to specify action_scaler to learn in environments with continuous action spaces.  When I save the model, it appears that the action scaler is ignored.  So, I need to specify the action scaler when I load the model.  I would expect that the action scalers are saved with models, but what is the best practice in saving and loading models with action scalers?

In the following, I show an example.  Only cql2.action_scaler is None, and cql2.predict(obs) gives an action that is different from the others.
```
import d3rlpy

dataset, env = d3rlpy.datasets.get_pendulum()

scaler = d3rlpy.preprocessing.action_scalers.MinMaxActionScaler()
scaler.fit(dataset)

cql = d3rlpy.algos.CQL(action_scaler=scaler)
cql.fit(dataset, n_steps=1, n_steps_per_epoch=1)
cql.save_model("tmp.pt")

cql2 = d3rlpy.algos.CQL()
cql2.build_with_env(env=env)
cql2.load_model("tmp.pt")

cql3 = d3rlpy.algos.CQL(action_scaler=scaler)
cql3.build_with_env(env=env)
cql3.load_model("tmp.pt")

print(cql.action_scaler)
print(cql2.action_scaler)
print(cql3.action_scaler)

obs = env.reset()
cql.predict(obs), cql2.predict(obs), cql3.predict(obs)
```

**Comment by takuseno** [comment]
@osogami Thanks for the issue. For now, please use `from_json` to load the initialized action scaler.
https://d3rlpy.readthedocs.io/en/v0.91/references/save_and_load.html#from-json

`params.json` includes the parameters of scaler, action scaler and reward scaler.

```
cql = d3rlpy.algos.CQL.from_json("path-to-json/params.json")
cql.load("path-to-model/model.pt")
```

**Comment by osogami** [comment]
Thank you very much for your quick response.  `from_json` works fine.
