### ISSUE TITLE
ImportError: cannot import name 'EnsembleDynamics'

### ISSUE THREAD

**Issue by hn2** [takuseno/d3rlpy#134]
When trying to import mopo and run this example:

from d3rlpy.datasets import get_pendulum
from d3rlpy.dynamics import mopo
from d3rlpy.metrics.scorer import dynamics_observation_prediction_error_scorer
from d3rlpy.metrics.scorer import dynamics_reward_prediction_error_scorer
from d3rlpy.metrics.scorer import dynamics_prediction_variance_scorer
from sklearn.model_selection import train_test_split

dataset, _ = get_pendulum()

train_episodes, test_episodes = train_test_split(dataset)

mopo = mopo(learning_rate=1e-4, use_gpu=True)

# same as algorithms
mopo.fit(train_episodes,
         eval_episodes=test_episodes,
         n_epochs=100,
         scorers={
            'observation_error': dynamics_observation_prediction_error_scorer,
            'reward_error': dynamics_reward_prediction_error_scorer,
            'variance': dynamics_prediction_variance_scorer,
         })

**Comment by takuseno** [comment]
@hn2 Sorry, what's the problem here?

**Comment by hn2** [comment]
Can not import:
from d3rlpy.dynamics import mopo
ImportError: cannot import name 'EnsembleDynamics'

**Comment by takuseno** [comment]
Please check the latest documentation.
https://d3rlpy.readthedocs.io/en/v0.91/references/model_based.html

**Comment by hn2** [comment]
I am trying ti run this example,

I get:

ImportError: cannot import name 'EnsembleDynamics'
