### ISSUE TITLE
Question about collecting vs fitting online

### ISSUE THREAD

**Issue by hn2** [takuseno/d3rlpy#136]
I am testing both method to collect data/fit online:

buffer = d3rlpy.online.buffers.ReplayBuffer(1000000, env=env)

# collect without training
sac.collect(env, buffer=buffer, n_steps=100000)

# collect with training
sac.fit_online(env, buffer=buffer, n_steps=100000)

# convert replay buffer to MDPDataset
dataset = buffer.to_mdp_dataset()

and then training an offline model.

In all my tastings, the second method (collect with training) always gives much better results, although it takes longer to train vs collect. Is this a normal expected behavior? (makes sense that it is).

**Comment by takuseno** [comment]
Of course, because the second method is updating parameters online.
