### ISSUE TITLE
[Question] How do you make datasets of CartPole? What do "replay" or "random" imply.

### ISSUE THREAD

**Issue by masaya611** [takuseno/d3rlpy#139]
Thank you your contribution like this opensources. I cannot find a detailed explanation of how to make cartpole's datasets "cartpole.h5" and what "replay" and "random" imply. Please explain it if possible.

**Comment by takuseno** [comment]
Hi, @masaya611 . Thank you for the question. You can find scripts here.
https://github.com/takuseno/d3rlpy/tree/master/scripts

**Comment by masaya611** [comment]
Thank you very much!
Additional question, I think Episode Termination of cartpole is that Episode length is greater than 200.
However, when I check datasets, it includes rewards that is more 200 in one episode. why?

**Comment by takuseno** [comment]
I believe that the length is 200 at most.
https://github.com/openai/gym/blob/d35d211fee6d2eb46066d4e733d81fa238b6b081/gym/envs/__init__.py#L16

Or I'm possible misunderstanding your question.

**Comment by masaya611** [comment]
<img width="396" alt="スクリーンショット 2021-09-20 16 57 03" src="https://user-images.githubusercontent.com/31643542/133971575-5cd763f8-2bbf-4e96-b351-0250e914f976.png">
`
rewards_sum = []
tmp = 0
for i in range(len(dataset.rewards)):
  if dataset.terminals[i] == 1:
    rewards_sum.append(tmp)
    tmp = 0
  if i == len(dataset.rewards) - 1:
    rewards_sum.append(tmp)
  tmp += 1
lst = [ i for i in range(0, len(rewards_sum))]
plt.plot(lst, rewards_sum)
plt.show()
`

**Comment by masaya611** [comment]
I check it to execute below code.
I think done==1 means termination of episode. So I count reward in dataset until done == 1.
And you can see this picture, there are episodes that have more 200 rewards.

And I'm possibly misunderstanding too. 

```
dataset, env = get_cartpole()

rewards_sum = []
tmp = 0
for i in range(len(dataset.rewards)):
  if dataset.terminals[i] == 1:
    rewards_sum.append(tmp)
    tmp = 0
  if i == len(dataset.rewards) - 1:
    rewards_sum.append(tmp)
  tmp += 1

#show rewards each episode
lst = [ i for i in range(0, len(rewards_sum))]
plt.plot(lst, rewards_sum)
plt.show()
```

<img width="389" alt="スクリーンショット 2021-09-20 17 02 21" src="https://user-images.githubusercontent.com/31643542/133972129-ad639cc8-bb61-4c7a-8c5c-1f3d2f871182.png">

**Comment by takuseno** [comment]
You should check `dataset.episode_terminals` because `terminals` will be zeros when timeouts.

**Comment by masaya611** [comment]
Thank you so much!!
It is solved.
このような初心者にも丁寧に回答してくださってありがとうございました！

**Comment by takuseno** [comment]
No worries. Thanks for the question.
ご質問ありがとうございました！
