### ISSUE TITLE
Support of AntMaze, Adroit and Kitchen in D4RL

### ISSUE THREAD

**Issue by TsuTikgiau** [takuseno/d3rlpy#143]
Hello Author, thanks for this nice repo!
I'd like to ask whether this repo supports other d4rl datasets like antmaze, adroit, and kitchen. I notice that in the function dataset.get_dataset, only hooper, halfcheetah, walker, and ant will be taken into account. Am I missing something? Thank you!

**Comment by takuseno** [comment]
Hello, @TsuTikgiau . Thanks for the issue. The other datasets supported by d4rl are also available in this library.
```
import d3rlpy

dataset, env = d3rlpy.datasets.get_d4rl("antmaze-umaze-v0")
```

**Comment by TsuTikgiau** [comment]
Oh I see, thanks for your quick answer!
