### ISSUE TITLE
[question] FQE convergence for pendulum dataset

### ISSUE THREAD

**Issue by vivecalindahl** [takuseno/d3rlpy#146]
I'm experimenting with FQE and the `pendulum-random` dataset. 

I've used `d3rlpy`s CQL to train a policy (20 epochs on 80% of the dataset) until the discounted episode reward is just below -200 (see orange line in figure) then I evaluate using FQE.

I'm seeing issues with FQE not converging to the expected value. In the figure this is seen as the FQE estimate (blue) dips down below the estimated true value (orange) and then up above it.

![image](https://user-images.githubusercontent.com/16899541/138924793-a1009e82-528d-492f-a3de-af857dacc48b.png)

Is this behavior as expected, @takuseno for this setup? Otherwise, do you have experience of how to configure training to get more reliable estimates?

**Comment by takuseno** [comment]
@vivecalindahl Thanks for the issue. The method is not always to be converged to the fixed point. One thing you can try is to train FQE with different policies and see how different the learnig curves are.
