### ISSUE TITLE
[Question] Question about CQL algorithm.

### ISSUE THREAD

**Issue by jsw7460** [takuseno/d3rlpy#147]
I have some questions on CQL algorithm implemented here.

https://github.com/takuseno/d3rlpy/blob/70f8f130a1e59ecd2092c52bd5c684f6153fd88b/d3rlpy/algos/cql.py#L54-L58
1.  
I thought the math equation above (or equivalently, an equation given in appendix F of the paper) is implemented in below code.
However, before the logsumexp, what means policy_values_tp1 ?
I think we only need first and third component, because the next time step observation (=obs_tp1 in code) is not needed for computing the conservative loss.
https://github.com/takuseno/d3rlpy/blob/70f8f130a1e59ecd2092c52bd5c684f6153fd88b/d3rlpy/algos/torch/cql_impl.py#L205-L214

2.
https://github.com/takuseno/d3rlpy/blob/70f8f130a1e59ecd2092c52bd5c684f6153fd88b/d3rlpy/algos/torch/cql_impl.py#L175-L196
Above code is for computing the random action values, which is needed for computing policy_values_t in 1.
However, at the last part, why we compute log(0.5 ** action size), rather than log(0.5)?
It is a place for the density of uniform distribution, so we need just 0.5, other than any other scalars.

Thank you for your great work!

**Comment by takuseno** [comment]
@jsw7460 Thanks for the issue!

Regarding the first question, this part is implemented to reproduce the author's code:
https://github.com/aviralkumar2907/CQL/blob/d67dbe9cf5d2b96e3b462b6146f249b3d6569796/d4rl/rlkit/torch/sac/cql.py#L244
I agree that we don't have to compute this. But, for reproducibility, I've followed their code.

For the second question, the probability of multi-dimensional actions is usually represented by a multiplication over the action dimension:
https://github.com/takuseno/d3rlpy/blob/70f8f130a1e59ecd2092c52bd5c684f6153fd88b/d3rlpy/models/torch/policies.py#L18
Therefore, it's done the same thing in that part.

If you have further questions, please let me know.
