### ISSUE TITLE
Usage help request

### ISSUE THREAD

**Issue by mamengyiyi** [takuseno/d3rlpy#148]
Hi, I wanna calculate the gradient of the ensemble Q with respect to input state or action. Could you tell me if there are related functions that can be called? If not, how could I implement it easily?

**Comment by takuseno** [comment]
@mamengyiyi Thank you for the issue. Please let me clarify what you want to do. Do you want to record gradients as training metrics?

**Comment by mamengyiyi** [comment]
> @mamengyiyi Thank you for the issue. Please let me clarify what you want to do. Do you want to record gradients as training metrics?

Hi, thanks for your reply. Actually I wanna calculate gradients like this:
![image](https://user-images.githubusercontent.com/23417331/140016363-4f9292bc-b64c-4302-ab7f-51076bb73f48.png)

**Comment by mamengyiyi** [comment]
Hi, after carefully reading your code, I thought I've found the solution to modify. Thanks again!
