### ISSUE TITLE
[REQUEST] Documentation of base algorithm and base implementation

### ISSUE THREAD

**Issue by im-Kitsch** [takuseno/d3rlpy#155]
Hi, 

thanks a lot for your excellent work. I wanna to ask if you would like to add documentation of "Base Implementation" and "Base Algorithm". That would be pretty helpful when we make custom algorithms. 

Thanks a lot for your work again.

**Comment by itsmesaisatish** [comment]
This will help for others to contribute and enhance this library

**Comment by takuseno** [comment]
Sorry for taking too long to address this. I have added an example to create your own original algorithm on top of d3rlpy codebase:
- https://github.com/takuseno/d3rlpy/blob/master/examples/custom_algo.py

Probably, this is the best I can provide for now. Please let me close this issue. Feel free to reopen this if there is any further discussion.
