### ISSUE TITLE
[REQUEST] Support bounded action spaces

### ISSUE THREAD

**Issue by AaronLiu1997** [takuseno/d3rlpy#157]
**Is your feature request related to a problem? Please describe.**

I want to use the d3rlpy framework for problems with bounded action spaces. At the moment, d3rlpy seems to generate potentially unbounded actions which cause evaluation to crash.

**Describe the solution you'd like**
Support for bounded action spaces.

**Comment by takuseno** [comment]
@AaronLiu1997 Hi, thanks for the issue. Basically, all continuous control algorithms in d3rlpy are bounded by tanh activation function. You can optionally use [ActionScaler](https://d3rlpy.readthedocs.io/en/v1.0.0/references/preprocessing.html#action) to postprocess action scales based on datasets or environments.
