### ISSUE TITLE
[BUG] Assertion error on running example

### ISSUE THREAD

**Issue by JensCardon** [takuseno/d3rlpy#16]
**Describe the bug**
Whenever running the example code for creating an MDPdataset instance, I get an assertion error.

**To Reproduce**
in order to reproduce, run the following code:
observations = np.random.random((1000, 100))
actions = np.random.random((1000, 4))
rewards = np.random.random(1000)
terminals = np.random.randint(2, size=1000)
dataset = MDPDataset(observations, actions, rewards, terminals)

**Additional context**
I get the following error using python 3.6 and 3.7.
Traceback (most recent call last):
  File "/Users/jens/Documents/CameraShading/Artificial-Eye/jj.py", line 77, in <module>
    dataset = MDPDataset(observations, actions, rewards, terminals)
  File "d3rlpy/dataset.pyx", line 138, in d3rlpy.dataset.MDPDataset.__init__
AssertionError

**Comment by JensCardon** [comment]
solved when installing from source

**Comment by takuseno** [comment]
@JensCardon Thank you for reporting this! I found this assertion is a bit confusing to users. So I've removed this in the next release.
