### ISSUE TITLE
Can't figure out the problem while training

### ISSUE THREAD

**Issue by Mashex** [takuseno/d3rlpy#160]
Hi @takuseno, 

I am trying to use IQL for offline training. I used the MDPDataset function with the parameters to build the dataset. Upon training with this dataset using the fit function with any batch size(200 in this example), I am getting the below issue (8 is the length of each action transition, and 197 is the length of each observation transition).

Here is some of my code: 
```
iql = d3rlpy.algos.IQL(use_gpu=True, batch_size = 8192)

scorer = evaluate_on_environment(env, self_play=True)

iql.fit(mdp,
        eval_episodes=mdp,
        n_epochs=5,
        save_interval=3,
        scorers={
            'environment': scorer,
            'td_error': d3rlpy.metrics.td_error_scorer
        }
)
```

And here is the error:
```
2022-01-22 20:01.59 [debug    ] RoundIterator is selected.
2022-01-22 20:01.59 [info     ] Directory is created at d3rlpy_logs\IQL_20220122200159
2022-01-22 20:01.59 [warning  ] Skip building models since they're already built.
2022-01-22 20:01.59 [info     ] Parameters are saved to d3rlpy_logs\IQL_20220122200159\params.json params={'action_scaler': None, 'actor_encoder_factory': {'type': 'default', 'params': {'activation': 'relu', 'use_batch_norm': False, 'dropout_rate': None}}, 'actor_learning_rate': 0.0003, 'actor_optim_factory': {'optim_cls': 'Adam', 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False}, 'batch_size': 200, 'critic_encoder_factory': {'type': 'default', 'params': {'activation': 'relu', 'use_batch_norm': False, 'dropout_rate': None}}, 'critic_learning_rate': 0.0003, 'critic_optim_factory': {'optim_cls': 'Adam', 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False}, 'expectile': 0.7, 'gamma': 0.99, 'generated_maxlen': 100000, 'max_weight': 100.0, 'n_critics': 2, 'n_frames': 1, 'n_steps': 1, 'real_ratio': 1.0, 'reward_scaler': None, 'scaler': None, 'tau': 0.005, 'use_gpu': 0, 'value_encoder_factory': {'type': 'default', 'params': {'activation': 'relu', 'use_batch_norm': False, 'dropout_rate': None}}, 'value_learning_rate': 0.0003, 'value_optim_factory': {'optim_cls': 'Adam', 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False}, 'weight_temp': 3.0, 'algorithm': 'IQL', 'observation_shape': (197,), 'action_size': 8}
Epoch 1/100: 0%
0/63376 [00:01<?, ?it/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_10336/2844033681.py in <module>
      4         save_interval=5,
      5         scorers={
----> 6             'environment': scorer
      7         }
      8 )

D:\Software\miniconda3\envs\RLAI\lib\site-packages\d3rlpy\base.py in fit(self, dataset, n_epochs, n_steps, n_steps_per_epoch, save_metrics, experiment_name, with_timestamp, logdir, verbose, show_progress, tensorboard_dir, eval_episodes, save_interval, scorers, shuffle, callback)
    421                 scorers,
    422                 shuffle,
--> 423                 callback,
    424             )
    425         )

D:\Software\miniconda3\envs\RLAI\lib\site-packages\d3rlpy\base.py in fitter(self, dataset, n_epochs, n_steps, n_steps_per_epoch, save_metrics, experiment_name, with_timestamp, logdir, verbose, show_progress, tensorboard_dir, eval_episodes, save_interval, scorers, shuffle, callback)
    635                     # update parameters
    636                     with logger.measure_time("algorithm_update"):
--> 637                         loss = self.update(batch)
    638 
    639                     # record metrics

D:\Software\miniconda3\envs\RLAI\lib\site-packages\d3rlpy\base.py in update(self, batch)
    745 
    746         """
--> 747         loss = self._update(batch)
    748         self._grad_step += 1
    749         return loss

D:\Software\miniconda3\envs\RLAI\lib\site-packages\d3rlpy\algos\iql.py in _update(self, batch)
    206         metrics.update({"critic_loss": critic_loss})
    207 
--> 208         actor_loss = self._impl.update_actor(batch)
    209         metrics.update({"actor_loss": actor_loss})
    210 

D:\Software\miniconda3\envs\RLAI\lib\site-packages\d3rlpy\torch_utility.py in wrapper(self, *args, **kwargs)
    338     def wrapper(self: Any, *args: Any, **kwargs: Any) -> np.ndarray:
    339         set_train_mode(self)
--> 340         return f(self, *args, **kwargs)
    341 
    342     return wrapper

D:\Software\miniconda3\envs\RLAI\lib\site-packages\d3rlpy\torch_utility.py in wrapper(self, *args, **kwargs)
    320 
    321                 tensors.append(tensor)
--> 322             return f(self, *tensors, **kwargs)
    323 
    324         return wrapper

D:\Software\miniconda3\envs\RLAI\lib\site-packages\d3rlpy\algos\torch\ddpg_impl.py in update_actor(self, batch)
    181         self._actor_optim.zero_grad()
    182 
--> 183         loss = self.compute_actor_loss(batch)
    184 
    185         loss.backward()

D:\Software\miniconda3\envs\RLAI\lib\site-packages\d3rlpy\algos\torch\iql_impl.py in compute_actor_loss(self, batch)
    127         assert self._policy
    128 
--> 129         dist = self._policy.dist(batch.observations)
    130 
    131         # unnormalize action via inverse tanh function

D:\Software\miniconda3\envs\RLAI\lib\site-packages\d3rlpy\models\torch\policies.py in dist(self, x)
    167         mu = self._mu(h)
    168         clipped_logstd = self._compute_logstd(h)
--> 169         return Normal(mu, clipped_logstd.exp())
    170 
    171     def forward(

D:\Software\miniconda3\envs\RLAI\lib\site-packages\torch\distributions\normal.py in __init__(self, loc, scale, validate_args)
     48         else:
     49             batch_shape = self.loc.size()
---> 50         super(Normal, self).__init__(batch_shape, validate_args=validate_args)
     51 
     52     def expand(self, batch_shape, _instance=None):

D:\Software\miniconda3\envs\RLAI\lib\site-packages\torch\distributions\distribution.py in __init__(self, batch_shape, event_shape, validate_args)
     54                 if not valid.all():
     55                     raise ValueError(
---> 56                         f"Expected parameter {param} "
     57                         f"({type(value).__name__} of shape {tuple(value.shape)}) "
     58                         f"of distribution {repr(self)} "

ValueError: Expected parameter loc (Tensor of shape (8192, 8)) of distribution Normal(loc: torch.Size([8192, 8]), scale: torch.Size([8192, 8])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
```

I have tried using the round iterator separately to see if there is any issue, and also manually created torch tensors, and computed the backward using the default gradient function to pinpoint the issue. 

Do you have any idea what could cause this in the dataset? Any location or hint to start searching would also be very helpful. 
This issue is because of the data only since the IQL algorithm works perfectly on another dataset that I tested. 

Thanks in advance :D

**Comment by takuseno** [comment]
@Mashex Hi, thanks for the issue! I'm suspecting the inverse tanh operation. Can you narrower the clipping on this line to fix this issue?
https://github.com/takuseno/d3rlpy/blob/f20f1e662e1c22daaa7b2bc9c8cd4771fd2965f8/d3rlpy/algos/torch/iql_impl.py#L130

Let's say `[-0.9, 0.9]`.
```
clipped_actions = batch.actions.clamp(-0.9, 0.9)
```

**Comment by Mashex** [comment]
Thanks for the quick reply @takuseno!

I delved a bit deeper and created the dataset again on a per-file basis. I think the issue is because some of the actions are all zeros (happens when the actor is still)

The below actions are picked from the middle of the dataset

` [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],`

Would this be causing an issue? And if yes, do you have any suggestions as to what I should do? 

I have also attached the MDPDataset file of the particular file that is causing a problem if you want to inspect it yourself.

[problem_MDPDataset.zip](https://github.com/takuseno/d3rlpy/files/7918636/problem_MDPDataset.zip)

**Comment by takuseno** [comment]
Thanks for sharing the dataset. I don't think all zeros are the problem. But I'll check your dataset and update you later.

**Comment by Mashex** [comment]
Thank you very much! 

EDIT: I used the compute_stats function in the MDPDataset, seems like there is a nan value somewhere, can't find it by directly searching the printed action string though. 

`ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_4000/874628221.py in <module>
----> 1 mdp.compute_stats()

D:\Software\miniconda3\envs\RLAI\lib\site-packages\d3rlpy\dataset.pyx in d3rlpy.dataset.MDPDataset.compute_stats()

<__array_function__ internals> in histogram(*args, **kwargs)

~\AppData\Roaming\Python\Python37\site-packages\numpy\lib\histograms.py in histogram(a, bins, range, normed, weights, density)
    790     a, weights = _ravel_and_check_weights(a, weights)
    791 
--> 792     bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
    793 
    794     # Histogram is an integer or a float array depending on the weights.

~\AppData\Roaming\Python\Python37\site-packages\numpy\lib\histograms.py in _get_bin_edges(a, bins, range, weights)
    424             raise ValueError('`bins` must be positive, when an integer')
    425 
--> 426         first_edge, last_edge = _get_outer_edges(a, range)
    427 
    428     elif np.ndim(bins) == 1:

~\AppData\Roaming\Python\Python37\site-packages\numpy\lib\histograms.py in _get_outer_edges(a, range)
    322         if not (np.isfinite(first_edge) and np.isfinite(last_edge)):
    323             raise ValueError(
--> 324                 "autodetected range of [{}, {}] is not finite".format(first_edge, last_edge))
    325 
    326     # expand empty range to avoid divide by zero

ValueError: autodetected range of [nan, nan] is not finite`

**Comment by Mashex** [comment]
Thank you very much!

I just found something that might help in finding the problem.

I used the MDPDataset compute_stats function, and it is giving an error, more specifically in the np.histogram line

`np.histogram(episode_returns, bins=20)`

```ValueError  Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_4000/874628221.py in <module>
----> 1 mdp.compute_stats()

D:\Software\miniconda3\envs\RLAI\lib\site-packages\d3rlpy\dataset.pyx in d3rlpy.dataset.MDPDataset.compute_stats()

<__array_function__ internals> in histogram(*args, **kwargs)

~\AppData\Roaming\Python\Python37\site-packages\numpy\lib\histograms.py in histogram(a, bins, range, normed, weights, density)
    790     a, weights = _ravel_and_check_weights(a, weights)
    791 
--> 792     bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
    793 
    794     # Histogram is an integer or a float array depending on the weights.

~\AppData\Roaming\Python\Python37\site-packages\numpy\lib\histograms.py in _get_bin_edges(a, bins, range, weights)
    424             raise ValueError('`bins` must be positive, when an integer')
    425 
--> 426         first_edge, last_edge = _get_outer_edges(a, range)
    427 
    428     elif np.ndim(bins) == 1:

~\AppData\Roaming\Python\Python37\site-packages\numpy\lib\histograms.py in _get_outer_edges(a, range)
    322         if not (np.isfinite(first_edge) and np.isfinite(last_edge)):
    323             raise ValueError(
--> 324                 "autodetected range of [{}, {}] is not finite".format(first_edge, last_edge))
    325 
    326     # expand empty range to avoid divide by zero

ValueError: autodetected range of [nan, nan] is not finite```

I further tried to use the np.isfinite function, and np.isnan function to see if that is true, but everything looks ok, all values in np.isnan are False and and True in np.isfinite.

**Comment by takuseno** [comment]
Yeah, I tried this.
```
>>> np.all(np.logical_not(np.isnan(dataset.rewards)))
False
```
It seems nan values in rewards caused this.

**Comment by Mashex** [comment]
Yes, my model just finished training, everything is fine now. 

My suggestion would be to put the compute stats function at the beginning of the fit/fitter function so that anyone in future can catch these problems early on, without getting unrelated problems from pytorch. 

I had one more thing to ask you, how would you go about optimizing your GPU usage, mine was very low at the around 1024 - 8192 batch size ( around 25% utilization) and only when I increased the batch size to 262144 did I reach 62% utilization, but that too is very sporadic. 

Here is the screenshot of my Wandb experiment tracking if you want to have a look 

<img width="1608" alt="Screenshot 2022-01-23 at 5 02 52 PM" src="https://user-images.githubusercontent.com/17247257/150676352-462a32da-a11c-485d-9e73-b442285345aa.png">

**Comment by takuseno** [comment]
Good to hear things go well. I'll add nan checks to the dataset initialization.

Regarding the GPU usage, it's hard to hit the high utilization with the small size observation such as non-image observations in MuJoCos. If you use image observations and set the large batch size, you'll see the higher utilization.

**Comment by Mashex** [comment]
Noted. Thanks for helping out! 
You have done a great job in this library, please do let me know if I can help out in any shape or form to improve the library.

**Comment by GongYanfu** [comment]
Hi, How dou you use wandb in this project?
can you share the code?
