### ISSUE TITLE
Install from source

### ISSUE THREAD

**Issue by im-Kitsch** [takuseno/d3rlpy#162]
Hi,

I wanna to hack inside the code to custom some features. If I install from source, should I  run `pip install -e .`  from the newest commit or from the tag `v1.00`?

Thanks so much in advance.
Best

**Comment by takuseno** [comment]
@im-Kitsch Hi, thanks for the issue. If you want to hack .ased on v1.0.0, you should use the tag. If you want to hack the latest code, you should use the master branch. Either way will work for you.

**Comment by im-Kitsch** [comment]
thanks a lot @takuseno
