### ISSUE TITLE
Questions on MDPDataset and training

### ISSUE THREAD

**Issue by Kongyj** [takuseno/d3rlpy#166]
Hi, thanks for you d3rlpy, which is a great job. I have some questions about this implementation, could you please help me?

1. What is the difference between MDPDataset.terminals and MDPDataset.episode_terminals. I have referred to the official documentation but failed to understand the difference [https://d3rlpy.readthedocs.io/en/v1.0.0/references/generated/d3rlpy.dataset.MDPDataset.html](url). According to my experiences, there should be only one termination array which is based on the done feedback of gym.envs (observation, reward, done, info = env.step(action)). 

2. As mentioned in https://github.com/takuseno/d3rlpy/issues/98#issuecomment-884878592, the dataset uses a virtual first reward and a virtual last action. However, in the latest code, I could not find the creation of the virtual first reward and last action as presented in the issue#98 (https://github.com/takuseno/d3rlpy/blob/master/d3rlpy/online/iterators.py#L194). Does this mean that the virtual first reward in MDPDataset is no longer used? If so, what is the current structure of MDPDataset because the initial reward does not exist. Furthermore, if a virtual first reward is used, it means that the reward is delayed by one step. Hence, I think that you are supposed to use batch.next_reward rather than batch.reward during training (https://github.com/takuseno/d3rlpy/blob/master/d3rlpy/algos/torch/dqn_impl.py#L122).

**Comment by takuseno** [comment]
@Kongyj Hi, thanks for the issue.

1.
The difference between `terminals` and `episode_terminals` is very simple. `terminal` represents the environmental termination while `episode_terminals` represents timeouts. So if you want to divide episodes without no terminal states, you can use `episode_terminals` as timeout flags.

2.
`next_reward` property no longer exists in `Transition`. The dataset structure is now completely the same as D4RL, which means there are no virtual first rewards.
```
observations = [o1, o2, o3, ...]
actions = [a1, a2, a3, ...]
rewards = [r1, r2, r2, ...] # r1 = r(o1, a1)
```

**Comment by Kongyj** [comment]
@takuseno Many thanks for your explanation.

**Comment by shivamvats** [comment]
@takuseno It seems to me that the terminal observation of an episode is discarded in Q learning. Is that correct?

In https://github.com/takuseno/d3rlpy/blob/master/d3rlpy/algos/qlearning/base.py#L684 ,  the last observation of an episode is stored in `next_observation` but this is not added to the buffer if `clip_episode` is true.

**Comment by takuseno** [comment]
@shivamvats That's right. This is because there is no way to use terminal states in standard Q-learning setup.

**Comment by jhcharlotte** [comment]
@takuseno Shouldn't the terminal states be used in Q-learning when episode timeout?

**Comment by jhcharlotte** [comment]
Sorry, i don't get you. Shouldn't terminal states be used in Q-learning when episode timeout occurs? Otherwise, what is the meaning of the two variables' terminal 'and' truncated 'returned by env. step()? Just go back to the 'done' step like before
