### ISSUE TITLE
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 2. Got 1 and 8

### ISSUE THREAD

**Issue by MAX00008888** [takuseno/d3rlpy#168]
Hi, so sorry to interupt you. I want to ask how to solve this problem.

**Comment by MAX00008888** [comment]
File "C:\Users\56549\miniconda3\envs\d3rlpy\lib\site-packages\d3rlpy\convEncoder.py", line 64, in forward
    h = torch.cat([h, action], dim=2)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 2. Got 1 and 8 in dimension 1

**Comment by MAX00008888** [comment]
class ConvEncoderWithAction(nn.Module):
    def __init__(self, observation_shape, action_size, feature_size):
        super(ConvEncoderWithAction, self).__init__()
        # self.feature_size = feature_size
        self.feature_size = feature_size
        self.action_size = action_size
        self.fc1 = nn.Linear(observation_shape[0] + action_size, 64)
        self.fc2 = nn.Linear(64, feature_size)

    def forward(self, x, action): # action is also given
        #h = torch.cat([x, action], dim=1)
        # conv1 = nn.Conv1d(x.shape[0], 1, kernel_size=1).to(device)
        # h = torch.relu(conv1(h.reshape(1, h.shape[0], h.shape[1])))
        #CRR AWAC Agri Need
        conv1 = nn.Conv1d(x.shape[0], 1, kernel_size=1).to(device)
        h = torch.relu(conv1(x.reshape(1, x.shape[0], x.shape[1])))

        if action.ndim==2:
            action= action.reshape(1,action.shape[0],action.shape[1])
        h = torch.cat([h, action], dim=2)
        h = torch.relu(self.fc1(h))
        h = torch.relu(self.fc2(h))
        return h

**Comment by takuseno** [comment]
@MAX00008888 Hi, can you share a minimal code that I can reproduce your issue?

**Comment by MAX00008888** [comment]
@takuseno Thank you so much for your reply. I'm using d3rlpy to do causal RL, I build a encoderfactory, and in the with action part, I did like this:
class ConvEncoderWithAction(nn.Module):
    def __init__(self, observation_shape, action_size, feature_size):
        super(ConvEncoderWithAction, self).__init__()
        # self.feature_size = feature_size
        self.feature_size = feature_size
        self.action_size = action_size
        self.fc1 = nn.Linear(observation_shape[0] + action_size, 64)
        self.fc2 = nn.Linear(64, feature_size)

    def forward(self, x, action): # action is also given
        #h = torch.cat([x, action], dim=1)
        # conv1 = nn.Conv1d(x.shape[0], 1, kernel_size=1).to(device)
        # h = torch.relu(conv1(h.reshape(1, h.shape[0], h.shape[1])))
        #CRR AWAC Agri Need
        conv1 = nn.Conv1d(x.shape[0], x.shape[1], kernel_size=1).to(device)
        h = torch.relu(conv1(x.reshape(1, x.shape[0], x.shape[1])))

        if action.ndim==2:
            action= action.reshape(1,action.shape[0],action.shape[1])
        h = torch.cat([h, action], dim=2)
        h = torch.relu(self.fc1(h))
        h = torch.relu(self.fc2(h))
        return h

**Comment by MAX00008888** [comment]
In ddpg_imp , I change the compute-critic-loss part to this
    def compute_critic_loss(
        self, batch: TorchMiniBatch, q_tpn: torch.Tensor
    ) -> torch.Tensor:
        assert self._q_func is not None
        #因果发现
        import cdt
        import torch
        import tensorflow as tf
        import networkx as nx
        from cdt.causality.graph import GES

        cols = ['age', 'educ', 'black', 'hispan', 'married', 'nodegree', 're74', 're75']
        data = pd.DataFrame(batch.observations.cpu().numpy(),
                                  columns=cols)
        #maxP = 3  # maximum number of parents when searching the graph
        #Record=ges(data, 'local_score_BIC', maxP=maxP, parameters=parameters)
        glasso = cdt.independence.graph.Glasso()
        skeleton = glasso.predict(data)
        new_skeleton = cdt.utils.graph.remove_indirect_links(skeleton, alg='aracne')
        model = cdt.causality.graph.GES()
        output_graph = model.predict(data, new_skeleton)
        matrix=nx.adjacency_matrix(output_graph).todense()

        #action=因果发现结果
        action = torch.Tensor(matrix).to(device)

        # rewards=BIC
        from causallearn.score.LocalScoreFunction import local_score_BIC
        rewards = local_score_BIC(data,1,[1])

        return self._q_func.compute_error(
            obs_t=batch.observations,
            # act_t=batch.actions,
            #临时调整
            act_t=action,
            # rew_tp1=batch.next_rewards,
            # 临时调整
            rew_tp1=rewards,
            q_tp1=q_tpn,
            ter_tp1=batch.terminals,
            gamma=self._gamma ** batch.n_steps,
            use_independent_target=self._target_reduction_type == "none",
            masks=batch.masks,
        )

**Comment by MAX00008888** [comment]
@takuseno Thank you soooo much!!!! I will try again.
