### ISSUE TITLE
The IQL algorithm keeps 0 evaluation score on antmaze enviornments

### ISSUE THREAD

**Issue by KeysaYoung** [takuseno/d3rlpy#171]
I tried the code below, and the environment eval score kept 0.  Is there something that I missed?

                      import d3rlpy
                      
                      dataset, env = d3rlpy.datasets.get_d4rl("antmaze-medium-play-v0")
                      
                      iql = d3rlpy.algos.IQL(expectile=0.9, weight_temp=10, use_gpu=True)
                      
                      iql.fit(dataset,
                              eval_episodes=dataset,
                              n_epochs=100,
                              scorers={
                                  'environment': d3rlpy.metrics.evaluate_on_environment(env),
                                  'td_error': d3rlpy.metrics.td_error_scorer
                              })

**Comment by takuseno** [comment]
@KeysaYoung Thanks for reporting this. I recently changed IQL with non squashed gaussian distribution policy, which is used in the author's code.
https://github.com/takuseno/d3rlpy/commit/6b67f8d356f5a2ae4f72014f2eed6ef37061747d

I observed that this change makes a big difference. Can you try again with the master branch?

**Comment by takuseno** [comment]
I never tried antmaze environments yet. But, paper seems propses we should subtract rewards by 1.
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/5235131/161379177-7b839851-59d6-4073-8ab2-890a2f2de0a4.png">

**Comment by takuseno** [comment]
I confirmed that d3rlpy's IQL achieves the same performance as what they reported in antmaze.
https://github.com/takuseno/d3rlpy/blob/master/reproductions/finetuning/iql.py

Let me close this issue.
