### ISSUE TITLE
[Bug] Reference to _active_logger is dropped before contained SummaryWriter is closed

### ISSUE THREAD

**Issue by YannickVogt** [takuseno/d3rlpy#172]
Hi,
first of all I wanted to mention that I really enjoy working with your library.

When working with multiple GPUs and tensorboard I encountered a small bug.

In `LearnableBase.fitter()` `_active_logger` gets dereferenced. https://github.com/takuseno/d3rlpy/blob/070b7926aae1bbab67fd35fd6e74db68a0e5b520/d3rlpy/base.py#L678
However, the `_active_logger` can contain a `_writer` which is an instance of tensorboardX SummaryWriter, which is then not closed.
This then leads to an error when the process terminates (as is https://github.com/pytorch/fairseq/issues/2357#issuecomment-739790602).

This issue can be resulved by adding `self._active_logger._writer.close()` before dropping the reference (care for the case where `_writer` does not exist).

Best regards
Yannick

**Comment by takuseno** [comment]
Sorry for the late notice. This issue should be solved at this commit.
https://github.com/takuseno/d3rlpy/commit/677da669699379d9374167112610d722c7ac47b8

Feel free to reopen this issue.
