### ISSUE TITLE
The CQL algorithm fails on Adorit environments.

### ISSUE THREAD

**Issue by KeysaYoung** [takuseno/d3rlpy#173]
I tried to reproduce the CQL experiments on Adroit/Antmaze environments following your examples, but the results almost kept 0 score. Can you give a complete example for running CQL on Adroit/Antmaze ?

**Comment by takuseno** [comment]
The reproduction code in d3rlpy is configured for locomotion datasets. Please check the CQL paper that should describe the hyperparameter difference.

**Comment by takuseno** [comment]
This seems fixed now? Feel free to open this issue again.

**Comment by Zed-Wu** [comment]
@KeysaYoung Have you found the correct hyperparameters for Adroit/Antmaze environments? I meet the same problems that CQL drops its performance dramatically using the default hyperparameters, except for the door-expert. Could you share the hyperparameters setting if you find the right one?
