### ISSUE TITLE
Batch.actions

### ISSUE THREAD

**Issue by MAX00008888** [takuseno/d3rlpy#174]
Hi, sorry to bother you.

I created a MDPDataset , and the actions is a ndarray of (600,8). I just want to use the first 8 lines. 
But when I use `batch.actions[0:8]`, I get the diffirent first 8 lines.

**Comment by MAX00008888** [comment]
How can `batch.actions[0:8]` get the same output as `actions[0:8}`

**Comment by takuseno** [comment]
I'm afraid I don't understand your question here. Do you mean you want to use the shape of `(8, 8)` actions in your dataset? `batch` always contains different samples because it's a mini-batch uniformly sampled from dataset.

**Comment by MAX00008888** [comment]
Thank you for your reply.
My actions is as below:
![image](https://user-images.githubusercontent.com/101794848/162197230-37f07fee-fd2a-4960-8d64-da719c030da0.png)
and I just want the fist 8 lines in it.
![image](https://user-images.githubusercontent.com/101794848/162197418-c2893add-b391-4119-9e12-ada8ccef8e4a.png)

**Comment by takuseno** [comment]
Yeah, that's how batch sampling works. Let's say `batch_size=256`, which means that 256 samples are randomly selected from the dataset. There is no sliding window mechanism.

**Comment by MAX00008888** [comment]
Thank you so much!!
