### ISSUE TITLE
Action-conditioned network

### ISSUE THREAD

**Issue by MAX00008888** [takuseno/d3rlpy#175]
Hi, I'm learning the encoderfactory part, I don't understand the use of Action-conditioned network. 
What  is it used for？

Hope to receive your reply.

**Comment by takuseno** [comment]
The latest tutorial page might be useful for you.
https://d3rlpy.readthedocs.io/en/latest/tutorials/customize_neural_network.html

**Comment by MAX00008888** [comment]
Thank you so much!! Could you please help me with another problem #176

**Comment by takuseno** [comment]
Let me close this issue, but feel free open this issue again.
