### ISSUE TITLE
Different size of batch.observations

### ISSUE THREAD

**Issue by MAX00008888** [takuseno/d3rlpy#176]
Hi, sorry to bother you again!

When I create a MDPDataset , I got `batch.observations `in the shape of(100,8).  But when used in scorer module, it shows `batch.observations` in the shape of(99.8).

**Comment by MAX00008888** [comment]
```
 for episode in episodes:
        for batch in _make_batches(episode, WINDOW_SIZE, algo.n_frames):
             actions = algo.predict(batch.observations)
```
This is  batch.observations/actions in scorer

**Comment by takuseno** [comment]
I'm afraid I don't understand your issue. When do you get `(100, 8)` and `(99, 8)`?

**Comment by MAX00008888** [comment]
![image](https://user-images.githubusercontent.com/101794848/162609890-3adf2358-78b6-4c51-9a8c-96c3a5f0cfb4.png)

**Comment by MAX00008888** [comment]
when I use` data= pd.DataFrame(batch.next_observations.cpu().numpy(), columns=cols)` to get data
![image](https://user-images.githubusercontent.com/101794848/162609920-0a8544f0-3baf-481c-9397-02de4329d64a.png)

**Comment by takuseno** [comment]
Sorry I don't know what's issue here. In scorer functions, the batch size is basically meaningless because it's based on `WINDOW_SIZE`. In training codes, the batch size is `batch_size` parameter in your algorithm.

**Comment by MAX00008888** [comment]
Thank you. I don't mean the batch size, I mean` batch.actions` size. It is in the size of(100,8). But in scorer,  `batch.actions` is in the size of (99,8).

**Comment by takuseno** [comment]
Yeah, it's not an issue anyway. Let me close this issue.
