### ISSUE TITLE
How to create dataset?

### ISSUE THREAD

**Issue by hn2** [takuseno/d3rlpy#177]
How was dataset create in :
dataset, env = d3rlpy.datasets.get_dataset("hopper-medium-v0")
for offline training:
sac.fit(dataset, n_steps=1000000)

Can you elaborate on different ways (preferably with code, with or without env) to create the trajectories dataset for offline training?
One way that I know is to train with sb3, save the replay buffer and then transform it.
What are the other ways and how did you do that?

**Comment by takuseno** [comment]
Please check the latest tutorial: https://d3rlpy.readthedocs.io/en/latest/tutorials/index.html .
