### ISSUE TITLE
d3rlpy callbacks

### ISSUE THREAD

**Issue by hn2** [takuseno/d3rlpy#178]
Does d3rlpy support the concept of callbacks like stable baselines 3?
[https://stable-baselines3.readthedocs.io/en/master/guide/callbacks.html]
Specifically, SaveOnBestTrainingRewardCallback:
[https://colab.research.google.com/github/Stable-Baselines-Team/rl-colab-notebooks/blob/sb3/monitor_training.ipynb]

**Comment by takuseno** [comment]
Yes, please check documentation.
https://d3rlpy.readthedocs.io/en/v1.0.0/references/generated/d3rlpy.algos.SAC.html#d3rlpy.algos.SAC.fit

**Comment by hn2** [comment]
Do you have an example how to use callbacks?
