### ISSUE TITLE
[BUG] Cannot add last observation to episode and implicit terminals

### ISSUE THREAD

**Issue by alxlampe** [takuseno/d3rlpy#18]
At first, thank you very much @takuseno for this super nice and clean written RL library! 🥇 

**Describe the bug**

*1. Truncated episodes:*
In my RL project, I am running complete episodes and add them to the replay buffer afterwards by creating `Episode` objects and using `buffer.append_episode(episode)`. 
I saw, that one cannot pass in `next_observations` and `terminals` to create episodes. When looking at the internals how you create transitions, it makes sense, because `next_observations` do not have the corresponding `next_actions` and `next_rewards` available. 
Since you are creating `next_observations` from `observations`, the last observation  (which is `next_observations[-1]`) of the episode is always missing.  

Furthermore, if `next_observations[-1]` is a *real* terminal state, where `terminals[-1]=True`, the agent would never see it in training. 

The question is, are you using `next_actions` and `next_rewards` somewhere explicitly in the algorithms? 

*2. Implicit terminals:*
I also noticed, that you are implicitly setting `terminal=True` for the last observation. There are use cases, where there are no *real* terminal states, e.g. in environments with infinite time horizon (control environments like `Pendulum-v0`). Setting `terminal=True` at the end of an episode for those environments would result in wrong TD targets. 

**To Reproduce**

In `Pendulum-v0` environment, the episode is truncated after 200 time steps. The `info` dict, that is returned each time step indicates the truncation with `info={'TimeLimit.truncated': True}`.
```python
import gym
import numpy as np

from d3rlpy.dataset import Episode

if __name__ == '__main__':
    env = gym.make('Pendulum-v0')

    states = []
    actions = []
    rewards = []
    next_states = []
    dones = []

    done = False
    state = env.reset()
    while not done:
        action = env.action_space.sample()
        next_state, reward, done, info = env.step(action)

        states.append(state)
        rewards.append(reward)
        actions.append(action)
        next_states.append(next_state)
        dones.append(done)

        state = next_state

    # info of last env step indicates time truncated episode -> no terminal state
    print(info)
    if info.get('TimeLimit.truncated', False):
        dones[-1] = False

    states = np.stack(states, axis=0)
    actions = np.stack(actions, axis=0)
    rewards = np.stack(rewards, axis=0)

    episode = Episode(env.observation_space.shape,
                      env.action_space.low.size,
                      states,
                      actions,
                      rewards)
    # len(episode)==199 since next_states not being used to create it
    print(len(episode))

``` 
**Expected behavior**
I would expect, that one can control if `terminals=True` should be set at the end of the episode. 
To get an episode length of 200 in the `Pendulum-v0` example, one can extend action and reward vectors with dummy values at the last time step but at the risk that this dummy values are used somewhere in the library.

A workaround is to use `buffer.append` in a for loop, to add the episode to the buffer. But one must not forget to set `buffer.prev_observation`, `buffer.prev_actions` etc. to `None` afterwards.

**Edit:**

I dived a bit deeper into your algo update functions and found that you are using `rew_tp1` to calculate the TD target with
```python
y = rew_tp1 + gamma * q_tp1
```
If I add transitions to the buffer as mentioned above, the reward of the current time step should be used instead of `rew_tp1` (as far as I know). 
Furthermore, I see that you are not taking the entropy bonus (e.g. in SAC) into account in the TD target calculation. Is this intended? In other libraries, it was added here. 
Sorry for mixing up so much topics. Should I create separate issues for discussion?

**Comment by takuseno** [comment]
@alxlampe Thank you for reporting the issue!

#### truncated episode
The `next_observation` with `terminal=True` is the last observation in an episode. So, I believe this observation is used to compute backup, but not used as `s_t`. In this sense, nothing is dropped.

`next_rewards` is the one often used in training, especially computing TD errors.
```
td_error = (Q(s_t, a_t) - r_t+1 - gamma * max_a Q(s_t+1, a)) ^ 2
```

`next_actions` is currently not used in d3rlpy (I guess so). But, I'm letting the tuple of all of `(s_t, a_t, r_t, s_t+1, a_t+1, r_t+1)` to handle any kinds of algorithms. Thus there is a change that some algorithms use this in the future.

#### implicit terminals
Thank you for pointing this out. Currently, `MDPDataset` does not differentiate `environment terminal` and `time-limit terminal`. But, I understand those should be differentiated for better performance in some cases. So I'm planning to add something like `env_terminals` in addition to the current `terminals`.

```
# terminals is the environment terminals
# the value at backup is clipped based on terminals
dataset = MDPDataset(obsevations, actions, rewards, terminals)

# terminals just indicate the last observation in episodes
# the value at backup is clipped based on env_terminals
dataset = MDPDataset(observations, actions, reward, terminals, env_terminals)
```

I hope this helps. Thank you!

**Comment by takuseno** [comment]
For the SAC, the entropy is used in the target calculation.
https://github.com/takuseno/d3rlpy/blob/5793793513218f51bf3db92c1c825df0329ea6e6/d3rlpy/algos/torch/sac_impl.py#L102

**Comment by alxlampe** [comment]
@takuseno thanks for your quick response!

> For the SAC, the entropy is used in the target calculation.
> https://github.com/takuseno/d3rlpy/blob/5793793513218f51bf3db92c1c825df0329ea6e6/d3rlpy/algos/torch/sac_impl.py#L102

My fault! I have looked at DDPG implementation 🤦 

#### Next reward:
> `next_rewards` is the one often used in training, especially computing TD errors.
> 
> ```
> td_error = (Q(s_t, a_t) - r_t+1 - gamma * max_a Q(s_t+1, a)) ^ 2
> ```
I totally agree with this notation, but I think and also have seen it in mostly all libraries and examples, that `env.step()` returns `next_reward` and not `reward` even if it is named `reward`.  As far as I understand, when we write:
```python
state = env.reset()
next_state, reward, done, info = env.step(action)
```
`reward` is the reward we are receiving when we transition from `state` (`s_t`) to `next_state` (`s_t+1`). In the td-error equation, `reward` is `r_t+1`. 

But if I create episodes as described in my previous post, `r_t+2` would be used in the td update.   


 #### truncated episode
> The `next_observation` with `terminal=True` is the last observation in an episode. So, I believe this observation is used to compute backup, but not used as `s_t`. In this sense, nothing is dropped. For example, if there are 200 observations, the number of transitions should be 199.


I have a little example and hope my problem becomes clearer:
Assuming that we create an episode with 5 transitions:

```
observations = [s0, s1, s2, s3, s4]
actions = [a0, a1, a2, a3, a4]
rewards = [r1, r2, r3, r4, r5]
next_observations = [s1, s2, s3, s4, s5]
terminals = [0, 0, 0, 0, 1]
``` 

The *terminal state* is `s5`. What the agent should learn here is that  if it is in state `s4` and takes the action `s4`, it would reach the terminal state `s5` and get the terminal reward `r5`. 
Now I write it in python using `Episode` object and simply use integers for the corresponding states and actions. 
I create the episode object just using `observations` and not using `next_observations`:
```python
import numpy as np

from d3rlpy.dataset import Episode

if __name__ == '__main__':
    observations = np.array([0, 1, 2, 3, 4]).reshape(-1, 1)
    next_observations = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)
    terminals = np.array([0, 0, 0, 0, 1]).reshape(-1, 1)
    actions = np.array([0, 1, 2, 3, 4]).reshape(-1, 1)
    rewards = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)
    episode = Episode((1,), 1, observations, actions, rewards)
```

Having a look at the last transition, I get:
```python
episode.transitions[-1].observation
# >>> array([3.], dtype=float32)
episode.transitions[-1].action
# >>> array([3.], dtype=float32)
episode.transitions[-1].reward
# >>> 4.0
episode.transitions[-1].next_reward
# >>> 5.0
episode.transitions[-1].next_observation
# >>> array([4.], dtype=float32)
episode.transitions[-1].terminal
# >>> 1.0
```

Using this transition for training, the agent learns that when in state `s3` and choosing action `a3` it will end up in terminal state `s4` and receives *next reward*  `r5`.  
Here you can also see the impact of using *next reward* instead of *reward*.

What do you think? Am I missing something?

**Comment by takuseno** [comment]
#### next reward
Basically, if you do this.
```
state = env.reset()
next_state, reward, done, info = env.step(action)
```
Those are `state=s_t`, `next_state=s_t+1`and `reward=s_t+1` and `done` indicates if `s_t+1` is a terminal state. In d3rlpy, those are correctly handled.

#### trucated episode
In your case, there are 4 transitions. And the last transition including `s4` and `s5` is also used to train. I'd like you take a look at  the documentation to make things clear.

https://d3rlpy.readthedocs.io/en/v0.40/references/generated/d3rlpy.dataset.Transition.html#d3rlpy.dataset.Transition

The novelty of the data structure in d3rlpy is the `Transition` object has the following properties.
```
transition.observations
transition.actions
transition.rewards
transition.next_obsevations
transition.next_actions
transition.next_rewards
transition.terminals
```
which will cover all algorithms.

**Comment by alxlampe** [comment]
@takuseno Thanks. I've edited my previous post.  I got it know. 
I noticed that you always add reward `r(t=0)=0.0` and `terminal(t=0)=False` and also always take action `a_t+1` on the terminal state. I've never seen this before. 

Thanks again.
