### ISSUE TITLE
Cython-numpy data ordering inconsistency for n>1 (3) channel images

### ISSUE THREAD

**Issue by gunshi** [takuseno/d3rlpy#180]
Hey!
Firstly, thanks so much for this great library, which has made experimenting with offline RL things so smooth for me!
I recently shifted from Atari to using Minigrid with this library, and noticed something strange about the TransitionMiniBatch class:

1. the mini grid observations I use are in a 3 channel image format (not to be interpreted as an RGB image, the state is a 16x5x3 matrix where 16x5 are the dimensions of the grid and the channel store info like object ID, object state, object color). I structure my dataset in a channel first format as expected (3x16x5)
2. When I view the dataset's transitions list, everything looks fine, but when I sample some transitions from this list and cast them to a batch object like so:
`trans_batch = TransitionMiniBatch(transitions)  # here I'm just using the full list of transitions for the example` 
I see that the observations field gets jumbled up from what it was before. Crucially:

trans_batch.observations[0]!=transitions[0].observation

Upon closer investigation, it looks like the data stored in this observation gets read in a different order when the batch object is made:

trans_batch.observations[0]:

`
array([[[ 2,  5,  0,  2,  5],
        [ 0,  2,  5,  0,  2],
        [ 5,  0,  2,  5,  0],
        [ 2,  5,  0,  1,  0],
        [ 0,  1,  0,  0,  1],
        [ 0,  0,  2,  5,  0],
        [ 2,  5,  0,  1,  0],
        [ 0,  6,  2,  0,  1],
        [ 0,  0,  2,  5,  0],
        [ 2,  5,  0,  1,  0],
        [ 0,  1,  0,  0,  1],
        [ 0,  0,  2,  5,  0],
        [ 2,  5,  0,  1,  0],
        [ 0,  6,  2,  0,  1],
        [ 0,  0,  2,  5,  0],
        [ 2,  5,  0,  1,  0]],

       [[ 0,  6,  2,  0,  1],
        [ 0,  0,  2,  5,  0],
        [ 2,  5,  0,  1,  0],
        [ 0,  1,  0,  0,  1],
        [ 0,  0,  2,  5,  0],
        [ 2,  5,  0,  1,  0],
        [ 0, 10,  0,  0,  1],
        [ 0,  0,  2,  5,  0],
        [ 2,  5,  0,  2,  5],
        [ 0, 11,  1,  0,  2],
        [ 5,  0,  2,  5,  0],
        [ 2,  5,  0,  1,  0],
        [ 0,  1,  0,  0,  1],
        [ 0,  0,  2,  5,  0],
        [ 2,  5,  0,  1,  0],
        [ 0,  1,  0,  0,  1]],

       [[ 0,  0,  2,  5,  0],
        [ 2,  5,  0,  1,  0],
        [ 0,  1,  0,  0,  1],
        [ 0,  0,  2,  5,  0],
        [ 2,  5,  0,  1,  0],
        [ 0,  1,  0,  0,  1],
        [ 0,  0,  2,  5,  0],
        [ 2,  5,  0,  1,  0],
        [ 0,  1,  0,  0,  1],
        [ 0,  0,  2,  5,  0],
        [ 2,  5,  0,  1,  0],
        [ 0,  1,  0,  0,  8],
        [ 1,  0,  2,  5,  0],
        [ 2,  5,  0,  2,  5],
        [ 0,  2,  5,  0,  2],
        [ 5,  0,  2,  5,  0]]], dtype=uint8)
`

but transitions[0].observation:

`
array([[[ 2,  2,  2,  2,  2],                                                                                                                                                                     
        [ 2,  1,  1,  1,  2],
        [ 2,  1,  6,  1,  2],
        [ 2,  1,  1,  1,  2],
        [ 2,  1,  6,  1,  2],
        [ 2,  1,  6,  1,  2],
        [ 2,  1,  1,  1,  2],
        [ 2,  1, 10,  1,  2],
        [ 2,  2, 11,  2,  2],
        [ 2,  1,  1,  1,  2],
        [ 2,  1,  1,  1,  2],
        [ 2,  1,  1,  1,  2],
        [ 2,  1,  1,  1,  2],
        [ 2,  1,  1,  1,  2],
        [ 2,  1,  1,  8,  2],
        [ 2,  2,  2,  2,  2]],

       [[ 5,  5,  5,  5,  5],
        [ 5,  0,  0,  0,  5],
        [ 5,  0,  2,  0,  5],
        [ 5,  0,  0,  0,  5],
        [ 5,  0,  2,  0,  5],
        [ 5,  0,  2,  0,  5],
        [ 5,  0,  0,  0,  5],
        [ 5,  0,  0,  0,  5],
        [ 5,  5,  1,  5,  5],
        [ 5,  0,  0,  0,  5],
        [ 5,  0,  0,  0,  5],
        [ 5,  0,  0,  0,  5],
        [ 5,  0,  0,  0,  5],
        [ 5,  0,  0,  0,  5],
        [ 5,  0,  0,  1,  5],
        [ 5,  5,  5,  5,  5]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]]], dtype=uint8)
`

Intuitively I can see that what seems to be happening is the the flattened data of both arrays is the same, but is being read out in different column/row/channel major formats. I'm not sure how to proceed from here (can work on removing my extra code and creating a reproducible example code), but was wondering if this is something that is a trivial bug that can be seen by looking at dataset.pyx code.
Best,
Gunshi

update: I added the line : states = np.ascontiguousarray(states) before initializing the MDPdataset object, and that seems to fix it

**Comment by takuseno** [comment]
Sorry for the late response. It looks like an issue of memory alignment if you could fix the issue by your solution (`np.ascontiguousarray`). This is because the observations are copied via low-level `memcpy` opeation to speed up memory copies.
https://github.com/takuseno/d3rlpy/blob/9ce191b9384164c3558e9cd24334c8febe5ebc8f/d3rlpy/dataset.pyx#L1087

So for now, I'd recommend you should make sure the data is contiguous.
