### ISSUE TITLE
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

### ISSUE THREAD

**Issue by hn2** [takuseno/d3rlpy#182]
I get this error when loading a trained model
Whta does it mean?

ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

**Comment by takuseno** [comment]
Please share the code that we can reproduce your issue.

**Comment by hn2** [comment]
\Anaconda3\lib\site-packages\d3rlpy\base.py in load_model(self, fname)
    321         """
    322         assert self._impl is not None, IMPL_NOT_INITIALIZED_ERROR
--> 323         self._impl.load_model(fname)
    324 
    325     def fit(

~\Anaconda3\lib\site-packages\d3rlpy\algos\torch\base.py in load_model(self, fname)
    123     def load_model(self, fname: str) -> None:
    124         chkpt = torch.load(fname, map_location=map_location(self._device))
--> 125         set_state_dict(self, chkpt)
    126 
    127     @property

~\Anaconda3\lib\site-packages\d3rlpy\torch_utility.py in set_state_dict(impl, chkpt)
     86         obj = getattr(impl, key)
     87         if isinstance(obj, (torch.nn.Module, torch.optim.Optimizer)):
---> 88             obj.load_state_dict(chkpt[key])
     89 
     90 

~\Anaconda3\lib\site-packages\torch\optim\optimizer.py in load_state_dict(self, state_dict)
    144         saved_lens = (len(g['params']) for g in saved_groups)
    145         if any(p_len != s_len for p_len, s_len in zip(param_lens, saved_lens)):
--> 146             raise ValueError("loaded state dict contains a parameter group "
    147                              "that doesn't match the size of optimizer's group")
    148 

ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

**Comment by takuseno** [comment]
Hmm, sorry, it's not a code we can execute on our end...

**Comment by hn2** [comment]
I first load the algo class from json and print it, it appears ok (?)

d3rlpy.algos.cql.CQL(action_scaler=None, actor_encoder_factory=d3rlpy.models.encoders.VectorEncoderFactory(hidden_units=[512, 512, 512, 512], activation='relu', use_batch_norm=False, dropout_rate=None, use_dense=False), actor_learning_rate=1e-05, actor_optim_factory=d3rlpy.models.optimizers.OptimizerFactory(optim_cls='Adam', betas=[0.9, 0.999], eps=1e-08, weight_decay=0, amsgrad=False), alpha_learning_rate=0.0001, alpha_optim_factory=d3rlpy.models.optimizers.OptimizerFactory(optim_cls='Adam', betas=[0.9, 0.999], eps=1e-08, weight_decay=0, amsgrad=False), alpha_threshold=10.0, batch_size=256, conservative_weight=5.0, critic_encoder_factory=d3rlpy.models.encoders.VectorEncoderFactory(hidden_units=[512, 512, 512, 512], activation='relu', use_batch_norm=False, dropout_rate=None, use_dense=False), critic_learning_rate=1e-05, critic_optim_factory=d3rlpy.models.optimizers.OptimizerFactory(optim_cls='Adam', betas=[0.9, 0.999], eps=1e-08, weight_decay=0, amsgrad=False), gamma=0.99, generated_maxlen=100000, impl=<d3rlpy.algos.torch.cql_impl.CQLImpl object at 0x0000015F7FBFA630>, initial_alpha=1.0, initial_temperature=1.0, n_action_samples=10, n_critics=2, n_frames=1, n_steps=1, q_func_factory=d3rlpy.models.q_functions.MeanQFunctionFactory(bootstrap=False, share_encoder=False), real_ratio=1.0, scaler=None, soft_q_backup=False, target_reduction_type='min', tau=0.005, temp_learning_rate=0.0001, temp_optim_factory=d3rlpy.models.optimizers.OptimizerFactory(optim_cls='Adam', betas=[0.9, 0.999], eps=1e-08, weight_decay=0, amsgrad=False), use_gpu=None)

**Comment by hn2** [comment]
I have a complex custom env and it is not easy to share the code.

**Comment by takuseno** [comment]
It seems it's very hard to tell what's exactly wrong with your code. I could imagine that the error  usually occurs when there is a difference in model parameters (layer size, observation size etc).

**Comment by hn2** [comment]
Difference between what and what?
I am first loading the model definition from json:
cql = d3rlpy.algos.CQL.from_json(...json file name)
Which works fine.
I then try to load the model:
cql.load_model(...model.pt file name)
Which fails with 
~\Anaconda3\lib\site-packages\d3rlpy\base.py in load_model(self, fname)
    321         """
    322         assert self._impl is not None, IMPL_NOT_INITIALIZED_ERROR
--> 323         self._impl.load_model(fname)
    324 
    325     def fit(

~\Anaconda3\lib\site-packages\d3rlpy\algos\torch\base.py in load_model(self, fname)
    123     def load_model(self, fname: str) -> None:
    124         chkpt = torch.load(fname, map_location=map_location(self._device))
--> 125         set_state_dict(self, chkpt)
    126 
    127     @property

~\Anaconda3\lib\site-packages\d3rlpy\torch_utility.py in set_state_dict(impl, chkpt)
     86         obj = getattr(impl, key)
     87         if isinstance(obj, (torch.nn.Module, torch.optim.Optimizer)):
---> 88             obj.load_state_dict(chkpt[key])
     89 
     90 

~\Anaconda3\lib\site-packages\torch\optim\optimizer.py in load_state_dict(self, state_dict)
    144         saved_lens = (len(g['params']) for g in saved_groups)
    145         if any(p_len != s_len for p_len, s_len in zip(param_lens, saved_lens)):
--> 146             raise ValueError("loaded state dict contains a parameter group "
    147                              "that doesn't match the size of optimizer's group")
    148 

ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

**Comment by hn2** [comment]
Train code

**Comment by hn2** [comment]
`import gym
import os
import d3rlpy
import shutil
from datetime import datetime
from os.path import join as path_join

import numpy as np
from d3rlpy.algos import cql
from d3rlpy.models.encoders import VectorEncoderFactory
from d3rlpy.online.buffers import ReplayBuffer
from d3rlpy.online.explorers import LinearDecayEpsilonGreedy

v_models_dir = r'C:\Temp'

def get_subdir_with_pattern(path, pattern):
    for sd in os.scandir(path):
        if sd.is_dir() and pattern in str(sd.path):
            subdir = sd.path

    return subdir

v_online_model_dir = path_join(*[v_models_dir, 'test-d3rlpy', 'online'])

if not os.path.exists(v_online_model_dir):
    os.makedirs(v_online_model_dir)

print(f'Model name:{v_online_model_dir}')

v_encoder_factory = VectorEncoderFactory(hidden_units=[512, 512])

v_online_class = d3rlpy.algos.CQL(actor_learning_rate=0.00001, 
                            critic_learning_rate=0.00001,
                            batch_size=32,
                            actor_encoder_factory=v_encoder_factory,
                            critic_encoder_factory=v_encoder_factory,
                            use_gpu=True)

print(v_online_class)

env = gym.make('Pendulum-v0')

buffer = ReplayBuffer(maxlen=1000000, env=env)

print("Start training model...")

v_online_class.fit_online(env=env,
                          buffer=buffer,
                          n_steps=1000,
                          logdir=v_online_model_dir,
                          tensorboard_dir=v_online_model_dir)

v_online_model_file_name = path_join(v_online_model_dir, 'model.pt')
v_online_class.save_model(v_online_model_file_name)
v_online_model_json_dir = get_subdir_with_pattern(v_online_model_dir, 'CQL')
v_online_model_json_file_name = path_join(v_online_model_json_dir, 'params.json')
shutil.copy(v_online_model_json_file_name, v_online_model_dir)
shutil.rmtree(v_online_model_json_dir)

print(f'Model file save to {v_online_model_file_name}, Params file save to {v_online_model_json_file_name}')

print("End training online model...")

env.close()`

**Comment by hn2** [comment]
test code

**Comment by hn2** [comment]
import numpy as np
import multiprocessing
from collections import deque
from datetime import timedelta
from distutils.util import strtobool
from os.path import join as path_join

import gym
import d3rlpy

v_models_dir = r'C:\Temp'

v_online_model_dir = path_join(*[v_models_dir, 'test-d3rlpy', 'online'])

v_online_model_file_name_json = path_join(v_online_model_dir, 'params.json')
v_online_model_file_name = path_join(v_online_model_dir, 'model.pt')

v_online_class = d3rlpy.algos.CQL.from_json(v_online_model_file_name_json)
print(v_online_class)

v_online_model = v_online_class.load_model(v_online_model_file_name)
print(v_online_model)

env = gym.make('Pendulum-v0')

obs = env.reset()
done = False

while not done:
    action = v_online_model.predict(obs)
    obs, _, done, _ = env.step(action)

**Comment by hn2** [comment]
AttributeError: 'NoneType' object has no attribute 'predict'

**Comment by hn2** [comment]
Save and load works.

**Comment by hn2** [comment]
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group
Still facing this error and struggling to debug it
Any advice?

**Comment by hn2** [comment]
This is solved

**Comment by jp18813100494** [comment]
I meet the same problem! Can you tell me how to solve it? Thanks a lot!

**Comment by jp18813100494** [comment]
> 

ok!thanks!
