### ISSUE TITLE
The ideal simulation is not working.

### ISSUE THREAD

**Issue by onozuka777** [takuseno/d3rlpy#190]
We are considering a very simple ideal simulation.
The number of states is 6, from 0 to 5.
The number of actions is assumed to be 20, from 0 to 19.
I made randomized actions data.

Performing Act1(=0) with St0(=0) will result in St1(=1) and state 1.
Once a state is in that state, it will not go down and will not go up unless the appropriate action is taken.
Performing Act2(=1) with St+1(=1) will result in St+2(=2).
Similarly.
St+2(=2) & Act3(=2) → St+3 = 3
St+3(=3) & Act4(=3) →St+4 = 4
St+4(=4) & Act5(=4) →St+5 = 5
When S reaches 5, the flag for done stands.
If S reaches 5 at the end of the game, the player is rewarded 1; if not, the player is rewarded -1.
We have created an ideal MDPDataset.
Essentially, the behavior that is encouraged is
S=0 and Act=0
S=1 and Act=1
S=2 and Act=2
S=3 and Act=3
S=4 and Act=4

but in fact

S=0 and Act=0
S=1 and Act=0 →I don't understand here
S =2 and Act=2
S =3 and Act=3 
S=4 and Act=4

 Does anyone have any ideas on what to do?
I am somewhat suspicious of the timing of t.t+1,,,,t+n.
Any help would be appreciated.

**Comment by takuseno** [comment]
Since none of us are AI consultants, we cannot answer the questions about the specific tasks. Let me close this issue.
