### ISSUE TITLE
DiscreteRandomPolicy sample_action always returns numpy.array([0])

### ISSUE THREAD

**Issue by gil-frenkel-marpai** [takuseno/d3rlpy#191]
https://github.com/takuseno/d3rlpy/blob/f20f1e662e1c22daaa7b2bc9c8cd4771fd2965f8/d3rlpy/algos/random_policy.py#L123

Using np.random.randint with the arg low=1 (_action_size=1 is constant 1),  no matter the size, will always give arrays of zeros.

It should return array of 0s and 1s in general? I mean vector of {0,1}^N

Or am I missing something?

Why not writing instead:

<code>
np.random.randint(2, size=self._action_size)
</code>

Thanks!

**Comment by takuseno** [comment]
I possibly don't understand your question here.

**Comment by gil-frenkel-marpai** [comment]
Thank you @takuseno for your quick reply.
Sorry, I had a lack of fundamental  understanding.
I noticed that I have to use _create_impl method to set the action_size.

Thank you

**Comment by gil-frenkel-marpai** [comment]
Closing the issue
