### ISSUE TITLE
[BUG] ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by maziar840** [takuseno/d3rlpy#197]
Hi all,

When I try to import `MDPDataset` using `from d3rlpy.dataset import MDPDataset`

I get: 

`ImportError: /lib64/libm.so.6: version 'GLIBC_2.27' not found (required by somepath/venv/lib/python3.8/site-packages/d3rlpy/dataset.cpython-38-x86_64-linux-gnu.so)`

Should I install d3rlpy from source?

**Comment by takuseno** [comment]
We have rarely seen this error recently. But, in this case, it might be worth trying to install source.
https://d3rlpy.readthedocs.io/en/v1.1.1/installation.html#install-from-source

**Comment by maziar840** [comment]
Thanks. Installing from source worked.
