### ISSUE TITLE
Cannot save policy to cpu when model is trained in gpu！

### ISSUE THREAD

**Issue by jp18813100494** [takuseno/d3rlpy#198]
D3RLPY provide the way to save and load policy through torch.jit. But in the production environment, we always train the model in GPU and  apply inference in cpu. The current torch.jit.save and torch.jit.load cannot support both cpu and gpu! Or anyone can tell me how to train moel in GPU and save/load policy in CPU?
<img width="810" alt="image" src="https://user-images.githubusercontent.com/26135273/177595515-0510e542-37ec-4671-8865-0efff81b6e0a.png">

**Comment by takuseno** [comment]
@jp18813100494 Thanks for the issue. This is essentially not a d3rlpy issue. Please use `map_location` to place all tensors on CPU.

```
torch.jit.load('policy.pt', map_location='cpu')
```
Please see https://pytorch.org/docs/stable/generated/torch.jit.load.html .

**Comment by takuseno** [comment]
Let me close this issue. Feel free to open this issue if you have anything to discuss.
