### ISSUE TITLE
Sum of rewards

### ISSUE THREAD

**Issue by maziar840** [takuseno/d3rlpy#199]
I have a pretty noob question. I would like to calculate the sum of rewards using the policy I've trained with CQL on test set and compare it with sum of rewards using the policy that I have collected the data with (basically the rewards in the test set).

Should I use predict after I fitted the model? Or am I making a mistake?

Cheers

**Comment by takuseno** [comment]
Sorry, I'm afraid I don't understand your question. Do you want to compute the rewards of pre-collected trajectory with a trained algorithm? If this is what you want, it's impossible to do that. Instead, you need to evaluate the trained policy with the environment just as the standard RL evaluation procedure.

**Comment by maziar840** [comment]
That makes total sense. Thank you.

So is there an example on how to deploy a model trained using d3rlpy inside an external environment? I used a simulator to gather my dataset, so it's not an env like cartpole that I can import to evaluate using the CQL.fit() for example.

I would like to export the model and use it to predict the action depending on the state inside the simulator. Is this currently possible?

**Comment by maziar840** [comment]
Great, that's what I needed. Thank you!
