### ISSUE TITLE
[REQUEST] Classmethods Episode.from_transitions and MDPDataset.from_episodes

### ISSUE THREAD

**Issue by alxlampe** [takuseno/d3rlpy#20]
**Is your feature request related to a problem? Please describe.**
I want to create `Episode` objects from a list of `Transition` objects and `MDPDataset` objects from a list of episodes, since there is some internal processing like setting terminals as mentioned in #18. 

To bypass this, I was trying to create episodes from transitions and then add all episodes to a new MDPDataset but both require to input observations, actions, rewards and terminals on object creation. 

**Describe the solution you'd like**
It would be nice to have something like this:
```python
# create episode from transitions
transitions = create_transitions()
episode = Episode.from_transitions(transitions)

# create dataset from episodes
episodes = create_episodes()
dataset = MDPDataset.from_episodes(episodes)

# adding more episodes to an existing dataset then would also make sense
dataset.append_episode(episodes)
```
What do you think?

**Comment by takuseno** [comment]
@alxlampe Sorry for being extremely late... I've added `TimeLimit` wrapper support for online and offline.
https://github.com/takuseno/d3rlpy/commit/2add9214c640382d0628cf5c49ed1fa752b394ec
https://github.com/takuseno/d3rlpy/commit/41ba2bd7d0a8cb4fed09c4eacfcd409c069f73a1

I hope this meets your requirements.

**Comment by alxlampe** [comment]
@takuseno no problem for being late. Since you share this nice library, I am always able to implement it by myself :)

But actually I am currently not using your library because  I don't get the performance  that I get with my own implementation and I cannot figure out why. 
I kept this open because I wanted to know if there already is a nice solution and for your own decision if you want to close it. So you can close this issue. 

Thanks for the info that you now support time limited termination.
