### ISSUE TITLE
[BUG] While using mixed dataset from d4rl *-v0 ,there comes an env error

### ISSUE THREAD

**Issue by houmaolin** [takuseno/d3rlpy#201]
:warning:
- Please don't post bug reports without a minimal example codes. Otherwise, it will take really long to solve the issue.
- Please be polite in discussion. This is an open-sourced project by voluntary contributors.

**Describe the bug**
While using mixed dataset from d4rl *-v0 ,there comes an env error

**To Reproduce**
(erl) [14:10:22] root:offline # python iql.py --gpu 3 --dataset 'walker2d-mixed-v0'

**Expected behavior**

**Additional context**
![image](https://user-images.githubusercontent.com/22930365/179454831-ec688d5d-0639-4aa2-8f28-4f8ee3d6029b.png)

**Comment by takuseno** [comment]
As far as I know, there is no `mixed` dataset anymore. The closest one is `walker2d-mixed-replay-v0`.

**Comment by houmaolin** [comment]
> As far as I know, there is no `mixed` dataset anymore. The closest one is `walker2d-medium-replay-v0`.

http://rail.eecs.berkeley.edu/datasets/offline_rl/gym_mujoco/
In the d4rl datasets, there still exists *mixed.hdf5 file (only for v0 version). And in CQL, they used it too.
![image](https://user-images.githubusercontent.com/22930365/179456840-dea45dad-b8fd-405e-b2a0-c65dff988251.png)
But the author of CQL dosen't explain the content of mixed dataset.

**Comment by takuseno** [comment]
There is no mixed datasets in d4rl. I believe it's obsolete.
https://github.com/rail-berkeley/d4rl/blob/master/d4rl/gym_mujoco/__init__.py

Anyway, this isn't an issue of d3rlpy. Please report it to d4rl.

**Comment by houmaolin** [comment]
> There is no mixed datasets in d4rl. I believe it's obsolete. https://github.com/rail-berkeley/d4rl/blob/master/d4rl/gym_mujoco/__init__.py
> 
> Anyway, this isn't an issue of d3rlpy. Please report it to d4rl.

Thanks for applying.You are right about this and sorry for bothering you.
