### ISSUE TITLE
[BUG] Incorrect Typing for torch_api Decorator

### ISSUE THREAD

**Issue by Jingyu6** [takuseno/d3rlpy#204]
**Description**
When I try to overwrite the `update` method in `d3rlpy/algos/torch/dqn_impl.py`, mypy complains about the following:

```
Argument 1 to "train_api" has incompatible type "ndarray[Any, Any]"; expected "Callable[..., ndarray[Any, Any]]"
```

**Expected Behavior**
I'm not sure how the project checks this typing but it looks to me that the signature of the `torch_api` decorator in `d3rlpy/torch_utility.py` should be:

```python
def torch_api(
    scaler_targets: Optional[List[str]] = None,
    action_scaler_targets: Optional[List[str]] = None,
    reward_scaler_targets: Optional[List[str]] = None,
) -> Callable[..., Callable[..., np.ndarray]]:
```

Thanks a lot!

**Comment by takuseno** [comment]
@Jingyu6 Thanks for pointing this out. I've updated this as you suggested in this commit.
https://github.com/takuseno/d3rlpy/commit/9001959ae2d4c043e6eab73770a1441e70bed096
