### ISSUE TITLE
Not able to import data 

### ISSUE THREAD

**Issue by SeasonedLeo** [takuseno/d3rlpy#206]
**Describe the bug**
Tried to run the sample code to import carpool and pendulum data, code breaks with an error "Unable to open file (file signature not found)"

**To Reproduce**
from d3rlpy.algos import DQN
from d3rlpy.datasets import get_cartpole
from d3rlpy.metrics.scorer import evaluate_on_environment
dataset, env = get_cartpole()

**Expected behavior**
I was expecting the data to get imported without issues/error

**Additional context**
I tried reinstalling d3rlpy and h5 using conda.

--------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_16276\981570718.py in <module>
      1 # obtain dataset
----> 2 dataset, env = get_cartpole()

7     # load dataset
     58     dataset = MDPDataset.load(
---> 59         data_path, create_mask=create_mask, mask_size=mask_size
     60     )
     c:\Users\Anaconda3\envs\tf\lib\site-packages\h5py\_hl\files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, fs_strategy, fs_persist, fs_threshold, fs_page_size, page_buf_size, min_meta_keep, min_raw_keep, locking, **kwds)
    505                                  fs_persist=fs_persist, fs_threshold=fs_threshold,
    506                                  fs_page_size=fs_page_size)
--> 507                 fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
    508 
    509             if isinstance(libver, tuple):

c:\Users\Anaconda3\envs\tf\lib\site-packages\h5py\_hl\files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    218         if swmr and swmr_support:
    219             flags |= h5f.ACC_SWMR_READ
...
h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (file signature not found)

**Comment by takuseno** [comment]
@SeasonedLeo Thanks for the issue. It seems that the conda package for Windows seems outdated. Could you re-install d3rlpy via `pip` command?

**Comment by SeasonedLeo** [comment]
I did pip install , still gettibg same error , not sure what I am missing here . Any pointers wpuld be helpful thx

**Comment by takuseno** [comment]
Can you make sure you uninstall d3rlpy first, and install it again?
```
$ pip uninstall d3rlpy
$ python -c "import d3rlpy"  # this should fail
$ pip install d3rlpy
```

**Comment by SeasonedLeo** [comment]
Thanks for responding tried everything you suggested still not working .:(

**Comment by takuseno** [comment]
Can you show the result of this command?
```
$ python -c "import d3rlpy; print(d3rlpy.__version__)"
```

**Comment by SeasonedLeo** [comment]
So i have two different versions in two different environment in anaconda in my pc one cersion is 1.1.1 and another is 0.91 . I have not specified any version while pip installing

**Comment by takuseno** [comment]
Can you try `conda uninstall d3rlpy` too?
```
$ conda uninstall d3rlpy
$ pip install d3rlpy
```
The version `0.91` should not be installed by default anymore, however, `conda` command might install it on Windows.

**Comment by SeasonedLeo** [comment]
Hello thaanks for helping out with this . I tried pip installing  d3rlpy on google colab . It works fine . It appears that some settings in my laptop might be causing issues not sure what it is . I tried everything you suggested . I would recommend closing this issue .

Thanks again
