### ISSUE TITLE
Loading saved model and continuing training ignores the Use GPU flag

### ISSUE THREAD

**Issue by michaelpulis-UOM** [takuseno/d3rlpy#207]
As the title states, when the model is loaded from storage and `model.fit` is called, the use_gpu flag seems to be ignored and the model trains without the gpu. This is when using the IQL algorithm

**Comment by takuseno** [comment]
I imagine you're using `from_json` to initialize algorithms. Please use `use_gpu` argument to enable it again. See the document here: https://d3rlpy.readthedocs.io/en/v1.1.1/references/generated/d3rlpy.algos.SAC.html#d3rlpy.algos.SAC.from_json

**Comment by takuseno** [comment]
Let me close this issue since it seems resolved.

**Comment by michaelpulis-UOM** [comment]
Hi.

What I actually did was the following:
1. re instantiated the model from scratch with the exact same parameters and `use_gpu` set to `True`
``` python
train_model = IQL(
  use_gpu=True,
  ...
)
```

2. I called build with dataset on the same dataset, and then loaded the model weights
``` python
train_model.build_with_dataset(dataset)
train_model.load_model(f'{path}')
```

3. I continued training
``` python
train_model.fit(...)
```

This has worked for me :)
