### ISSUE TITLE
Eval hangs itself

### ISSUE THREAD

**Issue by lettersfromfelix** [takuseno/d3rlpy#209]
Hi, 
First of all thanks for your awesome work! 
I've got a problem with getting d3rlpy for my own env and dataset up and running. It's an environment which I previously also trained with gym algorithms. It's a never-ending task, i.e. without terminals but just continuously moving a robot.
First question: Did I understand it correct that therefore all terminals of each step of all (non-dead) episodes should be 0, but the episode_terminals after the episode length = 1.0?
If so: When I add a split of that dataset as eval_episodes, the process seems to loop indefinitely, at least my processors are running and steps are executed, but it's never ending (tried it with just 1 epoch for train and test, still after 20min no results).
Have I forgotten anything or is this some bug somewhere? 
Thanks in advance!

**Comment by takuseno** [comment]
@lettersfromfelix Hi, thanks for the issue. I don't fully understand your setup. Sounds like your env never ends so that the evaluation episode continues forever. In that case, you should use `TimeLimit` wrapper to truncate the episode.
https://github.com/openai/gym/blob/907b1b20dd9ac0cba5803225059b9c6673702467/gym/wrappers/time_limit.py#L8

**Comment by lettersfromfelix** [comment]
Hi @takuseno , thanks for the awesomely fast reply! Just had a look into it, we actually reset the environment by ourselves after x time steps, so you're absolutely right, we never issued the truncated signal. Thanks for that hint, seems to work now! 

Just to make sure: What were my assumptions still correct to set the terminals array (when creating the Dataset) to all 0, and the episodes_terminals to 1.0 basically after the same max_ep_length as used for the TimeLimit Wrapper?

**Comment by takuseno** [comment]
Good to hear it works now. And, yes, your setup is correct if all of the episodes are truncated by time out.

**Comment by lettersfromfelix** [comment]
Thanks, you're awesome man!
