### ISSUE TITLE
Question: on-policy algorithm

### ISSUE THREAD

**Issue by Mamba413** [takuseno/d3rlpy#213]
`d3rlpy` is remarkably flexible!  I wonder whether `d3rlpy` can run an on-policy SAC algorithm by conducting: 

```python
policy = d3rlpy.algos.SAC(batch_size=1)
buffer = d3rlpy.online.buffers.ReplayBuffer(maxlen=1, env=env)
policy.fit_online(env, buffer, n_steps=1000)
```

**Comment by takuseno** [comment]
@Mamba413 Hi, SAC is an off-policy method, so it never becomes on-policy. If you meant "online", you can do it with the above code.

**Comment by Mamba413** [comment]
@takuseno Thanks! It addresses my question.
