### ISSUE TITLE
Question regarding plotting Cumulative Reward graph on Tensorboard 

### ISSUE THREAD

**Issue by ajam74001** [takuseno/d3rlpy#218]
I really enjoyed working with this repo. Thank you very much for your great work! 
I was just wondering how to have the cumulative reward plots on Tensorboard for deep Q network algorithm.

Thank you again!

**Comment by takuseno** [comment]
@ajam74001 Hi, thanks for the issue. Please specify `tensorboard_dir` at `fit` or `fit_online` method:
https://d3rlpy.readthedocs.io/en/v1.1.1/references/logging.html#tensorboard

**Comment by ajam74001** [comment]
Hi @takuseno, Many thanks for your reply. I did the same, but the cumulative reward plot does not appear on the tensorboard specifically.

**Comment by takuseno** [comment]
Did you set metrics like this?
https://github.com/takuseno/d3rlpy/blob/672aeced77071349fa172c7a9bd1f418acf16fe6/reproductions/offline/cql.py#L45

**Comment by ajam74001** [comment]
Yeah. 
`cql.fit(dataset, n_steps=50000,scorers={
        'environment': evaluate_on_environment(env), 
            'advantage': discounted_sum_of_advantage_scorer, # smaller is better
            'td_error': td_error_scorer, # smaller is better
            'value_scale': average_value_estimation_scorer
    }, tensorboard_dir='runs-atari-final')`

**Comment by takuseno** [comment]
Ah, you need to set `eval_episodes=dataset`.

**Comment by ajam74001** [comment]
oh, Thank you very much for your help. 
cheers!

**Comment by ajam74001** [comment]
Hi dear @takuseno, sorry for reopening the issue. I have the same problem with the online training. the environment graph doesn't appear on the Tensorboard. I will appreciate your help. 

`dqn.fit_online(env,
               buffer,
               explorer,
               eval_env=eval_env,
               n_steps=10000000,
               n_steps_per_epoch=10000, tensorboard_dir='runs-atari-final')`

**Comment by takuseno** [comment]
That's weird. I confirmed I get the tensorboard log data under `logdir` in this example.
```
import d3rlpy
import gym

env = gym.make("CartPole-v0")
dqn = d3rlpy.algos.DQN()
buffer = d3rlpy.online.buffers.ReplayBuffer(1000, env=env)
dqn.fit_online(env, buffer, n_steps=1000, n_steps_per_epoch=100, tensorboard_dir="logdir")
```

**Comment by ajam74001** [comment]
I ran the same code, here is the tensorboard output
<img width="1032" alt="Screen Shot 2022-08-29 at 10 09 35" src="https://user-images.githubusercontent.com/47214448/187130561-e5912661-99bd-4a0e-a72e-3306e42bfd54.png">

**Comment by takuseno** [comment]
I'm seeing the `evaluation` metrics in my tensorboard when I give `eval_env=eval_env`:
![image](https://user-images.githubusercontent.com/5235131/187186385-a208fd96-418e-42fe-82f3-4fc05e36dad3.png)

Please confirm that you're giving `eval_env=eval_env` and check `evaluation` metrics.

**Comment by takuseno** [comment]
Just for sure, here is the full example:
```
import d3rlpy
import gym

env = gym.make("CartPole-v0")
eval_env = gym.make("CartPole-v0")
dqn = d3rlpy.algos.DQN()
buffer = d3rlpy.online.buffers.ReplayBuffer(1000, env=env)
dqn.fit_online(env, buffer, eval_env=eval_env, n_steps=1000, n_steps_per_epoch=100, tensorboard_dir="logdir")
```

**Comment by ajam74001** [comment]
Thank you very much for your reply. So, the evaluation graph is equivalent to the cumulative reward here?

**Comment by takuseno** [comment]
Yes, that's right.

**Comment by ajam74001** [comment]
Great! thanks a lot for your help.

**Comment by Zebin-Li** [comment]
Hi,

I have a quick question regarding plotting the cumulative reward curve in Tensorboard is that, I noticed there should be a piece of code like `eval_env=eval_env` from the above discussion. However, in my case, I don't have the "env" only with an offline dataset to train the offline RL. So how to I plot the reward curve? Thank you very much!
