### ISSUE TITLE
Buggy problem in some corner cases in DBCQ,

### ISSUE THREAD

**Issue by ehsan-shahbazi** [takuseno/d3rlpy#221]
**Describing the bug**
Hi, when using Discrete_BCQ, if the discrete imitator according to an action flexibility pass only one action, and from other hand we encounter the lowest q_estimation between all actions in the only passed action, the following bug occurs:   

by normalizing the q_values to the minimum of them, the only valid action's q_value will be 0. and when we try to make action = argmax (mask_of_imitator * normalized_q_functions) we actually are taking argmax(zeroes) which is the first index, 0.

**Expected behavior**
We expected to have the only passed action from the imitator's mask as the action.

**Fix**
When normalizing the q_values with the  minimum of them in predict function, add a constant to all of normalized_q_funcitons to avoid the problem.

**Comment by takuseno** [comment]
@ehsan-shahbazi Hi, sorry, I'm afraid I don't understand your description above. I believe we don't have issues in `DiscreteBCQ`'s action selection:
https://github.com/takuseno/d3rlpy/blob/3678b33a332dddbe55004f5ab040307ee02fabca/d3rlpy/algos/torch/bcq_impl.py#L321
```
value = self._q_func(x)
normalized_value = value - value.min(dim=1, keepdim=True).values   # all values are the bigger than 0
action = (normalized_value * cast(torch.Tensor, mask)).argmax(dim=1)  # mask low probability actions and take the best action
```

**Comment by ehsan-shahbazi** [comment]
Dear @takuseno, thanks for agile answer.
The problem is when you do normalize the values, you always have at least one zero in that, Now if the mask is 0 in all the actions except that one the normalized_value * cast(torch.Tensor, mask) will be completely zeroes. for example:

values = [7, 2, 1, 5, 2, 5]
mask = [0, 0, 1, 0, 0, 0]
we expect the action to be 2 here, but:
normalized values will be -> values - min(values) = [6, 1, 0, 4, 1, 4]
and by multiplying that with mask we'll have argmax([0, 0, 0, 0, 0, 0]) -> 0

**Comment by takuseno** [comment]
Thanks for the explanation! Now, I agree with your point. It's fixed in this latest commit: https://github.com/takuseno/d3rlpy/commit/ee4d1e0726f61fbba99e8064b2baf17528ddb016 .

Thank you for reporting this!
