### ISSUE TITLE
Question Which data to be used for FQE compared to the algorithm to be evaluated by FQE?

### ISSUE THREAD

**Issue by tbskrpmnns** [takuseno/d3rlpy#226]
Hey,

I have an offline-rl problem with no environment available but only a mdp dataset. I am wondering which data to be used for off-policy evaluation using (discrete) fitted q evaluation (fqe) compared to my conservative q-learning (cql) agent training. 

I thought of different strategies:
(1) The naive strategy for me seems to be to **split the dataset D into D_train & D_eval and use both for cql and fqe**.
(2) Since I want to use fqe, using episodes for evaluation for my cql agent seems useless, thereby I can **split the dataset D into D_train_cql, D_train_fqe and D_eval_fqe**. 
(3) Split the dataset D into D_train & D_eval and use **D_train for both cql and fqe**. 

As of now, strategy (2) seems to be reasonable, but that is not more than a best guess. 

Can somebody please help me with that issue?

Thanks in advance!

**Comment by takuseno** [comment]
You don't have to split the dataset explicitly. The purpose of FQE is to estimate the expected return with the trained policy by fitting Q-function in on-policy manner.

**Comment by tbskrpmnns** [comment]
Thanks for your response and the explanation of FQE, which is now much more clear for me.

So, my steps would be as follows:

1. Split the dataset into two (and not as I interpret your answer into three) parts – one for fitting the CQL agent and the FQE agent and one part for calculation of evaluation metrics using the FQE agent wrapping my CQL agent.
2. Fit the CQL agent on data-part 1 without any evaluation_episodes as I use FQE to calculate evaluation metrics
3. Fit the FQE agent using the CQL agent under the hood on data-part 1 and use data-part 2 for FQE as evaluation_episodes.

**Comment by tbskrpmnns** [comment]
Thanks for your response and the explanation of FQE!
