### ISSUE TITLE
Error when saving the trained model as onnx file 

### ISSUE THREAD

**Issue by lk1983823** [takuseno/d3rlpy#228]
Torch version:  '1.11.0+cu113'
D3rlpy version: 0.90
I follow the tutorials of save and load. When I try to save a trained dqn policy into a onnx format. It has an error like this.

dqn.save_policy('policy.onnx', as_onnx=True)

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [28], in <cell line: 13>()
     10 dqn.save_policy('policy.pt')
     12 # save the greedy-policy as ONNX
---> 13 dqn.save_policy('policy.onnx', as_onnx=True)

File ~/.pyenv/versions/anaconda3-5.0.1/envs/mujoco_py/lib/python3.8/site-packages/d3rlpy/algos/base.py:100, in AlgoBase.save_policy(self, fname, as_onnx)
     74 """Save the greedy-policy computational graph as TorchScript or ONNX.
     75 
     76 .. code-block:: python
   (...)
     97 
     98 """
     99 assert self._impl is not None, IMPL_NOT_INITIALIZED_ERROR
--> 100 self._impl.save_policy(fname, as_onnx)

File ~/.pyenv/versions/anaconda3-5.0.1/envs/mujoco_py/lib/python3.8/site-packages/d3rlpy/torch_utility.py:288, in eval_api.<locals>.wrapper(self, *args, **kwargs)
    286 def wrapper(self: Any, *args: Any, **kwargs: Any) -> np.ndarray:
    287     set_eval_mode(self)
--> 288     return f(self, *args, **kwargs)

File ~/.pyenv/versions/anaconda3-5.0.1/envs/mujoco_py/lib/python3.8/site-packages/d3rlpy/algos/torch/base.py:96, in TorchImplBase.save_policy(self, fname, as_onnx)
     92 traced_script = torch.jit.trace(_func, dummy_x, check_trace=False)
     94 if as_onnx:
     95     # currently, PyTorch cannot directly export function as ONNX.
---> 96     torch.onnx.export(
     97         traced_script,
     98         dummy_x,
     99         fname,
    100         export_params=True,
    101         opset_version=11,
    102         input_names=["input_0"],
    103         output_names=["output_0"],
    104         example_outputs=traced_script(dummy_x),
    105     )
    106 else:
    107     traced_script.save(fname)

TypeError: export() got an unexpected keyword argument 'example_outputs'
```
Thanks!

**Comment by takuseno** [comment]
@lk1983823  Thanks for the issue. The version you're using is way behind the latest version. Please update d3rlpy by:
```
$ pip install -U d3rlpy
```

**Comment by lk1983823** [comment]
> @lk1983823 Thanks for the issue. The version you're using is way behind the latest version. Please update d3rlpy by:
> 
> ```
> $ pip install -U d3rlpy
> ```

Thank you. But when I upgrade d3rlpy and from d3rlpy.algos import DiscreteCQL, it shows:
`ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/lksgcc/.pyenv/versions/anaconda3-5.0.1/envs/mujoco_py/lib/python3.8/site-packages/d3rlpy/dataset.cpython-38-x86_64-linux-gnu.so)`
My ubuntu is 16.04, and the GLIBC version is 2.23.

**Comment by takuseno** [comment]
In that case, you should install from source. Please check the document: https://d3rlpy.readthedocs.io/en/v1.1.1/installation.html#install-from-source

**Comment by lk1983823** [comment]
> In that case, you should install from source. Please check the document: https://d3rlpy.readthedocs.io/en/v1.1.1/installation.html#install-from-source

Thanks, I can run d3rlpy 1.1.1. and save the onnx file successfully !
