### ISSUE TITLE
[BUG] MDPDataset auto flatten zero array

### ISSUE THREAD

**Issue by anhduong89** [takuseno/d3rlpy#236]
Hi guys,

I have the code

dataset = MDPDataset(observations=np.zeros((2,3)),
           actions=np.zeros((2,3)),
           terminals=np.zeros(2),
           rewards=np.zeros(2))

then dataset.actions will output:
array([0, 0, 0, 0, 0, 0], dtype=int32)

I expect output should be:
array([[0., 0., 0.],
       [0., 0., 0.]])

Could anyone explain to me this problem?

Thank guys for reading

**Comment by takuseno** [comment]
@anhduong89 Thanks for reporting this. This is because actions with all integer numbers are automatically detected as discrete action. You can explicitly set `discrete_action=False` to solve this.
```
dataset = MDPDataset(
    observations=np.zeros((2,3)),
    actions=np.zeros((2,3)),
    terminals=np.zeros(2),
    rewards=np.zeros(2),
    discrete_action=False,
)
```

**Comment by takuseno** [comment]
Please feel free to reopen this if there are any further discussions.
