### ISSUE TITLE
[BUG] setup FQE in the tutorial

### ISSUE THREAD

**Issue by 8JasonStatham8** [takuseno/d3rlpy#237]
At the Offline Policy Selection in the turtorial : https://d3rlpy.readthedocs.io/en/v1.1.1/tutorials/offline_policy_selection.html
Does 
fqe = d3rlpy.ope.DiscreteFQE()
should be 
fqe = d3rlpy.ope.DiscreteFQE(algo=dqn)

**Comment by takuseno** [comment]
@8JasonStatham8 Thanks for reporting this! I've just fixed it in the latest commit: https://github.com/takuseno/d3rlpy/commit/4c2691f6f1219a182b50849180ea285504f7d352
