### ISSUE TITLE
Data collection for offline RL,

### ISSUE THREAD

**Issue by ajam74001** [takuseno/d3rlpy#238]
Hi dear @takuseno. I am facing an issue while collecting data from cartpole environment, using the provided code in the documentation. The code is from the documentation, "data collection from the random policy" section. The Error is also attached.
I will appreciate any guidance. Many thanks.

```
import gym 
env = gym.make("CartPole-v0")
import d3rlpy

# setup algorithm
random_policy = d3rlpy.algos.DiscreteRandomPolicy()

# prepare experience replay buffer
buffer = d3rlpy.online.buffers.ReplayBuffer(maxlen=100000, env=env)

# start data collection
random_policy.collect(env, buffer, n_steps=100000)

# export as MDPDataset
dataset = buffer.to_mdp_dataset()
```

![image](https://user-images.githubusercontent.com/47214448/202707291-7aadfbfb-7436-4b41-9a99-fef5e45b8884.png)

**Comment by takuseno** [comment]
@ajam74001 Thanks for reporting this issue. It seems that this is because of recent changes in `gym` side. You can downgrade it to `gym==0.17.2` to dismiss this error.

**Comment by ajam74001** [comment]
oh, thank you very much. yeah, you are right. it was about the gym version. I am using a custom environment from [here](https://github.com/eleurent/highway-env) which requires me to use upgraded version of gym. I would like to use your library to collect data (for a offline RL algorithm) from this custom dataset. However, due to the mismatch gym versions, I am stuck. I was wondering if you have any suggestions for me?

Many many thanks,

**Comment by N0Dr4m4L4m4** [comment]
In my case it helped to change these sections with `observation = env.reset()[0]` instead of `observation = env.reset()`. there may be some other files where you need to change that. Like in scorer.py `observation = env.reset()[0]`. Dont know if that helps in your case. Just a hint :)

**Comment by ajam74001** [comment]
> In my case it helped to change these sections with `observation = env.reset()[0]` instead of `observation = env.reset()`. there may be some other files where you need to change that. Like in scorer.py `observation = env.reset()[0]`. Dont know if that helps in your case. Just a hint :)

many thanks for your reply, yeah I could solve it the same way. but I forgot to mention it here. 

Thanks again!

**Comment by takuseno** [comment]
Let me close this issue since the latest version should not have this issue anymore.
