### ISSUE TITLE
[BUG] AWAC example cannot be executed

### ISSUE THREAD

**Issue by VectorSL** [takuseno/d3rlpy#240]
:warning:
- Please don't post bug reports without a minimal example codes. Otherwise, it will take really long to solve the issue.
- Please be polite in discussion. This is an open-sourced project by voluntary contributors.

**Describe the bug**
hi, there is no function named `get_pybullet` in datasets.py, so how to run awac example.
I will appreciate any suggestions. Thanks a lot.
![image](https://user-images.githubusercontent.com/16863563/203201946-ca84167f-beeb-40e3-8dd4-ec800aa50e2a.png)

**To Reproduce**

`pip install d3rlpy`
d3rlpy Version: 1.1.1
`git clone https://github.com/takuseno/d3rlpy.git`
`pip install git+https://github.com/takuseno/d4rl-pybullet`

`cd d3rlpy/examples/finetuning && python train_awac.py`

**Expected behavior**

**Additional context**

**Comment by takuseno** [comment]
@VectorSL Sorry for the inconvenience. Currently, the example is obsolete. Please check these scripts instead.
https://github.com/takuseno/d3rlpy/tree/master/reproductions/finetuning

**Comment by VectorSL** [comment]
ok, got it. thanks!
