### ISSUE TITLE
TransitionMiniBatch object is NOT writable

### ISSUE THREAD

**Issue by XiudingCai** [takuseno/d3rlpy#242]
For validating an idea, I want to modify rewards in a TransitionMiniBatch dynamically. However, it threw an exception TransitionMiniBatch object is NOT writable. I checked the source code, and found that TransitionMiniBatch was implemented by C. I wonder there is a method to modify TransitionMiniBatch object. Thanks!

**Comment by takuseno** [comment]
@XiudingCai Currently, it's difficult to overwrite the contents in `TransitionMiniBatch`. I'm currently working on the next major update in [nightly](https://github.com/takuseno/d3rlpy/tree/nightly) branch. In this version, you can easily modify the values in the batch. Please stay tuned for the update.

**Comment by takuseno** [comment]
With the latest d3rlpy package, this should be fairly easy since it's fully written in Python.
