### ISSUE TITLE
[REQUEST] ReplayBuffer from MDP Dataset code example

### ISSUE THREAD

**Issue by jamartinh** [takuseno/d3rlpy#25]
```
def ReplayBuffer_from_dataset(dataset,maxlen=0):
    class FakeGym:
        observation_space = gym.spaces.Box(low=0, high=1,shape=dataset.get_observation_shape())
        action_space = gym.spaces.Box(low=0, high=1,shape=(dataset.get_action_size(),))
        action_space.n = dataset.get_action_size()

    
    maxlen = max(maxlen,dataset.rewards.shape[0])
    buffer = ReplayBuffer(maxlen=maxlen, env = FakeGym(), episodes=dataset.episodes)
    return buffer
```

**Comment by takuseno** [comment]
@jamartinh Hello, `ReplayBuffer` already supports initializing with a list of `Episode` objects.
https://d3rlpy.readthedocs.io/en/v0.51/references/generated/d3rlpy.online.buffers.ReplayBuffer.html#d3rlpy.online.buffers.ReplayBuffer

```
buffer = ReplayBuffer(maxlen=1000000, env=env, episodes=dataset.episodes)
```

**Comment by jamartinh** [comment]
@takuseno Yes, exactly, the only thing is the requirement of a gym env which I see unnecessary, I see MDPDataset as a formalization of an MDP per se so there should be no need to associate it with a specific environment to work with it.

The same could be applied to a replay buffer, which in essence should be a kind of MDP as well, both share the Transitions data structure.

**Comment by takuseno** [comment]
I see. So, the point is that we can instantiate replay buffer without the environment information when the dataset is given. Maybe, we can make `env` optional when the dataset is given.

**Comment by jamartinh** [comment]
Yes that will be very useful!
