### ISSUE TITLE
[QUESTION] Raised value passed to math.log

### ISSUE THREAD

**Issue by weaseve** [takuseno/d3rlpy#250]
https://github.com/takuseno/d3rlpy/blob/2cdb396ced6059b92a853f4fb2cd2aef046bb599/d3rlpy/algos/torch/cql_impl.py#L191

ln(a^b) = b * ln(a)

```python
random_log_probs = self._action_size * math.log(0.5)
```

Why was the above code not used? I think this way is better.

**Comment by takuseno** [comment]
The original code was based on CQL author's implementation. Since those are mathematically equivalent and not making significant accuracy issues in this case, I won't change it for now.
