### ISSUE TITLE
NameNotFound: Environment BreakoutNoFrameskip doesn't exist

### ISSUE THREAD

**Issue by Zebin-Li** [takuseno/d3rlpy#253]
Hello,

I am running the example code on the welcome page of Github for Atari 2600 and Online Training. Both of the two pieces of code raise the error that the environment cannot be found. Please see below.

For Atari 2600, I just copy the code and paste in PyCharm on Windows 11.

```
import d3rlpy
from sklearn.model_selection import train_test_split

# prepare dataset
dataset, env = d3rlpy.datasets.get_atari('breakout-expert-v0')

# split dataset
train_episodes, test_episodes = train_test_split(dataset, test_size=0.1)

# prepare algorithm
cql = d3rlpy.algos.DiscreteCQL(
    n_frames=4,
    q_func_factory='qr',
    scaler='pixel',
    use_gpu=True,
)

# start training
cql.fit(
    train_episodes,
    eval_episodes=test_episodes,
    n_epochs=100,
    scorers={
        'environment': d3rlpy.metrics.evaluate_on_environment(env),
        'td_error': d3rlpy.metrics.td_error_scorer,
    },
)
```
And it says 
![image](https://user-images.githubusercontent.com/52910998/208776121-78c4d0c2-5358-46c4-be21-1262b659c700.png)

Same for Online Training, I just copy and paste the code to PyCharm on Windows 11.
```
import d3rlpy
import gym

# prepare environment
env = gym.make('HopperBulletEnv-v0')
eval_env = gym.make('HopperBulletEnv-v0')

# prepare algorithm
sac = d3rlpy.algos.SAC(use_gpu=True)

# prepare replay buffer
buffer = d3rlpy.online.buffers.ReplayBuffer(maxlen=1000000, env=env)

# start training
sac.fit_online(env, buffer, n_steps=1000000, eval_env=eval_env)
```
And it says
![image](https://user-images.githubusercontent.com/52910998/208776278-dfc5354c-e0b6-488b-bf7e-7189f2cd4068.png)

Thank you!

**Comment by takuseno** [comment]
Sorry for the inconvenience. This is due to `gym` package compatibility issue. You can make it work by downgrading `gym` (e.g. `gym==0.17.2`).

**Comment by takuseno** [comment]
For `BulletEnv`, you can use MuJoCo instead since it's open-sourced now.

**Comment by Zebin-Li** [comment]
@takuseno Thank you for your help!
 I am trying to install MuJoCo on my PC (Window 11) using PyCharm and it raised this problem as show below. I am a beginner so could you help me with it? I tried some methods searched on Google but have not figure it out, thank you very much!
![image](https://user-images.githubusercontent.com/52910998/209601576-e2f6e59a-f9ed-4596-8e73-6ae4114a8552.png)

**Comment by takuseno** [comment]
I believe that this is something you need to ask MuJoCo people. But here is the quick note to install MuJoCo. [Here](https://github.com/deepmind/mujoco/releases?page=2) is the release page of MuJoCo simulator. And, download windows  release `mujoco210-windows-x86_64.zip` and move the binary to `\Users\lizeb\.mujoco\mujoco210\bin`. Finally, you need to add the path to `PATH` as the error message suggests. Note that I'm not a Windows user. So I couldn't test this process on my end.

**Comment by takuseno** [comment]
Feel free to reopen this if there is any further discussion.
