### ISSUE TITLE
[REQUEST] MDPDataset supports reward-to-go

### ISSUE THREAD

**Issue by GilgameshD** [takuseno/d3rlpy#254]
**Is your feature request related to a problem? Please describe.**
I am trying to implement a Decision Transformer model under d3rlpy, but find that it is hard to get RTG from MDPDataset. Any plan to support it?

**Describe the solution you'd like**
have Transition.rtg

**Additional context**
None

**Comment by takuseno** [comment]
@GilgameshD Hi, thanks for the issue. I'm actually working on this in `nightly` branch: https://github.com/takuseno/d3rlpy/blob/ea270a4ad1bc5e721db75c80ea643f2f0384305b/d3rlpy/dataset/components.py#L51 . Please stay tuned for the update.

**Comment by GilgameshD** [comment]
that helps a lot!
