### ISSUE TITLE
[BUG] StandardScaler crashes when we reload and evaluate TD3PlusBC by every episode. 

### ISSUE THREAD

**Issue by link-zju** [takuseno/d3rlpy#258]
```
class StandardScaler(Scaler):
    TYPE = "standard"
    _mean: Optional[np.ndarray]
    _std: Optional[np.ndarray]
    _eps: float

    def __init__(
        self,
        dataset: Optional[MDPDataset] = None,
        mean: Optional[np.ndarray] = None,
        std: Optional[np.ndarray] = None,
        eps: float = 1e-3,
    ):
        self._mean = None
        self._std = None
        self._eps = eps
        if dataset:
            transitions = []
            for episode in dataset.episodes:
                transitions += episode.transitions
            self.fit(transitions)
        elif mean is not None and std is not None:
            self._mean = np.asarray(mean)
            self._std = np.asarray(std)
```
The StandardScaler works well when we train the DRL models using the whole MDPdataset. 
However, if we reload the model and try to print the model's prediction by every episode in the following way. 
```
for episode in dataset:
    actions = model.predict(episode.observations)
```
It goes wrong since **both the mean and std are None**. 
The reason is that the StandardScaler is correctly initialized when training the model by ```model.fit()```, yet it lacks a proper initialization if we reload and evaluate the models.

**Comment by takuseno** [comment]
Hi @link-zju , please check this documentation.
https://d3rlpy.readthedocs.io/en/v1.1.1/references/save_and_load.html#from-json

**Comment by link-zju** [comment]
Thank you so much for the quick reply!
Great! I always choose the ```model.build_with_env(env)``` and do not find both mean and std are saved in JSON.

**Comment by link-zju** [comment]
Done
