### ISSUE TITLE
[REQUEST] action range

### ISSUE THREAD

**Issue by RafieeAshkan** [takuseno/d3rlpy#26]
Hi 
I was running CQL algorithm and I believe the action values sent to env in `fit_online` and also stored in replay buffer are scaled `[-1,1]`.  Is my understanding correct and shouldn't the action be scaled back to env action range prior to env.ste(action) step?

Also, if this is the case, do we need to scale the actions before building `MDPdataset` for the offline `fit`?

Many thanks

**Comment by takuseno** [comment]
@RafieeAshkan Hello, thanks for asking the question. Actually, across d3rlpy, the continuous action is assumed to be already scaled before passing to d3rlpy modules, which means that scaling action must be done in the environment or dataset side. So, I'm planning support the action scaler in the future release.

Thanks!

**Comment by RafieeAshkan** [comment]
@takuseno Many thanks for clarification. That is fine, I guess I can easily add a scaling function to `Algobase` class to resclae action before sending to `env.step`. How about observation, does that need to be in [-1,1] scale as well, or it can be in any range?

**Comment by takuseno** [comment]
For the observation, d3rlpy already supports `d3rlpy.preprocessing.Scaler` classes. Currectly, there are three scalers.
- `pixel`: divide observation by 255
- `min_max`: normalize observation in range of [0.0, 1.0]
- `standard`: standardize observation

If you want to use this scaler, you just pass this to arguments as follows.
```
from d3rlpy.algos import DQN

dqn = DQN(scaler='pixel')
```

**Comment by jamartinh** [comment]
@RafieeAshkan this has been solved independently of the library some time ago with the introduction of gym wrappers.

Study gym wrappers and you will find many many interesting things:


import numpy as np

import gym
from gym import spaces

```

class RescaleAction(gym.ActionWrapper):
    r"""Rescales the continuous action space of the environment to a range [a,b].
    Example::
        >>> RescaleAction(env, a, b).action_space == Box(a,b)
        True
    """
    def __init__(self, env, a, b):
        assert isinstance(env.action_space, spaces.Box), (
            "expected Box action space, got {}".format(type(env.action_space)))
        assert np.less_equal(a, b).all(), (a, b)
        super(RescaleAction, self).__init__(env)
        self.a = np.zeros(env.action_space.shape, dtype=env.action_space.dtype) + a
        self.b = np.zeros(env.action_space.shape, dtype=env.action_space.dtype) + b
        self.action_space = spaces.Box(low=a, high=b, shape=env.action_space.shape, dtype=env.action_space.dtype)

    def action(self, action):
        assert np.all(np.greater_equal(action, self.a)), (action, self.a)
        assert np.all(np.less_equal(action, self.b)), (action, self.b)
        low = self.env.action_space.low
        high = self.env.action_space.high
        action = low + (high - low)*((action - self.a)/(self.b - self.a))
        action = np.clip(action, low, high)
        return action
```

**Comment by RafieeAshkan** [comment]
@jamartinh Thanks for very useful advice

**Comment by jamartinh** [comment]
> For the observation, d3rlpy already supports `d3rlpy.preprocessing.Scaler` classes. Currectly, there are three scalers.
> 
> * `pixel`: divide observation by 255
> * `min_max`: normalize observation in range of [0.0, 1.0]
> * `standard`: standardize observation
> 
> If you want to use this scaler, you just pass this to arguments as follows.
> 
> ```
> from d3rlpy.algos import DQN
> 
> dqn = DQN(scaler='pixel')
> ```

It could be also possible to include int the signature of fit and fit_online two callables:

`fit(..., obs_fn=lambda x: x, act_fn=lambda x: x)`



So that:
In the iterations over env the code can look like :

```

        # apply obs_fn
        observation = obs_fn(observation)

        # sample exploration action
        if explorer:
            action = explorer.sample(algo, observation, step)
        else:
            action = algo.sample_action([observation])[0]
        # apply act_fn
        action = act_fn(action)

```

**Comment by takuseno** [comment]
@RafieeAshkan @jamartinh Hello, in the last commit, I've implemented `action_scaler` that preprocesses and postprocesses actions. All you need to use this, you just pass `min_max` to `action_scaler` argument.

```
from d3rlpy.algos import CQL

cql = CQL(action_scaler='min_max')

# compute scaling parameters from dataset
cql.fit(episodes)
```

This `action_scaler` works with both online and offline training.

**Comment by takuseno** [comment]
Let me close this issue since it's solved.

**Comment by RafieeAshkan** [comment]
@takuseno many thanks for the support
