### ISSUE TITLE
[BUG] AssertionError: self._impl is not None

### ISSUE THREAD

**Issue by pstansell** [takuseno/d3rlpy#27]
**Describe the bug**

Thank you so much for sharing your code.  I've just started exploring it and noticed an assertion error when following your example here https://d3rlpy.readthedocs.io/en/latest/getting_started.html

**To Reproduce**

Executing the following lines from https://d3rlpy.readthedocs.io/en/latest/getting_started.html
```python
from d3rlpy.datasets import get_cartpole
dataset, env = get_cartpole()

from sklearn.model_selection import train_test_split
train_episodes, test_episodes = train_test_split(dataset, test_size=0.2)

from d3rlpy.algos import DQN
dqn = DQN(use_gpu=False)

from d3rlpy.metrics.scorer import td_error_scorer
from d3rlpy.metrics.scorer import average_value_estimation_scorer
td_error = td_error_scorer(dqn, test_episodes)
```
gives this error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/d3rlpy/lib/python3.9/site-packages/d3rlpy/metrics/scorer.py", line 89, in td_error_scorer
    values = algo.predict_value(batch.observations, batch.actions)
  File "/home/user/miniconda3/envs/d3rlpy/lib/python3.9/site-packages/d3rlpy/algos/base.py", line 157, in predict_value
    assert self._impl is not None
AssertionError
```
Then, continuing with these lines from https://d3rlpy.readthedocs.io/en/latest/getting_started.html
```python
from d3rlpy.metrics.scorer import evaluate_on_environment
evaluate_scorer = evaluate_on_environment(env)
rewards = evaluate_scorer(dqn)
```
gives this error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/d3rlpy/lib/python3.9/site-packages/d3rlpy/metrics/scorer.py", line 466, in scorer
    action = algo.predict([observation])[0]
  File "/home/user/miniconda3/envs/d3rlpy/lib/python3.9/site-packages/d3rlpy/algos/base.py", line 115, in predict
    assert self._impl is not None
AssertionError
```

**Expected behavior**

No errors.

**Additional context**

I'm using the following
```
Python            3.9.1 
d3rlpy            0.51
gym               0.18.0
numpy             1.19.5
scikit-learn      0.24.0
scipy             1.6.0
torch             1.7.1
```

**Comment by pstansell** [comment]
Continuing on with the example from https://d3rlpy.readthedocs.io/en/latest/getting_started.html, after training successfully, the following lines:
```python
dqn.save_model('dqn.pt')
dqn2 = DQN()
dqn2.load_model('dqn.pt')
```
give this assertion error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/d3rlpy/lib/python3.9/site-packages/d3rlpy/base.py", line 289, in load_model
    assert self._impl is not None
AssertionError
```

**Comment by takuseno** [comment]
@pstansell Thanks for reporting this. Actually, this is expected behavior. The missing thing is the right tutorial. I'll fix the page. Sorry for the inconvenience.

**Comment by takuseno** [comment]
The latest documentation is updated.
https://d3rlpy.readthedocs.io/en/latest/getting_started.html

I'd like you to check it. If it's not updated, your browser probably stores a cache of this page. In that case, please reload the page.

**Comment by pstansell** [comment]
Thanks for addressing this so quickly, however, you have misspelt `dataset` in this line
```python
dqn.build_with_dataset(dataest)
```

**Comment by takuseno** [comment]
@pstansell Thanks for pointing typo! I've fixed this.

**Comment by pstansell** [comment]
Brilliant, thanks!

**Comment by DanielDowns** [comment]
Can you update the Save/Load page to add the explanation about why the build_with_dataset() call is needed? I didn't realize it was required until I checked here.

https://d3rlpy.readthedocs.io/en/v0.51/references/save_and_load.html

**Comment by pstansell** [comment]
Hello @DanielDowns, I think the code now prints this message when the assertion error is triggered:

   The neural network parameters are not
   initialized. Pleaes call build_with_dataset,
   build_with_env, or directly call fit or
   fit_online method.

@takuseno, I just noticed there is a typo in "Pleaes".
