### ISSUE TITLE
[BUG] Error in fitted q evaluation example

### ISSUE THREAD

**Issue by zxp567** [takuseno/d3rlpy#273]
I am following the example on this page "Offline Policy Selection": https://d3rlpy.readthedocs.io/en/v1.1.1/tutorials/offline_policy_selection.html
The 1st part "Prepare trained policies" runs fine.
The 2nd part “Train FQE with the trained policies“ produces an error that I don't know how to resolve. Could you help?
```
import d3rlpy

# setup the same dataset used in policy training
dataset, _ = d3rlpy.datasets.get_dataset("cartpole-replay")

# load pretrained policy
dqn = d3rlpy.algos.DQN()
dqn.build_with_dataset(dataset)
dqn.load_model("d3rlpy_logs/DQN_20230324225206/model_100000.pt")

# setup FQE algorithm
fqe = d3rlpy.ope.DiscreteFQE()

# start FQE training
fqe.fit(
   dataset,
   eval_episodes=dataset.episodes,
   n_steps=10000,
   n_steps_per_epoch=1000,
   scorers={
       "init_value": d3rlpy.metrics.initial_state_value_estimation_scorer,
       "soft_opc": d3rlpy.metrics.soft_opc_scorer(180),  # set 180 for success return threshold here
   },
)
```
Error:
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[3], line 15
     12 fqe = d3rlpy.ope.DiscreteFQE()
     14 # start FQE training
---> 15 fqe.fit(
     16    dataset,
     17    eval_episodes=dataset.episodes,
     18    n_steps=10000,
     19    n_steps_per_epoch=1000,
     20    scorers={
     21        "init_value": d3rlpy.metrics.initial_state_value_estimation_scorer,
     22        "soft_opc": d3rlpy.metrics.soft_opc_scorer(180),  # set 180 for success return threshold here
     23    },
     24 )

File C:\ProgramData\Anaconda3\envs\d3rl\lib\site-packages\d3rlpy\base.py:406, in LearnableBase.fit(self, dataset, n_epochs, n_steps, n_steps_per_epoch, save_metrics, experiment_name, with_timestamp, logdir, verbose, show_progress, tensorboard_dir, eval_episodes, save_interval, scorers, shuffle, callback)
    349 def fit(
    350     self,
    351     dataset: Union[List[Episode], List[Transition], MDPDataset],
   (...)
    368     callback: Optional[Callable[["LearnableBase", int, int], None]] = None,
    369 ) -> List[Tuple[int, Dict[str, float]]]:
    370     """Trains with the given dataset.
    371 
    372     .. code-block:: python
   (...)
    404 
    405     """
--> 406     results = list(
    407         self.fitter(
    408             dataset,
    409             n_epochs,
    410             n_steps,
    411             n_steps_per_epoch,
    412             save_metrics,
    413             experiment_name,
    414             with_timestamp,
    415             logdir,
    416             verbose,
    417             show_progress,
    418             tensorboard_dir,
    419             eval_episodes,
    420             save_interval,
    421             scorers,
    422             shuffle,
    423             callback,
    424         )
    425     )
    426     return results

File C:\ProgramData\Anaconda3\envs\d3rl\lib\site-packages\d3rlpy\base.py:637, in LearnableBase.fitter(self, dataset, n_epochs, n_steps, n_steps_per_epoch, save_metrics, experiment_name, with_timestamp, logdir, verbose, show_progress, tensorboard_dir, eval_episodes, save_interval, scorers, shuffle, callback)
    635 # update parameters
    636 with logger.measure_time("algorithm_update"):
--> 637     loss = self.update(batch)
    639 # record metrics
    640 for name, val in loss.items():

File C:\ProgramData\Anaconda3\envs\d3rl\lib\site-packages\d3rlpy\base.py:748, in LearnableBase.update(self, batch)
    738 def update(self, batch: TransitionMiniBatch) -> Dict[str, float]:
    739     """Update parameters with mini-batch of data.
    740 
    741     Args:
   (...)
    746 
    747     """
--> 748     loss = self._update(batch)
    749     self._grad_step += 1
    750     return loss

File C:\ProgramData\Anaconda3\envs\d3rl\lib\site-packages\d3rlpy\ope\fqe.py:96, in _FQEBase._update(self, batch)
     95 def _update(self, batch: TransitionMiniBatch) -> Dict[str, float]:
---> 96     assert self._algo is not None, ALGO_NOT_GIVEN_ERROR
     97     assert self._impl is not None, IMPL_NOT_INITIALIZED_ERROR
     98     next_actions = self._algo.predict(batch.next_observations)

**AssertionError: The algorithm to evaluate is not given. Please give the trained algorithm to the argument.**

**Comment by takuseno** [comment]
@zxp567 Hi, thanks for the issue. Can you given `dqn` to `fqe`?
```
fqe = d3rlpy.ope.DiscreteFQE(algo=dqn)
```

**Comment by zxp567** [comment]
> @zxp567 Hi, thanks for the issue. Can you given `dqn` to `fqe`?
> 
> ```
> fqe = d3rlpy.ope.DiscreteFQE(algo=dqn)
> ```

Thanks a lot! This works!

**Comment by takuseno** [comment]
Glad it worked now. Sorry about the documentation. In case, you might also check the latest version of documentation that fixes this part.
https://d3rlpy.readthedocs.io/en/latest/tutorials/offline_policy_selection.html
