### ISSUE TITLE
[REQUEST] How can I use Transformer to be a Encoder?

### ISSUE THREAD

**Issue by 8JasonStatham8** [takuseno/d3rlpy#274]
I want to use Transformer to be an encoder , but I find it's not easy to use it straightly.

So do you have some advice about How should I develop it.

**Comment by 8JasonStatham8** [comment]
And do you have a document to describe the d3rlpy, I hope to learn some details to enhance my coding ability. Thanks!!

**Comment by takuseno** [comment]
Currently, Transformer architecture is not supported yet, however, Decision Transformer is under development in [nightly](https://github.com/takuseno/d3rlpy/blob/nightly/d3rlpy/algos/transformer/decision_transformer.py) branch.

**Comment by 8JasonStatham8** [comment]
Thanks for your reply. Do you have more documents about  d3rlpy to help understant this package? some design details about d3rlpy.

**Comment by takuseno** [comment]
Decision Transformer is finally available :smile: 
https://github.com/takuseno/d3rlpy/blob/master/reproductions/offline/decision_transformer.py
