### ISSUE TITLE
[REQUEST] Adding Cal-QL

### ISSUE THREAD

**Issue by zxp567** [takuseno/d3rlpy#276]
**Is your feature request related to a problem? Please describe.**
It has been observed in research that the CQL (conservative q-learning) may be too conservative and often results in a significantly low q values than a typical policy when the online fine-tuning begins.

**Describe the solution you'd like**
There is a recent paper “Cal-QL: Calibrated Offline RL Pre-Training for Efficient Online Fine-Tuning” that seems to be addressing this issue.
https://arxiv.org/abs/2303.05479
It would be great if that could be incorporated into this library.
![image](https://user-images.githubusercontent.com/26178407/231342304-eb06e508-9628-4b7d-bbc2-02bf8c0ec6c4.png)

**Additional context**
There seems to be no open sourced code for Cal-QL yet by the authors. However, there are some python snippet in the Appendix A of the paper.

**Comment by zxp567** [comment]
The Cal-QL code has been released by the author: https://github.com/nakamotoo/Cal-QL/. 
However, it was implemented in JAXCQL and seems more robotics oriented, while I would just need something simpler that work with an offline MDPDataset like this d3rlpy library offers, and I am looking for discrete actions only as well. 

Would you have some capacity to include the calculation of reference policy Q-values and the logic of cal-ql could be added to this repo's discreteCQL algorithm? 

It seems we only need to revise "_compute_conservative_loss" in "algos/torch/cql_impl.py" by:
1) adding the "return_to_go" similar to the calculation as in "https://github.com/nakamotoo/Cal-QL/blob/main/JaxCQL/replay_buffer.py" as another input;
2) and including the lower bound logic similar to the logic as in "https://github.com/nakamotoo/Cal-QL/blob/main/JaxCQL/conservative_sac.py" 

Right? Would be helpful if you could add this into this repo as Cal-QL seems to work significantly better than CQL once the online fine-tuning begins.

Thank you very much.

**Comment by takuseno** [comment]
@zxp567 Hi, thank you for your request. I'm sure this can be supported in d3rlpy. I'm currently working on the next major update release in [nightly](https://github.com/takuseno/d3rlpy/tree/nightly) branch. I might support Cal-CQL there.

**Comment by takuseno** [comment]
`CalQL` has been implemented in the latest version. Let me close this issue.
