### ISSUE TITLE
[DOCS] docstrings in code but not on readthedocs

### ISSUE THREAD

**Issue by pstansell** [takuseno/d3rlpy#28]
I can see docstrings, with nice mathematical descriptions of the algorithms, in files like this one

- https://github.com/takuseno/d3rlpy/blob/master/d3rlpy/algos/cql.py

but the same documentation does not seem to be present on readthedocs

- https://d3rlpy.readthedocs.io/en/latest/index.html

Is this a problem with the processing of the documentation?

**Comment by pstansell** [comment]
The documentation is present on readthedocs for `stable`, `v0.51`, etc, for example

- https://d3rlpy.readthedocs.io/en/stable/references/generated/d3rlpy.algos.CQL.html

- https://d3rlpy.readthedocs.io/en/v0.51/references/generated/d3rlpy.algos.CQL.html

but not for `latest` here
- https://d3rlpy.readthedocs.io/en/latest/references/generated/d3rlpy.algos.CQL.html

**Comment by takuseno** [comment]
@pstansell Hello, thanks for checking the documentation. I've fixed the issue now.
https://d3rlpy.readthedocs.io/en/latest/references/algos.html
