### ISSUE TITLE
[REQUEST] Multi dimensional action space

### ISSUE THREAD

**Issue by joshuaspear** [takuseno/d3rlpy#282]
**Is your feature request related to a problem? Please describe.**
I maybe missing something obvious, but is there an easy way to train over a multi dimensional action space for example $[0,1]^2$ or $\mathbb{R}^2$, please? 

**Describe the solution you'd like**
I guess ideally - to pass several action columns in a dataset and generate a q function with a shared encoder and different prediction heads

**Additional context**

**Comment by hccroll** [comment]
I am also having an issue with a multi-dimensional action space in my custom environment. I am trying to migrate from SB3 due to d3rlpy's wider range of offline capabilities. My action space is currently set to be a box of 7 continuous actions, each with specified min_max of 0-1. 

Using the TD3 agent and fit.online() I can get confirmation that 'action_size': 7, but then I only get a single numpy.float32 scalar returned as an action. 

Any help would be appreciated,
Henry

**Comment by takuseno** [comment]
@hccroll Can you make a flattened action space? If they're all `ContinuouxBox`, it should be doable, I imagine.

**Comment by hccroll** [comment]
This was 100% my issue - I accidentally left in an SB3 wrapper that was for some reason only allowing a scaler action to be passed out of my step() function. No idea why this is the case, but the issue has been fixed when I removed the wrapper. 

@joshuaspear now that I read your initial post again I may have misunderstood what you were asking, and if so sorry for hijacking your thread! My multi-dimensional action space is a box with 7 actions, but sounds like you are asking about a matrix of actions?

**Comment by joshuaspear** [comment]
@hccroll I don't think you hijacked :) I've just looked at the definition of the OpenAI Box class and I think mine is also a Box. Specifically, of the form $\{0,1\}^{2}$ so my agent can take the following tuples of actions $\{(0,0),(0,1),(1,0),(1,1)\}$ (please correct me if I have miss understood)!

I'm guessing that's trivial to implement in d3rlpy and I'm missing something really obvious? When I was trying to use the DiscreteCQL model, I was trying to pass a (batch_size*2) dimensional array into the model and it didn't seem to work..

**Comment by hccroll** [comment]
Let me preface by saying I am no computer scientist, but to me this looks like it could be set up a couple of ways. The first is as one discrete action with four possibilities, something like the following:

```
action_space = spaces.Discrete(4)

if action = 0:
    my_action = (0,0)
elif action = 1:
    my_action = (0,1)
...
```

But that is not a very elegant solution, and does not scale well with an increasing matrix size. If you are only dealing with zeros and ones, I think the more elegant action space is [MultiBinary](https://www.gymlibrary.dev/api/spaces/#multibinary). That said, I had never heard of this space prior to your question, so there may not be as much documentation or support from different algorithms. 

`action_space = MultiBinary([0,2])`

Which should return:

`array([0, 1])` or some permutation thereof.

**Comment by joshuaspear** [comment]
@hccroll thank you! I'll have a crack - appreciate you taking the time to explain :)

**Comment by takuseno** [comment]
I think that `MultiBinary` can be translated to a simple discrete action-space. For now, I'm not considering to explicitly support this to keep the implementation as simple as possible. But, thanks for the request!
