### ISSUE TITLE
[QUESTION] How to use MOPO on offline datasets?

### ISSUE THREAD

**Issue by raunakkbanerjee** [takuseno/d3rlpy#288]
Hello @takuseno, I am trying to use `d3rlpy` to train on some offline RL datasets using the `MOPO` algorithm. But I do not know which APIs to use.

I currently have this simple code.
```
import d3rlpy
from d3rlpy.datasets import get_d4rl

task = "halfcheetah-medium-v2"
dataset, env = get_d4rl(task)

algo = d3rlpy.algos.MOPO()
algo.fit(dataset, n_epochs=2, n_steps_per_epoch=2)
```

I get an error `AssertionError: The dynamics to generate transitions is not given. Please give the trained dynamics to the argument`.

Issue (I think) is that, because `MOPO` is model-based, `d3rlpy.algos.MOPO()` takes an argument called `dynamics`.

But how does one create this trained dynamics model? Some sample code would be nice. 
I would appreciate any help you could provide.

**Comment by raunakkbanerjee** [comment]
@takuseno Please could you help me out with this

**Comment by takuseno** [comment]
Sorry for the late response. Please check documentation.
https://d3rlpy.readthedocs.io/en/v1.1.1/references/model_based.html

**Comment by raunakkbanerjee** [comment]
Thank you so much!
