### ISSUE TITLE
[QUESTION] import d3rlpy error

### ISSUE THREAD

**Issue by dengminxiao** [takuseno/d3rlpy#289]
<img width="158" alt="1688462017272" src="https://github.com/takuseno/d3rlpy/assets/138573613/03811fe3-94e5-4acf-957b-a19361927ecd">

get the error:
from .dataset import TransitionMiniBatch
ModuleNotFoundError: No module named 'd3rlpy.dataset'

I install the package use :"pip install d3rlpy" and "conda XXX"(just as the introduction ) but all failed

please tell me why ?

**Comment by takuseno** [comment]
Hi @dengminxiao , thanks for the issue. Can you try installation from source?
https://d3rlpy.readthedocs.io/en/v1.1.1/installation.html#install-from-source

**Comment by dengminxiao** [comment]
> Hi @dengminxiao , thanks for the issue. Can you try installation from source? https://d3rlpy.readthedocs.io/en/v1.1.1/installation.html#install-from-source

I tried ，but get a new error
 from . import h5 as _h5
  File "h5py\h5.pyx", line 1, in init h5py.h5
ImportError: DLL load failed: 。

**Comment by takuseno** [comment]
It's not d3rlpy's issue. But, I guess `pip install -U pip` might fix the problem.

**Comment by takuseno** [comment]
Let me close this issue. Feel free to reopen this if there is any further discussion.
