### ISSUE TITLE
Can FQE evaluation be used for model-based methods (MOPO and COMBO). When I use it this way, bugs appear

### ISSUE THREAD

**Issue by XiudingCai** [takuseno/d3rlpy#291]
Can FQE evaluation be used for model-based methods (MOPO and COMBO). When I use it this way, bugs appear

![Snipaste_2023-07-07_11-52-33](https://github.com/takuseno/d3rlpy/assets/34913517/192d9ece-1c07-4e58-b81e-2bbf8c101fc2)

**Comment by takuseno** [comment]
Can you share the full source code that I can reproduce your issue?

**Comment by XiudingCai** [comment]
> Can you share the full source code that I can reproduce your issue?
The result of the debug below looks like something is not being initialized?
![image](https://github.com/takuseno/d3rlpy/assets/34913517/6089f32d-2554-451a-add8-78db87996ddf)
