### ISSUE TITLE
No module named 'd3rlpy.iterators'

### ISSUE THREAD

**Issue by hn2** [takuseno/d3rlpy#30]
No sure if it is a bug or not, however I get:
No module named 'd3rlpy.iterators'
When trying to run d3rlpy

**Comment by takuseno** [comment]
@hn2 Thank you for reporting this issue! Could you share the entire error messages?

**Comment by hn2** [comment]
Traceback (most recent call last):
  File .../train-offline.py", line 24, in <module>
    from d3rlpy.algos import BCQ, BEAR, AWR, CQL, AWAC
  File ...\site-packages\d3rlpy\algos\__init__.py", line 2, in <module>
    from .base import AlgoBase, DataGenerator
  File ...\site-packages\d3rlpy\algos\base.py", line 8, in <module>
    from ..base import ImplBase, LearnableBase
  File ...\site-packages\d3rlpy\base.py", line 35, in <module>
    from .iterators import RoundIterator
ModuleNotFoundError: No module named 'd3rlpy.iterators'

**Comment by takuseno** [comment]
@hn2 Thanks! I think I resolve this error in the last commit.
https://github.com/takuseno/d3rlpy/commit/32ef0fec3b1f45b0430af2c5fd1834df2d9bbb49

**Comment by hn2** [comment]
This is a fresh installation of d3rlpy

**Comment by takuseno** [comment]
This commit is done a minute ago. Please pull the latest master, and reinstall this. Sorry for the inconvenience.

**Comment by takuseno** [comment]
Since this seems to be resolved, let me close this issue.

**Comment by hn2** [comment]
For some reason I do not get better results using offline algos.

What’s is the best offline algo to try? CQL?

I tried all of them.

Do I need to do hyper parameters tuning?

Am I doing anything else wrong?
