### ISSUE TITLE
[BUG] dataset class changed to ReplayBuffer 

### ISSUE THREAD

**Issue by HateBunnyPlzzz** [takuseno/d3rlpy#300]
**Pre/Post Processing the Data**
Setting up manual action space bounds from the example in Pre/Post Process Tutorials

**To Reproduce**
Following code tells us about the type of dataset variable now:
~~~python
import d3rlpy
import numpy as np


dataset, _ = d3rlpy.datasets.get_dataset("pendulum-random")

# prepare scaler without init
observation_scaler = d3rlpy.preprocessing.StandardObservationScaler()
sac = d3rlpy.algos.SACConfig(observation_scaler=observation_scaler).create()
type(dataset)
~~~
which has now been changed to ``d3rlpy.dataset.replay_buffer.ReplayBuffer``
from the previous ``d3rlpy.dataset.MDPDataset``.

**Expected behavior**
The code after the new major update v2.0.3, expected to run and initialize actions without any error. Error is described below

**Run the following code to reproduce the error message (new code example)**
~~~python
# prepare scaler without initialization
action_scaler = d3rlpy.preprocessing.MinMaxActionScaler()

# set as action scaler
sac = d3rlpy.algos.SACConfig(action_scaler=action_scaler).create()

# setup manually
minimum_action = np.min(dataset.actions, axis=0, keepdims=True)
maximum_action = np.max(dataset.actions, axis=0, keepdims=True)
action_scaler = d3rlpy.preprocessing.MinMaxActionScaler(
    minimum=minimum_action,
    maximum=maximum_action,
)

# set as action scaler
sac = d3rlpy.algos.SACConfig(action_scaler=action_scaler).create()
~~~

**Throws an error**
~~~python
AttributeError                            Traceback (most recent call last)
Cell In [2], line 8
      5 sac = d3rlpy.algos.SACConfig(action_scaler=action_scaler).create()
      7 # setup manually
----> 8 minimum_action = np.min(dataset.actions, axis=0, keepdims=True)
      9 maximum_action = np.max(dataset.actions, axis=0, keepdims=True)
     10 action_scaler = d3rlpy.preprocessing.MinMaxActionScaler(
     11     minimum=minimum_action,
     12     maximum=maximum_action,
     13 )

AttributeError: 'ReplayBuffer' object has no attribute 'actions'
~~~

**Additional Context**

Before the Major update, the get_dataset() method returned a MDPDataset class
~~~python
def get_pendulum(dataset_type: str = "replay") -> Tuple[MDPDataset, gym.Env]:
~~~

After the major update (v2), same method returned a ReplayBuffer class directly
~~~python
def get_pendulum(
    dataset_type: str = "replay",
    transition_picker: Optional[TransitionPickerProtocol] = None,
    trajectory_slicer: Optional[TrajectorySlicerProtocol] = None,
) -> Tuple[ReplayBuffer, gym.Env[np.ndarray, np.ndarray]]:
~~~

**Comment by takuseno** [comment]
@HateBunnyPlzzz Thanks for reporting this! This has been fixed at the latest commit: https://github.com/takuseno/d3rlpy/commit/452a46a39a3f3530f8bbb3de64bfee2fbd1ab0af . In v2 version, `d3rlpy.datasets.get_dataset("pendulum-random")` returns `ReplayBuffer` and there is no interface like `dataset.observations` anymore. I appreciate your help!

**Comment by takuseno** [comment]
The latest patch has been released.
https://github.com/takuseno/d3rlpy/releases/tag/v2.0.4
