### ISSUE TITLE
Issue when setup dataset and environment

### ISSUE THREAD

**Issue by Zebin-Li** [takuseno/d3rlpy#305]
Hi,

When I follow the document to run some example code and for the dataset and environment setup, I got the error as shown below:
`import d3rlpy`
`dataset, env = d3rlpy.datasets.get_dataset("cartpole-random")`
![image](https://github.com/takuseno/d3rlpy/assets/52910998/43d51f17-dd18-4a16-9a68-7dd6a4561d8a)

The d3rlpy version I used is 2.0.4. Thank you for your help!

Best,
Zebin

**Comment by takuseno** [comment]
Please upgrade `gym` package by `pip install -U gym`.

**Comment by Zebin-Li** [comment]
Thank you very much! It works!
