### ISSUE TITLE
[BUG] Tutorial -- Getting Started - Cannot get actions

### ISSUE THREAD

**Issue by fpoltronieri** [takuseno/d3rlpy#307]
Dear maintainers, 

I am very interested in using this library for a offline reinforcement learning project.
I started following the "Getting Started" tutorial available [here](https://d3rlpy.readthedocs.io/en/v2.0.4/tutorials/getting_started.html) that trains a DQN over the CartPole environment.
However, as soon as I try to predict the actions:

```
observation = env.reset()
# return actions based on the greedy-policy
action = dqn.predict([observation])[0]
```

I get the following error:
```
Traceback (most recent call last):
  File "load_cartpole.py", line 11, in <module>
    action = dqn.predict([observation])[0]
  File "/home/filippo/miniforge3/envs/offrl/lib/python3.7/site-packages/d3rlpy/algos/qlearning/base.py", line 258, in predict
    assert check_non_1d_array(x), "Input must have batch dimension."
  File "/home/filippo/miniforge3/envs/offrl/lib/python3.7/site-packages/d3rlpy/dataset/utils.py", line 181, in check_non_1d_array
    return all(v.ndim > 1 for v in array)
  File "/home/filippo/miniforge3/envs/offrl/lib/python3.7/site-packages/d3rlpy/dataset/utils.py", line 181, in <genexpr>
    return all(v.ndim > 1 for v in array)
AttributeError: 'tuple' object has no attribute 'ndim'
```

Can someone help me with that?

Thank you so very much!

**Comment by takuseno** [comment]
@fpoltronieri Thanks for the issue. The documentation seems outdated because of the recent major update. It should work as follows:
```
action = dqn.predict(np.expand_dims(observation, axis=0))[0]
```

**Comment by takuseno** [comment]
Documentation has been fixed at this latest commit: https://github.com/takuseno/d3rlpy/commit/36222ae2ae1d105d9f8719e4466f762f177f579a

**Comment by fpoltronieri** [comment]
@takuseno I commented your last commit with a fix. Now it works for me, can you check and then close the issue?

**Comment by fpoltronieri** [comment]
@takuseno sorry for that, the fix that I should have posted on the commit is the following:
