### ISSUE TITLE
[BUG] Segmentation fault from example

### ISSUE THREAD

**Issue by pstansell** [takuseno/d3rlpy#31]
**Describe the bug**

The simple script below ends with `Segmentation fault (core dumped)`.  The script is a sightly simplified version of the example here
- https://d3rlpy.readthedocs.io/en/latest/getting_started.html

**To Reproduce**

Run the following script

```python
from d3rlpy.datasets import get_cartpole

dataset, env = get_cartpole()

from sklearn.model_selection import train_test_split
train_episodes, test_episodes = train_test_split(dataset, test_size=0.2)

from d3rlpy.algos import DQN
dqn = DQN(use_gpu=False)
dqn.build_with_dataset(dataset)

from d3rlpy.metrics.scorer import average_value_estimation_scorer
dqn.fit(train_episodes,
        eval_episodes=test_episodes,
        n_epochs=1,
        scorers={'value_scale': average_value_estimation_scorer})

quit()
```

If run on the python command-line the fault does not occur until after `quit()` is executed.

I've tested it on machines with and without an NVIDIA GPU.

On a machines with a GPU, no more warning massages are given, however, on a machine without a GPU I also see this message, even though `use_gpu=False` is specified in the script
```
/Home/user/miniconda3/envs/d3rlpy/lib/python3.9/site-packages/torch/autograd/__init__.py:130: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)

```

**Additional context**

I'm using the following
```
Python            3.9.1 
d3rlpy            0.51
gym               0.18.0
numpy             1.19.5
scikit-learn      0.24.0
scipy             1.6.0
torch             1.7.1
```

**Comment by pstansell** [comment]
I don't know if this is helpful or relevant to the above `Segmentation fault`, but I tried the same script as above on another machine running a different linux OS.

The output was the following:
```
augmentation={'params': {'n_mean': 1}, 'augmentations': []}
batch_size=32
bootstrap=False
encoder_factory={'type': 'default', 'params': {'activation': 'relu', 'use_batch_norm': False}}
gamma=0.99
generator=None
learning_rate=6.25e-05
n_critics=1
n_frames=1
n_steps=1
optim_factory={'optim_cls': 'Adam', 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False}
q_func_factory={'type': 'mean', 'params': {}}
scaler=None
share_encoder=False
target_update_interval=8000
use_gpu=None
algorithm=DQN
observation_shape=(4,)
action_size=2
Epoch 0:   0%|                                                   | 0/2501 [00:00<?, ?it/s]
Illegal instruction
```
The OS was:
```
lsb_release -a 
  LSB Version:    core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
  Distributor ID: Neon
  Description:    KDE neon User Edition 5.20
  Release:        20.04
  Codename:       focal
```
with kernel
```
uname -a
   Linux host 5.4.0-59-generic #65-Ubuntu SMP Thu Dec 10 12:01:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
running the following:
```
Python            3.8.5
d3rlpy            0.51
gym               0.18.0
numpy             1.19.5
scikit-learn      0.24.0
scipy             1.6.0
torch             1.7.1
```

By the way, the previous OS used in my first post above was
```
lsb_release -a 
  LSB Version:    :core-4.1-amd64:core-4.1-noarch
  Distributor ID: CentOS
  Description:    CentOS Linux release 7.9.2009 (Core)
  Release:        7.9.2009
  Codename:       Core
```
with kernel
```
uname -a
  Linux host 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by pstansell** [comment]
I'm trying to solve the problem, but I seem to be going backwards, so I'm sorry for inundating you with messages.

I tried installing using conda as you suggest on your installation page (my previous installations used pip).

I'll keep this message short.  Here is how it went
```
conda create --name d3rlpy_test python==3.8
conda activate d3rlpy_test
conda install -c conda-forge d3rlpy

python 
  Python 3.8.0 (default, Nov  6 2019, 21:49:08) 
  [GCC 7.3.0] :: Anaconda, Inc. on linux
  Type "help", "copyright", "credits" or "license" for more information.
  >>> from d3rlpy.datasets import get_cartpole
    Illegal instruction (core dumped)
```

Please let me know if you can see what's wrong, or if you want me to provide any more diagnostic information.

**Comment by pstansell** [comment]
Installing from source works such that running the script above does not give either of th errors above, that is,
- `Segmentation fault (core dumped)`
- `Illegal instruction (core dumped)`

on either of the OSs I tested above.

To be precise, installating via the following produces an installation that works:
```
conda create --name d3rlpy python==3.8
conda activate d3rlpy

git clone git@github.com:takuseno/d3rlpy.git
cd d3rlpy
pip install cython
pip install numpy
pip install -e .
```

**Comment by takuseno** [comment]
@pstansell Thank you for reporting this. I notice that d3rlpy crashes on some machines due to compiled Cython modules. I'm still investigating how to prevent this. But, I actually did not find a way to solve this for now. If you're a Docker user, there is an official docker image where d3rlpy is installed, which you might not have this problem. 
https://hub.docker.com/repository/docker/takuseno/d3rlpy
