### ISSUE TITLE
[BUG]  Error compiling Cython file,   d3rlpy/dataset.pyx:15:0: 'dataset/CTransition.pxd' not found while installing version 1.1.1

### ISSUE THREAD

**Issue by HassamSheikh** [takuseno/d3rlpy#310]
Hi, I am getting the following error while installing the 1.1.1 version. 

 × python setup.py egg_info did not run successfully.
#0 2.839   │ exit code: 1
#0 2.839   ╰─> [42 lines of output]
#0 2.839       /opt/conda/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-og89eeo_/d3rlpy_0c62c62a8ef04fec86d74886797d9670/d3rlpy/dataset.pxd
#0 2.839         tree = Parsing.p_module(s, pxd, full_module_name)
#0 2.839
#0 2.839       Error compiling Cython file:
#0 2.839       ------------------------------------------------------------
#0 2.839       ...
#0 2.839
#0 2.839       from cython cimport view
#0 2.839
#0 2.839       from cython.parallel import prange
#0 2.839
#0 2.839       from dataset cimport CTransition
#0 2.839       ^
#0 2.839       ------------------------------------------------------------
#0 2.839
#0 2.839       d3rlpy/dataset.pyx:15:0: 'dataset.pxd' not found
#0 2.839
#0 2.839       Error compiling Cython file:
#0 2.839       ------------------------------------------------------------
#0 2.839       ...
#0 2.839
#0 2.839       from cython cimport view
#0 2.839
#0 2.839       from cython.parallel import prange
#0 2.839
#0 2.839       from dataset cimport CTransition
#0 2.839       ^
#0 2.839       ------------------------------------------------------------
#0 2.839
#0 2.839       d3rlpy/dataset.pyx:15:0: 'dataset/CTransition.pxd' not found
#0 2.839       Traceback (most recent call last):
#0 2.839         File "<string>", line 2, in <module>
#0 2.839         File "<pip-setuptools-caller>", line 34, in <module>
#0 2.839         File "/tmp/pip-install-og89eeo_/d3rlpy_0c62c62a8ef04fec86d74886797d9670/setup.py", line 23, in <module>
#0 2.839           ext_modules = cythonize([ext],
#0 2.839         File "/opt/conda/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
#0 2.839           cythonize_one(*args)
#0 2.839         File "/opt/conda/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
#0 2.839           raise CompileError(None, pyx_file)
#0 2.839       Cython.Compiler.Errors.CompileError: d3rlpy/dataset.pyx
#0 2.839       Compiling d3rlpy/dataset.pyx because it changed.
#0 2.839       [1/1] Cythonizing d3rlpy/dataset.pyx
#0 2.839       [end of output]

**Comment by takuseno** [comment]
@HassamSheikh Hi, thanks for the issue. Can you tell me how to install the package? This looks very weird.

**Comment by takuseno** [comment]
One possible solution is to downgrade Cython if you're installing the latest Cython. In that case, please try:
```
pip install -U Cython==0.29.28
```

**Comment by HassamSheikh** [comment]
> One possible solution is to downgrade Cython if you're installing the latest Cython. In that case, please try:
> 
> ```
> pip install -U Cython==0.29.28
> ```

It worked. Thank you
