### ISSUE TITLE
Asterix: why index=1 ?

### ISSUE THREAD

**Issue by pop-cultural-reference** [takuseno/d3rlpy#318]
Why is [`index=1` for Asterix](https://github.com/takuseno/d3rlpy/blob/6d8b0d6425eaf64fa0c9c6df6f53af2483b50291/reproductions/offline/discrete_cql.py#L17C34-L17C41) ?

**Comment by takuseno** [comment]
It seems that Google does not upload index=0 datasets for Asterix. That's why we need to shift index here.

**Comment by takuseno** [comment]
Let me close this issue. Feel free to reopen this if there is any further discussion.
