### ISSUE TITLE
[DOCS] Code typo correction

### ISSUE THREAD

**Issue by pstansell** [takuseno/d3rlpy#32]
This is extremely minor, but you have a typo in your code on this page
https://d3rlpy.readthedocs.io/en/latest/references/off_policy_evaluation.html

You have spelt `mixed` incorrectly on this line of your example
```python
dataset, env = get_pybullet('hopper-bullet-miexed-v0')
```

**Comment by pstansell** [comment]
Another very minor typo is `TorchSciprt` on this page https://d3rlpy.readthedocs.io/en/latest/references/save_and_load.html

**Comment by takuseno** [comment]
@pstansell Thank you for reporting this! I've fixed those! (it may take a while the readthedocs have the latest version.)
