### ISSUE TITLE
[BUG] d4rl and d3rlpy do not fit the gym version

### ISSUE THREAD

**Issue by HenryZhang-git** [takuseno/d3rlpy#323]
Hi，
I have some problem when I configure a virtual environment.I have install 'd4rl==1.1' and 'gym==0.23.1'
But when I `pip install d3rlpy`,terminal tell me that:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
d4rl 1.1 requires gym<0.24.0, but you have gym 0.26.2 which is incompatible.
`
and then I `pip install gym==0.23.1`,the terminal tell me that:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
d3rlpy 2.0.4 requires gym>=0.26.0, but you have gym 0.23.1 which is incompatible.`
What do you do to balance the gym version of d4rl and d3rlpy？Thank you!

**Comment by takuseno** [comment]
@HenryZhang-git `d3rlpy` requires `gym>=0.26.0` for interface compatibility. On the other hand, `d4rl` technically works with any versions of Gym. On my side, I usually install d4rl as follows:
```
pip install d3rlpy
pip install git+https://github.com/Farama-Foundation/D4RL
pip install -U gym
pip uninstall pybullet
```

**Comment by HenryZhang-git** [comment]
> @HenryZhang-git `d3rlpy` requires `gym>=0.26.0` for interface compatibility. On the other hand, `d4rl` technically works with any versions of Gym. On my side, I usually install d4rl as follows:
> 
> ```
> pip install d3rlpy
> pip install git+https://github.com/Farama-Foundation/D4RL
> pip install -U gym
> pip uninstall pybullet
> ```

Thanks for your reply!So, you mean that D4RL does not require the version of Gym to be less than 0.24.0 as mentioned in 'requirement. txt'. Can I boldly try higher versions of Gym？

**Comment by takuseno** [comment]
Yes, you can 😄

**Comment by HenryZhang-git** [comment]
> Yes, you can 😄

Thanks for your reply!I will close this Issues~
