### ISSUE TITLE
Add one-off transitions to the ReplayBuffer

### ISSUE THREAD

**Issue by gunshi** [takuseno/d3rlpy#325]
Hi,
I've been trying to play around with the latest version of d3rlpy (and also port my code using the older version to be compatible with the new version) and I had a question about the ReplayBuffer.
I've been finding it a bit confusing to understand how to work with all the components (writer, buffer, picker etc), and was wondering if the Replaybuffer already allows the following feature (or how I can define a class inheriting from it to enable it):
Given a dataset of episodes/trajectories that the replay buffer is constructed from, can we later add a few transitions to the replay buffer which are not necessarily part of a full episode or are sequentially related to the other transitions, but just are some meaningful transitions that we'd like to have in the buffer so that they're sampled for RL? 

I'm inclined to think no, since the replay buffer object doesn't expose the transitions list anymore like the MDPDataset used to earlier, and we only get to the transitions through the episode list, suggesting that any new transitions can only be added as part of episodes?
 
Any pointers would be great, thanks!

**Comment by takuseno** [comment]
@gunshi Hi, thanks for the issue. You're right that the latest replay buffer design is different from the previous `MDPDataset` implementation. Does this cover your use case?
```
# assuming that we already have pre-collected dataset
buffer, _ = d3rlpy.datasets.get_d4rl("hopper-medium-v0")

# add any transitions
buffer.append(observation1, action1, reward1)
buffer.append(observation2, action2, reward2)
# clip episode and set terminated=True if its environment termination.
buffer.clip_episode(terminated=<True or False>)

# you can repeat above as much as you want
```

**Comment by gunshi** [comment]
hey @takuseno,
thanks for your reply! yes your code snippet works with one caveat which I just wanted to point out in case you want to patch it:
If we want to add a terminal transition to the buffer (second last and last state), this is not possible because the clip_episode function returns without doing anything if the transition_count ==0, which will be true when we will be trying to append a terminal transition since we only need to append one (ops, act, rew) tuple for that and it is assumed that d3rlpy will append a dummy tuple for the last state on it's own (as coded in clip_episode() after that ^^ transition_count check, before starting a new active episode). 

For now I have just explicitly appending both the second last and last (terminal) state to make the function think the transition count is 1, so that it does the other things it does (start a new active episode) before returning.
Thanks again!

**Comment by takuseno** [comment]
Just 1 transition without environment termination cannot be used as a training data as you pointed out. This is because we need to use the next transition for bootstrapping. If you set `buffer.clip_episode(terminated=True)`, you can use it as training data.
