### ISSUE TITLE
[REQUEST] How to manually define the action space whether is discrete or continuous when building MDP dataset 

### ISSUE THREAD

**Issue by Zebin-Li** [takuseno/d3rlpy#338]
Hi,

I am using ```dataset = d3rlpy.dataset.MDPDataset(
    observations=observations,
    actions=actions,
    rewards=rewards,
    terminals=terminals,
)``` to build a dataset, and here my action is designed to a two-dimensional **continuous space**. The state/action/reward are from other experiments and in the collected data, the actions are, e.g., [14, 6], [10, 8]. However, when I running any algorithms, the action space was automatically specified as a **discrete space** because the all the actions in the collected data are integers (though I specified the type as np.float64). My question is how can I manually set the action space to be continuous? Thank you very much!

**Comment by takuseno** [comment]
@Zebin-Li Thanks for the issue. In the latest release, action-space cannot be directly specified. To address this issue, I've made changes to support this use case in this [commit](https://github.com/takuseno/d3rlpy/commit/9eb98e425328cadc118c571919b1776175c61cc5). If you install d3rlpy from the latest master branch, you can use this feature like this.
```
    replay_buffer = d3rlpy.dataset.ReplayBuffer(
        d3rlpy.dataset.InfiniteBuffer(),
        episodes=episodes,
        action_space=d3rlpy.ActionSpace.CONTINUOUS,
    )
```

**Comment by takuseno** [comment]
Sorry, I missed that you're using `MDPDataset`. In the next [commit](https://github.com/takuseno/d3rlpy/commit/68b25f21e49d9a5c0832b080c586a5b2aebbdc00), you can also give `action_space` option to `MDPDataset`.
```
replay_buffer = d3rlpy.dataset.MDPDataset(
    observations=observations,
    actions=actions,
    rewards=rewards,
    terminals=terminals,
    action_space=d3rlpy.ActionSpace.CONTINUOUS,
)
```

**Comment by Zebin-Li** [comment]
Thank you very much!

**Comment by takuseno** [comment]
Let me close this issue. This feature will be included in the next release.
