### ISSUE TITLE
[Question] Access to policy's weights 

### ISSUE THREAD

**Issue by omidsbhn** [takuseno/d3rlpy#339]
Hi, 
I trained an agent using an offline data set. Now I need to access the weights in the policy network for further extensibility investigations (using for example captum library). So, first I saved the policy network using `cql.save_policy("policy.pt")`. But as the saved policy a TorchScript, I do not have access to the weights or layers.

```
policy = torch.jit.load("policy.pt")
scripted_state_dict = policy.state_dict()
print(scripted_state_dict)

> OrderedDict()
```
```
print("Keys in scripted_state_dict:", scripted_state_dict.keys())

> Keys in scripted_state_dict: odict_keys([])
```

Could you help me please with the issue?

**Comment by takuseno** [comment]
@omidsbhn Thanks for the issue. Currently, this might be the easiest way to extract the `nn.Module` of policy function:
```py
import d3rlpy
import gym

env = gym.make("Pendulum-v1")
cql = d3rlpy.algos.CQLConfig().create()
cql.build_with_env(env)
print(cql.impl.policy)

# NormalPolicy(
#   (_encoder): VectorEncoder(
#     (_layers): Sequential(
#       (0): Linear(in_features=3, out_features=256, bias=True)
#       (1): ReLU()
#       (2): Linear(in_features=256, out_features=256, bias=True)
#       (3): ReLU()
#     )
#   )
#   (_mu): Linear(in_features=256, out_features=1, bias=True)
#   (_logstd): Linear(in_features=256, out_features=1, bias=True)
# )
```

**Comment by omidsbhn** [comment]
Great, thanks.

**Comment by takuseno** [comment]
Let me clos this. Feel free  to reopen this if there is any further question.
