### ISSUE TITLE
[REQUEST] Save model less frequently than metrics

### ISSUE THREAD

**Issue by pstansell** [takuseno/d3rlpy#34]
Hello, when running `fit_online` I'd like to be able to save the metrics regularly (eg, once every episode, which is 200 timesteps for the pendulum environment) without having to save the model `.pt` files at the same high frequency (because the model files are quite large). 

Put another way, I'd like to be able to write data to the `evaluation.csv` file without having to write a `model_?????.pt` file every time.

I can't see how this is possible in the current code.  If it's not possible, I'd like to request it as a feature.  Thanks!

**Comment by takuseno** [comment]
@pstansell Hi, sorry for being late. Now `eval_interval` argument is available.
https://github.com/takuseno/d3rlpy/commit/0d91df6fb4052ced9754a556116a50d6b0943457

**Comment by pstansell** [comment]
@takuseno, thanks for adding `eval_interval`, but I can only see it available in `fit_batch_online()`, not in `fit_online()`, which is where I wanted to use it.

**Comment by takuseno** [comment]
Ah, sorry. I've added `save_interval` to both methods.

**Comment by pstansell** [comment]
After further experimentation, I think v0.51 already had the argument I wanted to control the rate at which model files were written, that is,
```
  save_interval – interval to save parameters.
```
I hadn't realised what it did.  Sometimes I struggle to understand exactly what the fuction arguments do based on their names and descriptions.  But, anyway, the problem is solved now so I will close the issue.  You make changes so quickly, it's hard for me to keep up :-).  Thanks very much!

**Comment by pstansell** [comment]
@takuseno, it seems that `fit_online()` does not allow argument `eval_interval`.

**Comment by takuseno** [comment]
Yes, `fit_online` does not have that option. But you can control save frequency with `save_interval`.

**Comment by pstansell** [comment]
But doesn't that mean that I have to save models at the same rate as metrics?  Put another way, the number of lines in metric files, for example `time_step.csv`, will be the same as the number of output files named `model_*.pt`.  My initial desire was to be able to save metrics at a higher rate than model files.  Given the current input arguments, I'm not sure if I can do that.

**Comment by takuseno** [comment]
The saved model file name and the epoch number in metrics will match. So, if you give `save_interval=2`, the files and metrics will be like below.
```
metrics

0,xxx,yyy
1,xxx,yyy
2,xxx,yyy
3,xxx,yyy
4,xxx,yyy
.
.

model files

model_0.pt
model_2.pt
model_4.pt
.
.
```

**Comment by takuseno** [comment]
Oh, wait. I found my bad. I'll fix this.
https://github.com/takuseno/d3rlpy/blob/0d91df6fb4052ced9754a556116a50d6b0943457/d3rlpy/online/iterators.py#L258

**Comment by takuseno** [comment]
@pstansell I've fixed this in the last commit.
https://github.com/takuseno/d3rlpy/commit/b6c9b69e95fee386cff0d7a8c213fd1f7b01a642

**Comment by pstansell** [comment]
I tested it and confirm that it's fixed now.  Thanks very much.
