### ISSUE TITLE
[BUG] AWAC:  Not all tensors loading to cuda device

### ISSUE THREAD

**Issue by Zebin-Li** [takuseno/d3rlpy#341]
Hi @takuseno, 

I added a comment under #329 but I saw it has been closed, therefore, I report the issue here again.

I am using AWAC and I also met the issue that not all tensors loading to cuda device.
My code is:
```
with open("dataset_0926_3.h5", "rb") as f:
    new_dataset = d3rlpy.dataset.ReplayBuffer.load(f, d3rlpy.dataset.InfiniteBuffer())

awac = d3rlpy.algos.AWACConfig(
    actor_learning_rate=3e-4,
    critic_learning_rate=5e-4,
    batch_size=128,
    action_scaler=MinMaxActionScaler(),
    observation_scaler=MinMaxObservationScaler(),
    reward_scaler=MinMaxRewardScaler(),
    update_actor_interval=1,
    n_action_samples=4
).create(device=True)

awac.fit(
    new_dataset,
    n_steps=100000,
    n_steps_per_epoch=200,
    save_interval=10,
    experiment_name=f"AWAC",
    logger_adapter=d3rlpy.logging.TensorboardAdapterFactory(root_dir="tensorboard_logs_0926"),
)
```
And the error occurred:
![image](https://github.com/takuseno/d3rlpy/assets/52910998/d25b3142-48ac-400d-9510-9e66b2965770)
I cannot figure it out, thank you for your help!

**Comment by takuseno** [comment]
Thanks for reporting this issue! I'll investigate this. I believe you're using v2.1.0 or the latest master branch, right?

**Comment by Zebin-Li** [comment]
Thank you for the quick reply! I am using v2.0.4.

**Comment by Zebin-Li** [comment]
I just tried v2.1.0 but the same error also occurred:
![1696000484217](https://github.com/takuseno/d3rlpy/assets/52910998/6c0bab76-c013-49fe-9a57-a901c7afb3ec)
Besides, it seems that for v2.1.0 AWAC removed the parameter 'update_actor_interval'. Thank you!

**Comment by takuseno** [comment]
@Zebin-Li Thank you for sharing information. I think I've fixed this issue at this latest commit: https://github.com/takuseno/d3rlpy/commit/6cbaf66c43daaa324d51ee0c60660e7084a5666f . Please let me know if the issue still exists.

**Comment by Zebin-Li** [comment]
Hi @takuseno, I tried the latest commit and it works now, thank you!

**Comment by takuseno** [comment]
Let me close this issue. This fix will be included in the next release. Feel free to reopen this if there is any further discussion.
