### ISSUE TITLE
[REQUEST] Specify action_space for Algo

### ISSUE THREAD

**Issue by serenawjw** [takuseno/d3rlpy#343]
**Is your feature request related to a problem? Please describe.**
I've been working with DQN for my project. Specifically, I generate data from several simulators simultaneously, with each action (step) predicted by an algorithm checkpoint (discrete action). At the end of each episode, I generate a mdp_dataset and perform a batch offline update with data from different simulators. 
Everything works fine with DQN, and now I would like to switch to another algorithm that supports discrete control as well. I've tried SAC, BCQ, and CQL, but none of them worked. The algorithms have been interpreting my action space as continuous, and I'm not sure how to switch it to discrete.

**Describe the solution you'd like**
Is there any way to specify the action space for algorithms that support both discrete and continuous control?

**Additional context**
I went through a [closed issue](https://github.com/takuseno/d3rlpy/issues/338) to manually define the action space for the MDP dataset. I tried, but it didn't help, as the problem emerged as soon as I tried to create the algorithm and make predictions. I would like to know how to control the type of action it predicts.

**Comment by takuseno** [comment]
@serenawjw Sorry for the late response. You can use `DiscreteSAC`, `DiscreteBCQ` and `DiscreteCQL` for discrete action-space.
