### ISSUE TITLE
[Question] Predicted value

### ISSUE THREAD

**Issue by spencerJ777** [takuseno/d3rlpy#344]
Hi,

This might be a stupid question. I trained an algorithm with several finite-horizon episodes. When I use predict_value on a single (s,a) in the episode, is it providing the value for that single state-action pair like the immediate reward, or is it supposed to be like the sum of rewards from that (s,a) till the end of the episode?

Also, it is possible to calculate the actual value in the dataset and compare it with the predicted value by the algorithm?

Any help would be much appreciated.

**Comment by takuseno** [comment]
@spencerJ777 Hi, thanks for the issue.

Regarding the first question, this is the right answer:
>is it supposed to be like the sum of rewards from that (s,a) till the end of the episode?

To compute return of an episode, you can do as follows:
```py
import d3rlpy
import numpy as np

dataset, env = d3rlpy.datasets.get_cartpole()

dqn = d3rlpy.algos.DQNConfig().create()
dqn.build_with_env(env)

episode = dataset.episodes[0]

# step 1: compute discount factors on each step
discounts = dqn.config.gamma ** np.arange(episode.size())

# step 2: compute discounted sum of rewards
discounted_return = np.sum(discounts * episode.rewards.reshape(-1))

# step 3: estimate discounted value
preds = dqn.predict_value(episode.observations[:1], episode.actions[:1])

# compare return and prediction
print(discounted_return, preds)
```

**Comment by spencerJ777** [comment]
Thanks! This clears up my confusion.
