### ISSUE TITLE
[BUG] Calculation of gamma via batch.intervals

### ISSUE THREAD

**Issue by nicoguertler** [takuseno/d3rlpy#346]
Hi, this looks like a bug to me but I might be missing something.

**Describe the bug**
When gamma is calculated for the transitions in a batch then the hyperparameter gamma is exponentiated by `batch.intervals`, e.g. [here for DDPG](https://github.com/takuseno/d3rlpy/blob/45c9c655f75ac5795e0e820b7022ea3b6d739b4c/d3rlpy/algos/qlearning/torch/ddpg_impl.py#L80C14-L80C14). However, `batch.intervals` [is set to the terminals](https://github.com/takuseno/d3rlpy/blob/45c9c655f75ac5795e0e820b7022ea3b6d739b4c/d3rlpy/dataset/mini_batch.py#L84C13-L84C13) so it is almost always 0 and therefore gamma is calculated to (hyperparameter gamma)**0=1 which effectively sets gamma to 1. In the experiments I ran this makes the critic loss diverge due to TD learning.

**To Reproduce**
Run an algorithm, for example CRR, with version 2.1 and observe the value gamma is set to [here](https://github.com/takuseno/d3rlpy/blob/45c9c655f75ac5795e0e820b7022ea3b6d739b4c/d3rlpy/algos/qlearning/torch/ddpg_impl.py#L80C14-L80C14).

**Expected behavior**
I expected gamma to be left unchanged in the normal setting.

**Additional context**
I did not observe a diverging critic in version 1.1.1.

As version 2 is a bit different from version 1 I might be missing something important. Thank you for your feedback!

**Comment by takuseno** [comment]
@nicoguertler Hi, thanks for reporting this! This has been fixed at the latest commit https://github.com/takuseno/d3rlpy/commit/eab9e9f4cd54c5d9b9064b2e2df895d559cb0942 . I'll release a new version `v2.2.0` in a few hours.

**Comment by takuseno** [comment]
The `v2.2.0` package has been released. If you reinstall d3rlpy by `pip install -U d3rlpy`, the issue should be resolved.

**Comment by nicoguertler** [comment]
Thanks a lot for fixing this so quickly! With the new version the critic loss does not diverge anymore and I get the expected performance. So the issue is solved for me.
I have another quick question: Would you recommend version 1 or 2 of d3rlpy for research projects at the moment?

**Comment by takuseno** [comment]
Good to hear that it works now! I believe v2 is ready for reseaech use. v2 also has many features v1 didn't implement. If you find anything critical for research ise case, please report it in GitHub issues so that I can quickly fix.

**Comment by nicoguertler** [comment]
Ok, sounds good. Thanks!

**Comment by takuseno** [comment]
Let me close this issue. Feel free to reopen tbis if there is any further discussion.
