### ISSUE TITLE
[BUG] The gym version of D4RL and d3rlpy doesn't seem match.

### ISSUE THREAD

**Issue by CTID282** [takuseno/d3rlpy#349]
Hi,
First, I want to say thank you for making such a wonderful library.

I checked that you solved this problem before. #337
But I am facing the following error.

`AttributeError: 'dict' object has no attribute 'env_specs'`

Unlike what is shown in #337, it doesn't work in environments like `Hopper` or `Walker2d`.

Can you tell me how to fix this? Thank you!

**Comment by takuseno** [comment]
@CTID282 Hi, thank you for the issue. #323 is the actual relevant issue here. The easiest fix is as follows:
```
# assuming that you're using d3rlpy==2.2.0
$ pip uninstall d4rl gym
$ d3rlpy install d4rl
```
d3rlpy provides some useful CLI commands. `d3rlpy install d4rl` will install all necessary dependencies to experiment with D4RL.

**Comment by CTID282** [comment]
I appreciate your quick and accurate response.
I've resolved the issue.
I will now close this issue.
Thank you !
