### ISSUE TITLE
[BUG] Kernel size can't be greater than actual input size.

### ISSUE THREAD

**Issue by feyza-droid** [takuseno/d3rlpy#35]
First of all, thank you for creating such a great library.

**Describe the bug**
I am running online training with DQN on gym atari environment. But I guess because of hardcoded part, observation size is smaller than the kernel size which causes error. If the kernel size is hardcoded, could you change it?

**To Reproduce**

    def dqn_train(n_steps=10000, use_gpu=False):

      # setup DQN algorithm
      dqn = DQN(n_frames=4, learning_rate=1e-3, target_update_interval=100, use_gpu=use_gpu)
  
      # setup explorers
      explorer = LinearDecayEpsilonGreedy(start_epsilon=1.0,
                                          end_epsilon=0.1,
                                          duration=10000)
  
      # setup replay buffer
      buffer = ReplayBuffer(maxlen=50000, env=env)
  
      # start training
      dqn.fit_online(env,
                     buffer,
                     explorer = explorer,
                     eval_env=eval_env,
                     n_steps=20000, #n_steps=50000,
                     n_steps_per_epoch=10000, #n_steps_per_epoch=10000,
                     show_progress=True)
      return buffer, dqn

    env = gym.make('Breakout-v0') 
    eval_env = gym.make('Breakout-v0')
    buffer, dqn = dqn_train(n_steps=20000)

The code is more or less like this.

**Expected behavior**
It gives the following error.
**_RuntimeError: Calculated padded input size per channel: (160 x 3). Kernel size: (8 x 8). Kernel size can't be greater than actual input size._** 

**Additional context**
Environment's observation space is Box(0, 255, (210, 160, 3), uint8).

Could you help me with this? Thanks in advance.

**Comment by takuseno** [comment]
@feyza-droid Hello, thank you for reporting this issue! I found this is because the environment has the channel-last observation shape `(210, 160, 3)`. But, `d3rlpy` expects channel-first shape `(3, 210, 160)`. I'm planning to support `channel_last` flag to handle this case. But, for now, I would suggest using my Atari wrapper.
```
$ pip install git+https://github.com/takuseno/d4rl-atari
```

```py
import gym
import d4rl_atari

env = gym.make('breakout-mixed-v0', stack=False)

env.observation_space.shape == (1, 84, 84)  # resized gray-scale image.
```

**Comment by takuseno** [comment]
@feyza-droid Hello. In the last commit. I've implemented `ChannelFirst` wrapper to solve this issue.
https://github.com/takuseno/d3rlpy/commit/3865880d7b7a3b85a546b1da2f8e707c287a7e6c

```py
import gym
from d3rlpy.algos import DQN
from d3rlpy.envs import ChannelFirst

# this wrapper transposes the observation
env = ChannelFirst(gym.make('Breakout-v0'))

dqn = DQN()
dqn.fit_online(env)
```

**Comment by feyza-droid** [comment]
@takuseno Thank you so much! Now I'm able to use d3rlpy with atari breakout env. 😄

**Comment by takuseno** [comment]
Let me close this issue since this seems to be solved.
