### ISSUE TITLE
[BUG] Cannot use SAC with temperature 0

### ISSUE THREAD

**Issue by BasVolkers** [takuseno/d3rlpy#351]
**Describe the bug**
I would like to be able to use SAC while setting the temperature parameter to be a constant 0.

**To Reproduce**
``` python
model = DiscreteSACConfig(temp_learning_rate=0, initial_temperature=0).create(device="cuda:0")
```
This will give a `ValueError: math domain error` because taking the log of 0 is impossible:
``` python
    log_temp = create_parameter(
        (1, 1),
        math.log(self._config.initial_temperature),
        device=self._device,
    )
```

**Expected behavior**
While I understand that a temperature > 0 may be what is intended, I want to compare policies learned with a temperature of 0 to other policies. Is there a solution or should I use another algorithm?

**Comment by takuseno** [comment]
@BasVolkers Hi, thanks for the issue. I quickly made a change to support your use case at this commit https://github.com/takuseno/d3rlpy/commit/1dec1772a0e0c5f860319a781977415def40ede5 . If you can install d3rlpy from source code, you can use this feature.

**Comment by BasVolkers** [comment]
Seems to work! Thanks for the quick fix :)
