### ISSUE TITLE
[REQUEST] Error in first page of documentation

### ISSUE THREAD

**Issue by TruthSeekerxx** [takuseno/d3rlpy#354]
Link:
[https://d3rlpy.readthedocs.io/en/v2.2.0/tutorials/getting_started.html](https://d3rlpy.readthedocs.io/en/v2.2.0/tutorials/getting_started.html)

Code below throws an error:
```
observation = env.reset()

# return actions based on the greedy-policy
action = dqn.predict(np.expand_dims(observation, axis=0))

# estimate action-values
value = dqn.predict_value(np.expand_dims(observation, axis=0), action)
```
Error:
_ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part._

Proposed fix (observation -> observation[0]):
```
observation = env.reset()

# return actions based on the greedy-policy
action = dqn.predict(np.expand_dims(observation[0], axis=0))

# estimate action-values
value = dqn.predict_value(np.expand_dims(observation[0], axis=0), action)
```

**Comment by takuseno** [comment]
@TruthSeekerxx Hi, thank you for reporting this! I've fixed this at the latest commit https://github.com/takuseno/d3rlpy/commit/fae340299ff2df8edca9dc83cd5616df879d6540 .

**Comment by takuseno** [comment]
Let me close this issue. Feel free to reopen this if there is any further discussion.
