### ISSUE TITLE
AttributeError: 'KitchenMicrowaveKettleLightSliderV0' object has no attribute 'wrapped_env'

### ISSUE THREAD

**Issue by BrightMoonStar** [takuseno/d3rlpy#358]
The following is my test code 
`from d3rlpy.datasets import get_d4rl     # D4RL datasets`
`get_d4rl("kitchen-complete-v0")`
But there reports an error about `AttributeError: 'KitchenMicrowaveKettleLightSliderV0' object has no attribute 'wrapped_env'`

```
Warning: Mujoco-based envs failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'six'
Warning: Flow failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'flow'
Warning: CARLA failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'carla'
Warning: GymBullet failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'pybullet_envs'
Reading configurations for Franka
Initializing Franka sim
/home/dellpc/anaconda3/envs/d4rl/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
load datafile: 100%|██████████| 6/6 [00:00<00:00, 1409.61it/s]
Traceback (most recent call last):
  File "/home/dellpc/Downloads/publishing/pubcode/main.py", line 5, in <module>
    get_d4rl("kitchen-complete-v0")
  File "/home/dellpc/anaconda3/envs/d4rl/lib/python3.9/site-packages/d3rlpy/datasets.py", line 435, in get_d4rl
    unwrapped_env: gym.Env[Any, Any] = env.env.env.env.wrapped_env  # type: ignore
AttributeError: 'KitchenMicrowaveKettleLightSliderV0' object has no attribute 'wrapped_env'
2023-12-06 22:06.17 [info     ] Signatures have been automatically determined. action_signature=Signature(dtype=[dtype('float32')], shape=[(9,)]) observation_signature=Signature(dtype=[dtype('float32')], shape=[(60,)]) reward_signature=Signature(dtype=[dtype('float32')], shape=[(1,)])
2023-12-06 22:06.17 [info     ] Action-space has been automatically determined. action_space=<ActionSpace.CONTINUOUS: 1>
2023-12-06 22:06.17 [info     ] Action size has been automatically determined. action_size=9
```

**Comment by takuseno** [comment]
@BrightMoonStar Thanks for the issue. This is a little tricky issue to solve because implementations of environments in D4RL are different from each other. I'll look into this in this weekend and let you know once it's done.

**Comment by BrightMoonStar** [comment]
Thank you for your efficient reply and great work !

**Comment by takuseno** [comment]
@BrightMoonStar I realized that it's extremely difficult to support kitchen environments of D4RL because environments are no longer compatible with the latest gym interface.  Instead, I decided to focus on [Minari](https://github.com/Farama-Foundation/Minari) ecosystem. In the latest commit, I added kitchen environment support to `get_minari` function https://github.com/takuseno/d3rlpy/commit/94e83459911124f3199101eead1ba5164a05d3a5 . If you install d3rlpy from source, you can try `kitchen-complete-v1` as follows:
```
dataset, env = d3rlpy.datasets.get_minari("kitchen-complete-v1")
```

For more information about Minari, please check this page.
https://minari.farama.org/

**Comment by BrightMoonStar** [comment]
Thanks for the solution you provide！I will check it soon.

**Comment by takuseno** [comment]
Let me close this issue. Feel free to reopen this if there is any further discussion.
