### ISSUE TITLE
[BUG] tentative bug in dataset.extend(dataset)

### ISSUE THREAD

**Issue by pstansell** [takuseno/d3rlpy#36]
**Describe the bug**

Unexpected `TypeError` from `dataset.extend(dataset)`.  (I'm relatively new to Python, so I'm not entirely sure it's a bug, but it seems very strange to me).

**To Reproduce**

The following script gives the error below:
```python
import numpy as np
from d3rlpy.dataset import MDPDataset

N = 10
observations = np.random.random((N, 3))
actions = np.random.random((N, 1))
rewards = np.random.random(N)
terminals = np.append(np.zeros(N-1, dtype='int'), [1])

dataset = MDPDataset(observations, actions, rewards, terminals)
#print(len(dataset))

dataset.extend(dataset)
print(len(dataset))
```
Error
```python
Traceback (most recent call last):
  File "bug_dataset.py", line 13, in <module>
    dataset.extend(dataset)
  File "d3rlpy/dataset.pyx", line 458, in d3rlpy.dataset.MDPDataset.extend
  File "d3rlpy/dataset.pyx", line 443, in d3rlpy.dataset.MDPDataset.append
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'list'
```
However, if I uncomment the `print` statement on line 11 the code runs without error.

**Additional context**

I'm using the following
```
Python            3.8.0
d3rlpy            0.51
numpy             1.19.5
```

**Comment by takuseno** [comment]
@pstansell Thanks for reporting this issue! I confirm it's a bug. I'll fix this immediately. But, You can avoid an error by doing as follows:
```
dataset = MDPDataset(observations, actions, rewards, terminals)

dataset.build_episodes()

dataset.extend(dataset)
```

**Comment by takuseno** [comment]
I've fixed this in the latest commit.
https://github.com/takuseno/d3rlpy/commit/43abc7af5e164ca3b57371e5a4eaec522e8dd708

**Comment by pstansell** [comment]
I think there still might be something wrong because the there seems to be an extra episode added, ie, 3 instead of 2.

The output of the following code:
```python
import numpy as np
from d3rlpy.dataset import MDPDataset

N = 10
observations = np.random.random((N, 3))
actions = np.random.random((N, 1))
rewards = np.random.random(N)
terminals = np.append(np.zeros(N-1, dtype='int'), [1])

# First use of extend.
dataset = MDPDataset(observations, actions, rewards, terminals)  # dataset of single episode
dataset.extend(dataset)
print("p1: ", len(dataset))

# Reset and second use of extent, should be identical to first.
dataset = MDPDataset(observations, actions, rewards, terminals)
print("p2: ", len(dataset))
dataset.extend(dataset)
print("p3: ", len(dataset))
```
is
```
p1:  3
p2:  1
p3:  2
```

**Comment by takuseno** [comment]
@pstansell I see. I'll investigate this and update this issue when it's resolved. Sorry for the inconvenience.

**Comment by takuseno** [comment]
@pstansell Helli, I've finally fixed the issue in the last commit.
https://github.com/takuseno/d3rlpy/commit/21430b93b91bdaf3a4a8c989de7888ff9ed49d44

**Comment by pstansell** [comment]
Thank you so much (I tested it again and it seems okay now).
