### ISSUE TITLE
[REQUEST] Support WandB logging

### ISSUE THREAD

**Issue by BasVolkers** [takuseno/d3rlpy#362]
**Is your feature request related to a problem? Please describe.**
I would like to use WandB to log my runs

**Describe the solution you'd like**
For this I need a WandBLoggerAdapter that uses the wandb python api to write metrics.
I'm curious if this is something where you also see added value. 
I would love to help; I already made a version I'm using myself locally.

**Comment by takuseno** [comment]
@BasVolkers Hi, thanks for the issue. Since I recognize that there are many wandb users out there, I'd appreciate if you make pull requests for d3rlpy! Otherwise, I'll look into this by myself.

**Comment by BasVolkers** [comment]
Sounds good! I'll make an initial PR somewhere next week

**Comment by HateBunnyPlzzz** [comment]
hey @BasVolkers , 
If you're working on the PR, I'd love to contribute in writing the custom LoggerAdaprter class for WandB.
Please let me know
Thank you.
