### ISSUE TITLE
[REQUEST] Possibility of customizing the last activation function in VectorEncoderFactory

### ISSUE THREAD

**Issue by wenxuhaskell** [takuseno/d3rlpy#371]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Today "VectorEncoderFactory" allows to include/exclude the last activation function. There is no possibility of specifying the last activation function. Sometimes we would like the last activation function to be different from the hidden layers activation functions. Therefore customizing the last activation function would be beneficial. 

One simple workaround could be: 

replace exclude_last_activation (bool) by last_activation (str). 
In VectorEncoder(), 
...
    if last_activation ==''" or last_activation == None:
       # exclude last activation
       ...
    else:
       layers.append(last_activation)
...

Thanks!

**Additional context**
No.

**Comment by takuseno** [comment]
@wenxuhaskell Hi, thanks for the issue. I quickly added this feature at this latest commit https://github.com/takuseno/d3rlpy/commit/06dd7a7698bf68af0645afeb62f148aad921a9bd . If you pull the master branch, you can use this functionality.

**Comment by wenxuhaskell** [comment]
@takuseno With the latest master branch, the proposed feature is working (specifying the last activation function). Thank you for the quick support!
