### ISSUE TITLE
[REQUEST / QUESTION] Changing the network architecture in DQN

### ISSUE THREAD

**Issue by mhmohebbi** [takuseno/d3rlpy#373]
Hi!

I was wondering if it would be possible for me to change the network in DQN to be a transformer? For the specific task I am working on I need to set up a DQN in an offline setting where the policy is developed through a Transformer with no positional encoding as the network architecture.
If this is possible, could anyone guide me on what changes I'd need to make to this library?

**Comment by takuseno** [comment]
@mhmohebbi Hi, thanks for the issue. Here is the documentation to describe how you can change the network architecture.
https://d3rlpy.readthedocs.io/en/v2.3.0/tutorials/customize_neural_network.html

Note that currently, DQN does not support sequence inputs. Thus, you can combine it with Transformer, but the input is a single time-step transition. d3rlpy already supports Decision Transformer though.

**Comment by takuseno** [comment]
Let me close this issue since I feel I described the status of this library. Feel free to reopen this if there is any further discussion.
