### ISSUE TITLE
[REQUEST] More control over logging options

### ISSUE THREAD

**Issue by jdesman1** [takuseno/d3rlpy#376]
**Is your feature request related to a problem? Please describe.**
D3rlpy has so far been a pleasure to work with. However, I've noticed that for models that take many epochs to train, I sometimes sit on an enormous storage footprint after saving many model checkpoints, which can be inconvenient for myself or others that share the same resource allocation.

**Describe the solution you'd like**
Perhaps this exists and I missed it in the documentation, but it might be nice to have a parameter that represents "log every n epoch". Being able to use this in the logging adapter classes would be a convenient feature for long training runs, or hyperparameter searches that can take a long time.

**Comment by takuseno** [comment]
@jdesman1 Hi, thank you for the issue. Yes, d3rlpy already provides an option to control this, which is called `save_interval`.
https://d3rlpy.readthedocs.io/en/v2.3.0/references/algos.html#d3rlpy.algos.QLearningAlgoBase.fit

If you set `save_interval=10`, d3rlpy will save models every 10 epochs.
