### ISSUE TITLE
[Question] Is it possible to only collect image observation?

### ISSUE THREAD

**Issue by zichunxx** [takuseno/d3rlpy#384]
Hi! 

I want to use `d3rlpy` to collect image observations to train my custom network. So, I only want to collect these images and save them into `.h5` file. Is it possible? 

Because the size of the image observation is big, I met some memory errors during the process of collecting. Meanwhile, I'm not sure `d3rlpy` can solve this kind of issue. 

Thanks in advance for your reply!

**Comment by takuseno** [comment]
Hi, @zichunxx thank you for the issue. I imagine that your question is whether we could save images more than RAM size of your computer. The short answer is it's doable, but it's tricky. d3rlpy does not directly support this use case. Here is a workaround:
1. Collect image data by yourself and save them as numpy's buffer data.
2. Use `numpy.memmap` to load the saved buffer.
3. Build `MDPDataset` with the loaded buffer.

See relevant discussion here #140 .

**Comment by takuseno** [comment]
I believe the proposal I mentioned above should resolve the issue. Let me close this issue. If there is any further discussion, feel free to reopen this.
