### ISSUE TITLE
[REQUEST] NotImplementedError: "save_policy method does not support tuple observation yet."

### ISSUE THREAD

**Issue by junyeop** [takuseno/d3rlpy#388]
In v2.4.0, d3rlpy supports observing tuples.

But when I look at the QLearningAlgoBase class inside the base.py script, I get an error saying that tuple observations are not supported within the save_policy method.

I want to save the model in onnx format using tuple observations.

Can you help me how to do this?

```
# class QLearningAlgoBase
def save_policy(self, fname: str) -> None:
        assert self._impl is not None, IMPL_NOT_INITIALIZED_ERROR

        if is_tuple_shape(self._impl.observation_shape):
            raise NotImplementedError(
                "save_policy method does not support tuple observation yet."
            )

        ...

```

**Comment by takuseno** [comment]
@junyeop Hi, thanks for the issue. Currently, this is a little tricky to support due to weirdness of `torch.script`. But, I'll look into this for the next release.

**Comment by junyeop** [comment]
@takuseno Hi, thank you for your reply. I'll be looking forward to the next release.

**Comment by takuseno** [comment]
@junyeop Hi, I've supported this functionality at this latest commit: https://github.com/takuseno/d3rlpy/commit/9e7d59a0b5b0775250a34734754173cbc764dadd . If you install d3rlpy from the source, you can use this feature. When you use the saved policy, you need to do as follows:

TorchScript
```py
policy = torch.jit.load("tuple_policy.pt")

# infer the action
tuple_observation = [torch.rand(1, 3), torch.rand(1, 5)]
action = policy(tuple_observation[0], tuple_observation[1])
```

ONNX
```py
ort_session = ort.InferenceSession('tuple_policy.onnx', providers=["CPUExecutionProvider"])

# infer the action
tuple_observation = [np.random.rand(1, 3).astype(np.float32), np.random.rand(1, 5).astype(np.float32)]
action = ort_session.run(None, {'input_0': tuple_observation[0], 'input_1': tuple_observation[1]})
```

**Comment by takuseno** [comment]
Let me close this issue since the request has been supported. This feature will be included in the next release.
