### ISSUE TITLE
[REQUEST] save decision transformer models as TorchScript/ONNX

### ISSUE THREAD

**Issue by turbosheep44** [takuseno/d3rlpy#390]
The Q Learning models have a `save_policy` method which allows them to be exported as TorchScript modules which makes it easy for me to train my models using `d3rlpy` and then execute them in a Rust program. 

The `DecisionTransformer` algorithms do not have `save_policy` and attempting to export `model.impl.modules.transformer` using `torch.jit.script` or `torch.jit.trace` produces errors.

**Solution**
A similar `save_policy` method on decision transformers.

**Comment by takuseno** [comment]
@turbosheep44 Hi, thanks for the issue. In the latest commit, I just implemented `save_policy` method for Decision Transoformer: https://github.com/takuseno/d3rlpy/commit/196974f39a54c5398e8085efd7aa347fb65f4301 .

Here is an example:
```py
# training and export
import d3rlpy

dataset, env = d3rlpy.datasets.get_pendulum()

dt = d3rlpy.algos.DecisionTransformerConfig(context_size=10).create()
dt.fit(dataset, n_steps=10000, n_steps_per_epoch=100, eval_env=env, eval_target_return=0)
dt.save_policy("dt.pt")
```
inference
```py
from collections import deque
import gym
import torch
import numpy as np

env = gym.make("Pendulum-v1", render_mode="human")

policy = torch.jit.load("dt.pt")

target_return = 0
obs, _ = env.reset()

observations = deque([np.zeros_like(obs)] * 10, maxlen=10)
actions = deque([np.random.random(1)] * 10, maxlen=10)
return_to_go = deque([[0]] * 10, maxlen=10)
timestep = deque([0] * 10, maxlen=10)

observations.append(obs)
t = 0
while True:
    action = policy(
        torch.tensor(observations, dtype=torch.float32),
        torch.tensor(actions, dtype=torch.float32),
        torch.tensor(return_to_go, dtype=torch.float32),
        torch.tensor(timestep, dtype=torch.int32),
    ).numpy()

    obs, reward, done, truncated, info = env.step(action)
    t += 1

    target_return -= reward
    observations.append(obs)
    actions.append(action)
    return_to_go.append([target_return])
    timestep.append(t)

    if done or truncated:
        break
```

**Comment by takuseno** [comment]
Please let me close this issue since the requested feature has been implemented. Feel free to reopen this if there is any further discussion.
