### ISSUE TITLE
[QUESTION] Offline Learning via custom MDPDataset

### ISSUE THREAD

**Issue by Charles-Lim93** [takuseno/d3rlpy#399]
Greetings,

I'm looking for the document for creating a custom/own MDPDataset,

But I'm wondering how to train the model with my own MDPDataset.

Because I'm using my environment for simulation, and don't have an idea for combining with d3rlpy's environments. Is there any way to conduct learning with custom environments? (eg. Airsim, Nvidia drive sim)

Can anyone share or suggest an example code for using your own MDP dataset?

Thank you in advanced.

**Comment by takuseno** [comment]
Let me close this issue since d3rlpy supports Gym and Gymnasium interface. Feel free to reopen this if there is any further discussion.
