### ISSUE TITLE
[BUG] Identical models being saved multiple times

### ISSUE THREAD

**Issue by pstansell** [takuseno/d3rlpy#40]
Hello @takuseno, I think identical models are being saved, unnecessarily, multiple times.

As far as I understand, the logic in `train_single_env()` from `d3rlpy/online/iterators.py` can be summarised by the following example with `n_steps_per_epoch = 3` and `save_interval = 2`
```python
import numpy as np

n_steps = 16
n_steps_per_epoch = 3
save_interval = 2

total_step = np.arange(n_steps)
# array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

epoch = total_step // n_steps_per_epoch
# array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5])

epoch % save_interval
# array([0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1])
```

The model is saved when `epoch % save_interval == 0`, therefore it's being saved 3 times when `epoch = 0`, 3 times when `epoch = 2`, 3 times when `epoch = 4`, etc, and I think it's correct to say that the epoch number is incremented every time the model is updated, so identical models are being saved multiple times.

**Comment by takuseno** [comment]
@pstansell Sorry for that. I've fixed this issue in the last commit.
https://github.com/takuseno/d3rlpy/commits/master

**Comment by pstansell** [comment]
Thanks!
