### ISSUE TITLE
gym version incompatibility

### ISSUE THREAD

**Issue by PandaGuang** [takuseno/d3rlpy#400]
It seems the gym version requirements from d3rlpy and d4rl are incompatible. 

After "pip install d3rlpy", I run the code and it showed no module named d4rl. Then I used "d3rlpy install d4rl" to install it, it finally showed:

d3rlpy 2.5.0 requires gym>=0.26.0
d4rl 1.1 requires gym<0.24.0, but you have gym 0.26.2 which is incompatible.

**Comment by takuseno** [comment]
@PandaGuang Hi, thanks for the issue. You need to install d4rl via d3rlpy CLI command:
```
$ d3rlpy install d4rl
```
This version of d4rl resolves some of compatibility issues for d3rlpy.

**Comment by takuseno** [comment]
Let me close this issue since the response above should the issue here.
