### ISSUE TITLE
[QUESTION] Custom evaluators not working.

### ISSUE THREAD

**Issue by shreyassgs00** [takuseno/d3rlpy#402]
Hi @takuseno,

I am trying to create a custom evaluator as provided in your documentation.

class CustomEnvironmentEvaluator(d3rlpy.metrics.EvaluatorProtocol):
    _env: gym.Env
    _n_trials: int
    _epsilon: float

    def __init__(self, env: gym.Env, n_trials: int = 10, epsilon: float = 0.0):
        self._env = env
        self._n_trials = n_trials
        self._epsilon = epsilon

    def _call_(self, algo: QLearningAlgoProtocol, dataset: ReplayBufferBase) -> float:
        return evaluate_qlearning_with_environment_custom(
            algo=algo,
            env=self._env,
            n_trials=self._n_trials,
            epsilon=self._epsilon,
        )

Whenever I try to fit the model using this evalutator, using:
 evaluators={
                'environment': CustomEnvironmentEvaluator(env, n_trials=100),
            },

It raises a NotImplementedError.

Could you please let me know how to solve this or is it the case that this is not yet supported? Thanks in advance for your time!

**Comment by takuseno** [comment]
@shreyassgs00 Thanks for the issue. Could you share a full stack-trace?

**Comment by shreyassgs00** [comment]
Hi @takuseno, please find it here:

NotImplementedError: 
File <command-3768798148954825>, line 1
----> 1 run_id, metrics = load_with_environment(mdp_dataset, df_train)
      2 print_log(f'Run ID: {run_id}',)
File <command-3768798148954815>, line 39, in load_with_environment(mdp_dataset, df_train)
     32 # Fit model
     33 model = d3rlpy.algos.IQLConfig(
     34     batch_size=256, gamma=0.99, actor_learning_rate=0.005, critic_learning_rate=0.005,
     35     observation_scaler=StandardObservationScaler(), action_scaler=MinMaxActionScaler(), reward_scaler=StandardRewardScaler(),
     36     tau=0.005, n_critics=2, expectile=0.5, weight_temp=3.0, max_weight=100.0
     37 ).create(device='cpu')
---> 39 metrics_tuples = model.fit(
     40     mdp_dataset,
     41     n_steps=n_steps,
     42     n_steps_per_epoch=n_steps_per_epoch,
     43     logger_adapter=d3rlpy.logging.FileAdapterFactory(root_dir="d3rlpy_model_parallel_logs"),
     44     evaluators={
     45         'environment': CustomEnvironmentEvaluator(env, n_trials=100),
     46     },
     47 )
     50 log_model_to_mlflow(model=model, run_id=run_id)
     52 params = {**custom_params, **get_params_from_model(model)}
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/d3rlpy/algos/qlearning/base.py:422, in QLearningAlgoBase.fit(self, dataset, n_steps, n_steps_per_epoch, experiment_name, with_timestamp, logging_steps, logging_strategy, logger_adapter, show_progress, save_interval, evaluators, callback, epoch_callback, enable_ddp)
    373 def fit(
    374     self,
    375     dataset: ReplayBufferBase,
   (...)
    388     enable_ddp: bool = False,
    389 ) -> List[Tuple[int, Dict[str, float]]]:
    390     """Trains with given dataset.
    391 
    392     .. code-block:: python
   (...)
    420         List of result tuples (epoch, metrics) per epoch.
    421     """
--> 422     results = list(
    423         self.fitter(
    424             dataset=dataset,
    425             n_steps=n_steps,
    426             n_steps_per_epoch=n_steps_per_epoch,
    427             experiment_name=experiment_name,
    428             with_timestamp=with_timestamp,
    429             logging_steps=logging_steps,
    430             logging_strategy=logging_strategy,
    431             logger_adapter=logger_adapter,
    432             show_progress=show_progress,
    433             save_interval=save_interval,
    434             evaluators=evaluators,
    435             callback=callback,
    436             epoch_callback=epoch_callback,
    437             enable_ddp=enable_ddp,
    438         )
    439     )
    440     return results
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/d3rlpy/algos/qlearning/base.py:588, in QLearningAlgoBase.fitter(self, dataset, n_steps, n_steps_per_epoch, logging_steps, logging_strategy, experiment_name, with_timestamp, logger_adapter, show_progress, save_interval, evaluators, callback, epoch_callback, enable_ddp)
    586 if evaluators:
    587     for name, evaluator in evaluators.items():
--> 588         test_score = evaluator(self, dataset)
    589         logger.add_metric(name, test_score)
    591 # save metrics
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/d3rlpy/metrics/evaluators.py:50, in EvaluatorProtocol.__call__(self, algo, dataset)
     36 def __call__(
     37     self,
     38     algo: QLearningAlgoProtocol,
     39     dataset: ReplayBufferBase,
     40 ) -> float:
     41     """Computes metrics.
     42 
     43     Args:
   (...)
     48         Computed metrics.
     49     """
---> 50     raise NotImplementedError

**Comment by takuseno** [comment]
Thanks for sharing this. I noticed that your method name is wrong:
```
_call_ -> __call__
```

**Comment by shreyassgs00** [comment]
Thanks for that answer. Closing this issue for now.
