### ISSUE TITLE
[REQUEST] Support for MultiBinary action spaces

### ISSUE THREAD

**Issue by syed881** [takuseno/d3rlpy#41]
Hi,

Thanks for such superb work. 

I am working with an environment that has MultiBinary action spaces. I have successfully created the dataset. However, when I try to train BC or DCQL, it shows action_size=2 and gives an error if evaluated during training. If I don't evaluate during training, then it gets trained but with action_size=2 (which I can't use for testing purposes). 

Could you please help me out with this issue? many thanks in advance.

**Comment by takuseno** [comment]
@syed881 Hi, thanks for reporting an issue. Honestly, I'm not sure what `MultiBinary` action space is. Is it expecting the actions like this?
```
[0, 1, 0, 0, 1]
```
If it's so, you can convert the action-space into the flat discrete space. If it's 2-dimensional binary actions, it's the exactly same as 4-dimensional flag discrete space.

**Comment by syed881** [comment]
@takuseno Thanks for youre reply.

Yes, MultiBinary action spaces work as you mentioned, i.e.,  MultiBinary(5) would be an array with 5 indices where each index value would be a binary: [0, 1, 0, 0, 1]. 

I am sorry but I didn't get this:
 _" If it's 2-dimensional binary actions, it's the exactly same as 4-dimensional flat discrete space. "_

do you mean to assign a unique action index to each combination of MultiBinary and then train? or do you mean something else, could you please explain? thanks a lot

**Comment by takuseno** [comment]
@syed881 Yes, I meant that we can convert `MultiBinary(N)` action-space into `2^N` single discrete action-space. For now, this conversion is not supported by d3rlpy. So, I'd like you to do this before making the dataset or inside an environment. Sorry for the inconvenience.

**Comment by syed881** [comment]
@takuseno Thanks for your response. 

Yeah, I will do as you said but I think it will exponentially increase the size of the action space. For example, we will have an action space of size 1024 for MultiBinary(10). 

On a side note, I found another really interesting paper which I think would a great inclusion in your library:
https://arxiv.org/pdf/2006.04678.pdf

**Comment by takuseno** [comment]
@syed881 I think that is the only way to handle MultiBinary action-space (Or, you can use it as a continuous action-space and make a threshold to take `0` or `1`). Is there any nice idea?

For the paper, looks interesting. Thanks for sharing!

**Comment by syed881** [comment]
Yeah, I think it's a good idea to convert it into continuous action space and make a threshold. I'm not really sure about other ideas. Thanks for your feedback. 

Looking forward to your implementation of PWIL.
Cheers

**Comment by takuseno** [comment]
Let me close this issue until any good ideas are proposed.
