### ISSUE TITLE
create own environment

### ISSUE THREAD

**Issue by jhcharlotte** [takuseno/d3rlpy#411]
Hello, I would like to create my own environment where the output observations, rewards, done, and received actions are all in Tensor on GPU. However, your algorithm defaults to using arrays as input and output when interacting with the environment. In between, there is a process of converting the array to Tensor and then to array. How can I eliminate this unnecessary step and directly input and output arrays. If you could reply to my question, I would greatly appreciate it

**Comment by takuseno** [comment]
@jhcharlotte Hi, thank you for the issue. As you mentioned, parallelized environments are not supported yet. To the best of knowledge, most of such environments are implemented with Jax, which requires memory copies to PyTorch anyway. I need to consider Jax support in the future.

**Comment by jh12521** [comment]
Thank you for your reply? There is another question. The environment I want to create is based on isaacgym 4, which requires the gym version to be 0.23.1. However, your code requires the gym version to be greater than 0.26.0. How can we solve this problem? If I change the reset function, step function, render function, and other functions that create my own environment to conform to the format of gym0.26.0 and later versions, can I use your code to train my environment in gym0.23.1?

**Comment by jhcharlotte** [comment]
Thank you for your reply. There is another question. The environment I want to create is based on isaacgym 4, which requires the gym version to be 0.23.1. However, your code requires the gym version to be greater than 0.26.0. How can we solve this problem? If I change the reset function, step function, render function, and other functions that create my own environment to conform to the format of gym0.26.0 and later versions, can I use your code to train my environment in gym0.23.1?

**Comment by takuseno** [comment]
Gym==v0.23.1 is very outdated and its interface is no longer compatible with most of RL projects now. Also, isaacgym seems not being actively developed anymore. What I can suggest here is to move away from isaacgym and use actively maintained environments.

**Comment by takuseno** [comment]
Let me close this issue. Feel free to reopen this if there is any further discussion.
