### ISSUE TITLE
[BUG] MDPDataset action space identifier failed

### ISSUE THREAD

**Issue by NuclearHolocaustoVengeance666** [takuseno/d3rlpy#417]
**Describe the bug**
For a discrete action space with missing values in it, the code will miscalculate the number of actions by using the maximum number of the action instead of the actual number of actions.

**To Reproduce**
1. Have a replaybuffer['action'] with unique values that are missing numbers, i.e., the unique values are [0,2,3]
2. Then the MDPDataset will miscalculate the number of actions as 4, but actually it is 3

**Expected behavior**
The number of actions should be consistent as the actual number of actions in the dataset, but not the maximum serial number of action +1

**Additional context**
I encoded the action space from strings to integers, and then some of them are filtered out. This is why the bug occurs. 
This might be happening in a lot of real-world dataset.

**Comment by takuseno** [comment]
@NuclearHolocaustoVengeance666 Hi, thank you for the issue. In d3rlpy, the discrete action ids need to be contiguous. You need to remap `[0, 2, 3]` to `[0, 1, 2]`, which should be easy and out of d3rlpy's scope. Let me close this issue.
