### ISSUE TITLE
Reduction in TD loss for ensemble Q networks

### ISSUE THREAD

**Issue by joshuaspear** [takuseno/d3rlpy#420]
@takuseno Do you have a reference for the ensemble Q network implementation, please? I noticed to calculate the TD loss during training the loss is summed - I'm wondering whether applying this aggregate loss across all networks has been tested against other mechanisms? Thanks :)

**Comment by takuseno** [comment]
@joshuaspear Thank you for the issue. Since #421 seems duplicating the same topic, let me close this one.
