### ISSUE TITLE
[REQUEST] your pip install should not overwrite existing packages

### ISSUE THREAD

**Issue by pwyq** [takuseno/d3rlpy#422]
**Is your feature request related to a problem? Please describe.**
The current `pip install d3rlpy` installs a bunch of new packages and upgrades existing packages without user's consent. This terrible auto-upgrading behaviour breaks all dependencies in my environment. It is a fucking pain in the ass to fix environment dependency issues.

**Describe the solution you'd like**
You should list the main package you use in the `README.md`, and/or gives warning to users when using the `pip install`.

**Additional context**
There is a lack of description of the dataset. For example, how is the data collected? what is the performance of the dataset (random? expert?)

**Comment by takuseno** [comment]
@pwyq Thank you for the issue. First of all, please note that d3rlpy is open source project maintained by voluntary contributors. Please keep it in your mind. 

Regarding the dependencies, I have updated `README.md` to show the list of dependencies: https://github.com/takuseno/d3rlpy?tab=readme-ov-file#dependencies

Hope this helps users to be aware of what's going to be installed/upgraded when they install d3rlpy.

Regarding the datasets, d3rlpy only provides datasets for CartPole and Pendulum, but other datasets are provided through external sources:
- D4RL: https://github.com/Farama-Foundation/D4RL
- Atari 2600: https://github.com/takuseno/d4rl-atari
- Minari: https://github.com/Farama-Foundation/Minari

Please check details in their repositories or papers.

**Comment by takuseno** [comment]
Please let me close this issue. If there is any further discussion, feel free to reopen this.
