### ISSUE TITLE
[BUG] Batch inference deviates from single state inference

### ISSUE THREAD

**Issue by jdesman1** [takuseno/d3rlpy#434]
**Describe the bug**
Thanks @takuseno for creating such a great tool for offline RL. However, recently I have encountered an issue where running batch inference produces difference results from inference on single states. i.e.:

Let `ep.observations` = `states` be a (100, 10) (observation, state dimension) array:
```
batch_infer = model.predict(ep.observations)
list_infer = [model.predict(np.expand_dims(s, axis=0))[0] for s in ep.observations)
```
`batch_infer` and `list_infer` produce different results across a number of models I have tested. 

See reproduction code below. This issue emerged while we were running inference on a proprietary dataset where there is appreciable and meaningful difference when running inference on every state versus batch inference. I cannot provide this dataset, but please see below for a minimal example illustrating unexpected differences when running batch vs single state inference.

**To Reproduce**
```
import numpy as np
from d3rlpy.datasets import get_pendulum
from d3rlpy.algos import CQLConfig

# Setup
dataset, env = get_pendulum()
model = CQLConfig().create()
model.build_with_dataset(dataset)
model.fit(
    dataset,
    n_steps=100,
    n_steps_per_epoch=10
)

# Use only a single episode for reproducibility
ep = dataset.episodes[0]

# Infer actions
batch_infer = model.predict(ep.observations)
list_infer = [model.predict(np.expand_dims(s, axis=0))[0] for s in ep.observations]
batch_infer = np.array(batch_infer)
list_infer = np.array(list_infer)
diff = batch_infer - list_infer
print(diff)            ### Produces non-zero values! ###

# Infer values
batch_infer = model.predict_value(ep.observations, ep.actions)
list_infer = [model.predict_value(np.expand_dims(s, axis=0), np.expand_dims(a, axis=0))[0]
              for s, a in zip(ep.observations, ep.actions)]
batch_infer = np.array(batch_infer)
list_infer = np.array(list_infer)
diff = batch_infer - list_infer
print(diff)            ### Produces non-zero values! ###
```

**Expected behavior**
`diff` should be 0.

**Additional context**
In the tutorials section of the documentation, we see single state inference: [tutorial](https://d3rlpy.readthedocs.io/en/stable/tutorials/getting_started.html)

However in the algorithm section, batch inference seems to be supported: [interface documentation](https://d3rlpy.readthedocs.io/en/stable/references/algos.html#d3rlpy.algos.QLearningAlgoBase.predict)

**Comment by takuseno** [comment]
Sorry for the late response. I have tried this locally and could reproduce the issue. I believe that this is simply a precision error because the difference is very small (<1e-6). This could happen when the order of computation (e.g. all at once vs one-by-one) is changed. If the error is significantly large, such as the difference is larger than 1e-5, please let me know. Otherwise, this is an inevitable error.
