### ISSUE TITLE
[BUG] unintuitive numbering for saved models

### ISSUE THREAD

**Issue by pstansell** [takuseno/d3rlpy#44]
Hello @takuseno,

This is not really a bug, but slightly unexpected behaviour that can lead to wasted run time if one is not careful.

In the `fit` method for offline learning, if, for example, one specifies
```python
fit(dataset, n_epochs = 1000, save_interval = 500)
```
I think the expectation is that the models from the 500th and the final, 1000th, epochs would be saved, however, the models that are saved are
```
model_0.pt
model_500.pt
```
This means the second half of the run is wasted (and there is not much use in saving `model_0.pt` which has hardly been trained).  Obviously, this is because the 1000th epoch is labelled with 999 because of the counting from zero, and models are saved when `epoch % save_interval == 0`.

Would it be possible to add 1 to the epoch number when the models are saved so that at the end of the first epoch the model is called `model_1.pt` instead of `model_0.pt`.  Something like the following, maybe, in `d3rlpy/base.py`:
```python
# save model parameters
if epoch + 1 % save_interval == 0:
    logger.save_model(epoch + 1, self)
```

Then the `fit` method specified above would save the following models (which seems more intuitive to me):
```
model_500.pt
model_1000.pt
```

**Comment by takuseno** [comment]
@pstansell Hello, thanks for reporting this issue! Yeah, this is definitely a bug. I'll fix this. I appreciate your continuous contributions!

**Comment by takuseno** [comment]
@pstansell Hi! I've fixed this in the last commit.
https://github.com/takuseno/d3rlpy/commit/a091aeadcc413bd6aad45e1e24296d985e7b99d7

**Comment by pstansell** [comment]
Thanks very much.
