### ISSUE TITLE
Port encoders.py and torch_utility.py to Cython

### ISSUE THREAD

**Issue by DanielDowns** [takuseno/d3rlpy#46]
**Describe the solution you'd like**

A cProfile scan of a AWAC experiment I'm running suggests that models/torch/encoders.py consumes ~16% of the run time and torch_utility.py consumes ~10% of the total run time. Both have many calls to the same function and each call is running comparatively slow. Porting them to Cython would offer a significant speed up.

total run time: 2.213e+04

ncalls       | tottime | percall       | cumtime | percall     | filename:lineno(function)

11999990 | 266.3 | 2.219e-05 | 3643 | 0.0003036 | encoders.py:217(_fc_encode)
3999997 | 247 | 6.176e-05 | 1082 | 0.0002704 | policies.py:13(squash_action)
1999998 | 620.9 | 0.0003104 | 2011 | 0.001006 | torch_utility.py:14(soft_sync)

**Comment by takuseno** [comment]
@DanielDowns Thank you for reporting this issue! This is very insightful information! It might be difficult to directly port things to Cython since those files are doing PyTorch operations. But, it's definitely worth looking for a way to speed things up there. I'll update this when something is improved. Thank you!

**Comment by DanielDowns** [comment]
Yeah, Pytorch in general is one of the slower parts of your codebase. You did a good job, there weren't many spots that could be improved. However, I'm trying to eke out as much speed up as I can to try and get good results so I wanted to pass on my findings. Do you have a rough plan on when you might try and improve it (a week, a month, a year)?

**Comment by takuseno** [comment]
@DanielDowns Thanks. Any information would be great! I'll work on this today and for a week.

**Comment by takuseno** [comment]
So far, I did not see any room for Cythonization in algorithms. Instead, I'm planning to support JIT compilation. Please let me close this issue for now.
