### ISSUE TITLE
[REQUEST] additional parameters written to params.json

### ISSUE THREAD

**Issue by pstansell** [takuseno/d3rlpy#47]
Hello @takuseno,

I really like the fact that d3rlpy writes a record of the run parameters to the `params.json` file, and to the screen when `verbose=True`.

However, it seems that the following two encoder parameters are missing:

- `hidden_units`
- `use_dense`

Maybe there is a specific reason why you don't include these parameters, but if not, please could we have these parameters included in `params.json` and the screen output for each encoder.

**Comment by takuseno** [comment]
@pstansell Hello, thanks for reporting issue! d3rlpy saves all information to `params.json` in order to reconstruct the object only from the file. Which encoder are you using? By default, it uses `DefaultEncoderFactory`.
https://d3rlpy.readthedocs.io/en/v0.61/references/generated/d3rlpy.models.encoders.DefaultEncoderFactory.html#d3rlpy.models.encoders.DefaultEncoderFactory
If you use `VectorEncoderFactory`, those variables should be saved.

**Comment by pstansell** [comment]
Hello @takuseno, maybe the problem is that the output in `params.json` says that the value of the `encoder type` is `default` but it doesn't say what `default` is exactly, even though other default values are saved explicitly.

For example, if I run
```python
import gym
from d3rlpy.algos import SAC
from d3rlpy.online.buffers import ReplayBuffer

env = gym.make('Pendulum-v0')
sac = SAC()
buffer = ReplayBuffer(maxlen = 1000, env = env)
sac.fit_online(env, buffer)
``` 
the encoder output in `params.json` is
```python
actor_encoder_factory={'type': 'default', 'params': {'activation': 'relu', 'use_batch_norm': False}}
critic_encoder_factory={'type': 'default', 'params': {'activation': 'relu', 'use_batch_norm': False}}
```
It doesn't explicitly record the values of `hidden_units` or `use_dense`

**Comment by takuseno** [comment]
`DefaultEncoderFactory` creates the encoder models depending on the given observation shape. Currently, it's hard to add that information since this process is done after saving `params.json`. But, the `DefaultFactoryEncoder` always creates `[256, 256]` linear layers for vector observation and Nature-DQN CNN encoder for pixel observation. Sorry for the inconvenience...

**Comment by pstansell** [comment]
I did try to make the change myself before I raised the issue, but I didn't manage it.

Correct me if I'm wrong, but isn't it the case that the following are set before `params.json` is printed

-   `self._hidden_units = [256, 256]`
-   `self._use_dense = use_dense`

They seem to be set in `__init__` of class `VectorEncoderFactory` in`d3rlpy/models/encoders.py`.  Shouldn't that mean that their values are available to record when `params.json` is written?

**Comment by takuseno** [comment]
If you don't specify any encoders, this will be used.
https://github.com/takuseno/d3rlpy/blob/1bb5a3f40976e17987d3da12681adf7726bd6d56/d3rlpy/models/encoders.py#L236
It does not have an access to those values until creating encoders.

**Comment by pstansell** [comment]
I'm sorry to persist with this point, but the values are known at the time the `params.json` file is written, therefore surely the values could be written to that file.

I performed the trivial test of adding print statements on this line
https://github.com/takuseno/d3rlpy/blob/1bb5a3f40976e17987d3da12681adf7726bd6d56/d3rlpy/models/encoders.py#L194

I could print out the values of the above variables before `params.json` was written.

Also, if I set custom encoder values, as in this example,
```python
import gym
from d3rlpy.algos import SAC
from d3rlpy.online.buffers import ReplayBuffer
from d3rlpy.models.encoders import VectorEncoderFactory

env = gym.make('Pendulum-v0')

actor = VectorEncoderFactory(hidden_units=[64, 64], activation='tanh')
critic = VectorEncoderFactory(hidden_units=[32, 32], activation='relu')

sac = SAC(actor_encoder_factory = actor, critic_encoder_factory = critic)

buffer = ReplayBuffer(maxlen = 1000, env = env)

sac.fit_online(env, buffer, tensorboard = False)
```

the custom values are written to the `params.json`, that is, it contains
```
"actor_encoder_factory": {
  "type": "vector",
  "params": {
    "hidden_units": [
      64,
      64
    ],
    "activation": "tanh",
    "use_batch_norm": false,
    "use_dense": false
  }
}
"critic_encoder_factory": {
  "type": "vector",
  "params": {
    "hidden_units": [
      32,
      32
    ],
    "activation": "relu",
    "use_batch_norm": false,
    "use_dense": false
  }
}
```
Given that custom values are written to the `params.json` file, I'm afraid that I don't understand why the default values can't be written if no custom values are set.

**Comment by takuseno** [comment]
The result of `get_params` method will be written to `params.json`. For `DefaultEncoderFactory` only has `activation` and `use_batch_norm` values.
https://github.com/takuseno/d3rlpy/blob/76d52753a9a43d30f9613cf6c61185432aa98b5c/d3rlpy/models/encoders.py#L286

If you specify `vector`, all the information will be written.
https://github.com/takuseno/d3rlpy/blob/76d52753a9a43d30f9613cf6c61185432aa98b5c/d3rlpy/models/encoders.py#L222

**Comment by pstansell** [comment]
Thanks for your patience with me.  I have to admit that I don't fully understand the python, but if all that is required for the network parameters to be written to `params.json` is to specify them as custom settings in the code (as in my example above) then I'm happy with that solution.
