### ISSUE TITLE
[REQUEST] Add additional info for MDPDatSetd

### ISSUE THREAD

**Issue by jamartinh** [takuseno/d3rlpy#48]
Hi, it would be very useful to have additional info dict into the MDPDataset.

I think It can be implemented at two levels:

1.  Additional info as "INFO" dict per "row" where user can add any other relevant measures such as "second reward", "risk" etc, of course this can be incorporated to observations but this will break the meaning of observations and could make the dataset non usable for the learning API.
2. Additional "METADATA " dict at Dataset Level, in here one can specify things such as "Observation column names", "action var names", suggested "action scaling" etc

**Comment by takuseno** [comment]
@jamartinh Hello! Thanks for the request! I agree that the additional features might be useful. I'll add it soon.

**Comment by takuseno** [comment]
Let me close this issue since the latest d3rlpy has the significant change from v1.
