### ISSUE TITLE
[PROPOSAL] Stable-Baselines3 Wrappers

### ISSUE THREAD

**Issue by araffin** [takuseno/d3rlpy#5]
Hello,

Would you be interested in wrappers/convert scripts to make this repo works with [Stable-Baselines3 (SB3)](https://github.com/DLR-RM/stable-baselines3)?

The thing is that d3rlpy API is quite nice, close to SB3 one and the offline algorithms in d3rlpy complements the one available in SB3.
We could also add a section in our documentation explaining how to use d3rlpy with SB3 ;)

The idea would be to have different wrappers:
- one that adds the `learn()` method to continue training after pretraining with offline data and that makes the `predict()` method,match the SB3 signature (it returns actions and hidden states in the case of LSTM policies instead of just states)
this would allow to integrate d3rlpy to the [rl-zoo](https://github.com/DLR-RM/rl-baselines3-zoo)
- one that convert d3rlpy dataset to SB3 replay buffer or the otherway around

and maybe a wrapper to load pre-trained policies from d3rlpy into SB3 models.

Later other wrappers would be to convert SB3 models to use d3rlpy api (that would give you access to all algorithms from SB3).

**Comment by araffin** [comment]
To give a concrete example, training with SB3 SAC/DQN, then using offline model with d3rlpy and then using `evaluate_policy` helper from sb3.

Convert helpers:
```python
import gym
from stable_baselines3.common.buffers import ReplayBuffer

from d3rlpy.dataset import MDPDataset


def to_mdp_dataset(replay_buffer: ReplayBuffer) -> MDPDataset:
    pos = replay_buffer.size()
    return MDPDataset(observations=replay_buffer.observations[:pos, 0],
                      actions=replay_buffer.actions[:pos, 0],
                      rewards=replay_buffer.rewards[:pos, 0],
                      terminals=replay_buffer.dones[:pos, 0],
                      discrete_action=isinstance(replay_buffer.action_space,
                                                 gym.spaces.Discrete))


def to_sb3_predict(d3rlpy_model):
    d3rlpy_model._predict = d3rlpy_model.predict
    # patch predict
    def sb3_predict(observation, state=None, mask=None, deterministic=True):
        if deterministic:
            return d3rlpy_model._predict(observation), None
        return d3rlpy_model.sample_action(observation), None
    d3rlpy_model.predict = sb3_predict
    return d3rlpy_model
```

tests:
```python
import pytest
import pybullet_envs
from stable_baselines3 import DQN, SAC
from stable_baselines3.common.evaluation import evaluate_policy

from d3rlpy.algos import AWR, DiscreteAWR
from d3rlpy.sb3.convert import to_mdp_dataset, to_sb3_predict


@pytest.mark.parametrize("algo_env", [(SAC, "Pendulum-v0"),
                                      (SAC, "HopperBulletEnv-v0"),
                                      (DQN, "CartPole-v1")])
def test_to_mdp_dataset(algo_env):
    algo, env = algo_env
    model = algo("MlpPolicy",
                 env,
                 policy_kwargs=dict(net_arch=[64]),
                 learning_starts=2500)
    model.learn(2500)

    dataset = to_mdp_dataset(model.replay_buffer)

    if env == "CartPole-v1":
        offline_class = DiscreteAWR
    else:
        offline_class = AWR
    offline_model = offline_class(n_epochs=2)
    offline_model.fit(dataset.episodes)

    offline_model = to_sb3_predict(offline_model)

    evaluate_policy(offline_model, model.get_env())


```

**Comment by takuseno** [comment]
@araffin Hello! Thank you for your amazing proposal! I'm actually interested in increasing compatibilites with more projects. I'll start making `learn` interface which seems to be also useful for this project. I'll update this later!

**Comment by araffin** [comment]
Update: a more elegant solution for the `predict()`:

```python
class SB3Wrapper(object):
    def __init__(self, d3rlpy_model):
        super(SB3Wrapper, self).__init__()
        # Avoid infinite recursion due to override of setattr
        self.__dict__["model"] = d3rlpy_model

    def predict(self, observation, state=None, mask=None, deterministic=True):
        if deterministic:
            return self.model.predict(observation), None
        return self.model.sample_action(observation), None

    def __getattr__(self, attr):
        if attr in self.__dict__:
            return getattr(self, attr)
        return getattr(self.model, attr)

    def __setattr__(self, attr_name, value):
        if attr_name != "model":
            self.model.__setattr__(attr_name, value)
        else:
            self.__dict__["model"] = value
```
that way, you can do:

```python
offline_model = AWR(n_epochs=1)
offline_model.fit(dataset.episodes)

wrapped_model = SB3Wrapper(offline_model)
# Use SB3 predict method
evaluate_policy(wrapped_model, env)

# Call methods from the wrapped model
wrapped_model.sample_action(obs)
wrapped_model.fit(dataset.episodes)

# Set attributes
wrapped_model.n_epochs = 2
assert wrapped_model.model.n_epochs == 2
```

**Comment by takuseno** [comment]
@araffin Hello. Sorry for being late for this. I've made a branch to make the wrapper you proposed. Please check it up.
https://github.com/takuseno/d3rlpy/compare/sb3?expand=1

**Comment by araffin** [comment]
> I've made a branch to make the wrapper you proposed. 

Good to hear =)
Can you create a PR, so it would be easier to me to review ;) (but for now, LGTM)

After that, I will try to make a PR in the future to add more features (so you can continue training for instance after pretraining with offline RL).
Btw, would you be interested afterward to create a PR to the SB3 repo to add a page about your repo?
We did that for the [imitation](https://stable-baselines3.readthedocs.io/en/master/guide/imitation.html) library for instance.

**Comment by takuseno** [comment]
@araffin Hello. Please check this PR:)
https://github.com/takuseno/d3rlpy/pull/15

> Btw, would you be interested afterward to create a PR to the SB3 repo to add a page about your repo?
We did that for the imitation library for instance.

Sounds great! I'm definitely interested! It'd be great if you let me know more about this!

**Comment by araffin** [comment]
>Sounds great! I'm definitely interested! It'd be great if you let me know more about this!

Good to hear =)
So, as mentioned in my message, we focus on model-free online RL, and rely on other projects for additional features.
This is the case for instance for imitation learning.
The idea is to have a page in the documentation that explain the aim of the project (here, what is offline RL and what algorithms are implemented in d3rlpy), how to quickly use the lib (so the example in the readme should be enough) and here in addition, how to use the SB3 wrapper with your lib.

I already started integrated your repo in the zoo ;)
The branch can be found here: https://github.com/DLR-RM/rl-baselines3-zoo/tree/feat/offline-RL

**Comment by takuseno** [comment]
@araffin Okay, then. I'll pr for the documentation:)
And, great to hear you're working with my d3rlpy. If you have anything you need to ask, feel free to contact me!
