### ISSUE TITLE
[BUG] q_func_type  vs. q_func_factory

### ISSUE THREAD

**Issue by jamartinh** [takuseno/d3rlpy#52]
Hi @takuseno It seems that in some moment the API changed between using parameter "q_func_type" to using "q_func_factory"

If this is so, the algorithms that use q_func_type are using then the default "mean" ?

If so, then all examples and doc should be updated with the right name "q_func_factory" ?

Best,
Jose

**Comment by takuseno** [comment]
@jamartinh Thanks for bringing this up! Yes, you're right. `q_func_type` was changed to `q_func_factory` at some point. There may be old examples and docs that don't catch up with this change. I'll check the ones, and I'll also appreciate if you point it out or make PR:)

**Comment by jamartinh** [comment]
PR done 
[pool request ](https://github.com/takuseno/d3rlpy/issues?q=is%3Apr+is%3Aopen+author%3Ajamartinh)

**Comment by takuseno** [comment]
@jamartinh Thank you for your contribution! Let me close this issue.
