### ISSUE TITLE
[REQUEST] Add algorithm, Critic Regularized Regression

### ISSUE THREAD

**Issue by toy101** [takuseno/d3rlpy#54]
Thank you for creating the great repository. 
It is helping me to study reinforcement learning.

if you would not mind, could you implement an offline reinforcement learning algorithm called Critic Regularized Regression (CRR)?
This URL is the paper on the algorithm.
https://arxiv.org/abs/2006.15134

I appreciate this great repository.

**Comment by takuseno** [comment]
@toy101 Thanks for your request! I'll support this method since the CRR is one of the method that frequently appears in recent papers. I believe this will be available in the next release.

**Comment by toy101** [comment]
Thank you very much!!
I look forward to releasing the next version!

**Comment by takuseno** [comment]
@toy101 Hello, I've made up a draft CRR implementation.
https://github.com/takuseno/d3rlpy/commit/696a9bc66883f1ced20a26c050e23adcf44dd787

I'll keep working on [crr](https://github.com/takuseno/d3rlpy/commits/crr) branch since there are still some missing features such as CWP.

**Comment by takuseno** [comment]
@toy101 Hello! CRR is now available in the master branch.
https://github.com/takuseno/d3rlpy/blob/master/d3rlpy/algos/crr.py

Unlike the original paper, d3rlpy does not currently support categorial distributional Q function whereas d3rlpy supports other distributional Q functions such as Quantile Regression. The categorical distributional Q function will be supported later.

**Comment by toy101** [comment]
Thank you!
I'll try to get it running right away!

Thank you so much for implementing this!
