### ISSUE TITLE
[REQUEST] support multiple evaluation datasets

### ISSUE THREAD

**Issue by navidmdn** [takuseno/d3rlpy#55]
While training an offline RL agent, I need to monitor evaluation metrics on both training and evaluation datasets in order to early stop my training process. I think a general approach is supporting a list of evaluation datasets like many other platforms. Please let me know if there is any other way I can do this.

**Comment by takuseno** [comment]
@navidmdn Thank you for your request! Comparing metrics between training and test datasets sounds nice. Currently, evaluating the policy with the environment is also represented as a scikit-learn scorer function, which makes this difficult. So I'm currently planning to redesign this evaluation scheme to implement your idea. I'll update this issue when I made any changes relevant to this topic.

**Comment by jamartinh** [comment]
@navidmdn by now until new feature arrives you can use a trick.
Create two fitter objects:
```python

    fitter1 = algo.fitter(
    dataset = train_episodes,    
    eval_episodes = test_episodes,
    ...
   )
```
```python
    fitter2 = algo.fitter(
    dataset = train_episodes,    
    eval_episodes = train_episodes,
    ...
)
```
And then train with the for loop for both fitters one after another (until we can do it parallel or async)

```python
df_metrics = None
df_metrics2 = None

for (epoch, metrics),(epoch2,metrics2) in zip(fitter,fitter2):
    
    if df_metrics is None:
        df_metrics = pd.DataFrame.from_records([metrics])
        df_metrics2 = pd.DataFrame.from_records([metrics2])       
    else:
        df_metrics = df_metrics.append([metrics]).reset_index(drop=True)
        df_metrics2 = df_metrics2.append([metrics2]).reset_index(drop=True)        
    
    clear_output(wait=True)    
    df_metrics.plot(subplots=True, figsize=(30, 20),layout=(15,1))
    df_metrics2.plot(subplots=True, figsize=(30, 20),layout=(15,1))    
    plt.show()    
    algo.save_policy(network_file_name)
    # if metrics_diverge(df_metrics,df_metrics2):
    #     break
```

You will have a lag of +1 epoch for the metrics of training set but at least you can see the trend

**Comment by navidmdn** [comment]
Great! thanks!
