### ISSUE TITLE
[BUG] Unbounded action (CRR)

### ISSUE THREAD

**Issue by araffin** [takuseno/d3rlpy#57]
**Describe the bug**
When trying to use CRR `predict()` with an env which has a normalized action space (low=-1, high=1), CRR outputs actions outside that range.

Also related, the implementation of "NormalPolicy" is a bit weird to me, as it is a "squashed" normal, no? (as in SAC)
https://github.com/takuseno/d3rlpy/blob/7d983f99d6fc8c9d3b32721792ec7a176a5b36e1/d3rlpy/models/torch/policies.py#L126

I can produce a minimal working example if needed ;)

**Expected behavior**
The actions outputted should be in a valid range specified by the environment.

**Additional context**
Using master version of the library.

(I'm currently working with the SB3 wrapper and it works fine for behavior cloning)

**Comment by takuseno** [comment]
@araffin Thanks for reporting this issue! Good catch! This should be fixed in the latest commit.
https://github.com/takuseno/d3rlpy/commit/3d2c6c40d6f6381205bd11a1addd30c0510b10e7

Basically, in d3rlpy, every policy with gaussian distribution is implemented as the squashed policy same as SAC uses.

**Comment by araffin** [comment]
thanks for the quick fix =)

>Basically, in d3rlpy, every policy with gaussian distribution is implemented as the squashed policy same as SAC uses.

alright, is it documented? (I think it is an important detail, same for state-independent or not variance)

**Comment by takuseno** [comment]
Actually, the internal parts are not documented yet since the documentation is only ready for library users, not for developers... But, I agree that those should be documented at some point...
