### ISSUE TITLE
[REQUEST] Allow to disable logging

### ISSUE THREAD

**Issue by araffin** [takuseno/d3rlpy#6]
**Is your feature request related to a problem? Please describe.**
Currently logging is enabled by default and it creates folders with the logs of each run inside.

**Describe the solution you'd like**
It would be nice to be able to deactivate that logging (as it is possible for tensorboard only for now: https://d3rlpy.readthedocs.io/en/v0.23/references/logging.html)

**Comment by takuseno** [comment]
thanks for the request! i'll definitely make this feature in this week!

**Comment by takuseno** [comment]
@araffin Hello. I've added `save_metrics` flag to disable all loggings.

https://github.com/takuseno/d3rlpy/commit/2fec466107309f7584e610158e2bcb60dc3635b2

This will be included in the next release.

**Comment by araffin** [comment]
Thanks =)

**Comment by araffin** [comment]
Is there a way to deactivate the creation of the `runs/` folder, too?
