### ISSUE TITLE
[BUG] unused parameter 'kernel_type' when reproducing BEAR results

### ISSUE THREAD

**Issue by ShenQianli** [takuseno/d3rlpy#65]
**Describe the bug**
I tried to reproduce the results published in `Kumar et al., Stabilizing Off-Policy Q-Learning via Bootstrapping Error Reduction. <https://arxiv.org/abs/1906.00949>` by running the script located in `reproductions/offline/bear.py`. I guess in line 29 you made a slight mistake as the parameter name is expected to be **mmd_kernel** according to _d3rlpy/algos/bear.py_ rather than **kernel_type**. It results in blindly choosing _laplacian kernel_ for all environments including _halfcheetah_, while according to the original paper, _gaussian kernel_ is a better choice for _halfcheetah_.

**To Reproduce**
`python reproductions/offline/bear.py --dataset halfcheetah-medium-v2`
Then the logger will report a warning for the unused parameter 'kernel_type'. And I checked _params.json_ and found that _laplacian kernel_ was chosen as it is the default option.

I also tried to modify `reproductions/offline/bear.py` by replacing 'kernel_type' with 'mmd_kernel' and the warning was silenced. For _halfcheetah-medium-v2_, there is a ~1k performance gap between two kernel choices (gaussian ~6000, laplacian ~5000, average results with random seeds [1,2,3]).

**Expected behavior**
_gaussian kernel_ for halfcheetah and _laplacian kernel_ for the rest.

**Additional context**
Thanks for your amazing and powerful toolkits! Wish you guys all the best :)

**Comment by takuseno** [comment]
@ShenQianli Thanks for reporting this issue! You're totally right. As you mentioned, `kernel_type` should be `mmd_kernel`. I'll fix this soon.

**Comment by takuseno** [comment]
@ShenQianli It's fixed here. https://github.com/takuseno/d3rlpy/commit/59423f7284895bea9783b3a7acfc428d9d7f9d02

**Comment by ShenQianli** [comment]
Cool! Thanks for your timely update!
