### ISSUE TITLE
[BUG] IndexError: list index out of range

### ISSUE THREAD

**Issue by Homura2333** [takuseno/d3rlpy#67]
**Describe the bug**
I copied the codes from this page in the tutorial: [https://d3rlpy.readthedocs.io/en/v0.80/references/dataset.html]()
And I think my codes are exactly the same with those on that page, except for one line of code to import numpy.
The codes are about how to build a MDPDataset. 
It has **a probability** of reporting the following error:

```
Traceback (most recent call last):
  File "D:/Codes/Python/RL_test/diy_dataset.py", line 20, in <module>
    episode[0].observation
  File "d3rlpy\dataset.pyx", line 799, in d3rlpy.dataset.Episode.__getitem__
IndexError: list index out of range
```

It seems that if there is no transaction in the auto divided episode, the error will occur. At such time, I use len(epidose) and the output is 0. Is it the problem of the episode auto splitting?

**To Reproduce**
Run the codes for several times

**Expected behavior**
There should be no errors

**Additional context**
My python version is 3.8 and my d3rlpy version is 0.80.

**Comment by takuseno** [comment]
@Homura2333 Thanks for reporting this issue! Yes, you're right. The problem is that there is an episode without any steps. Practically, this is not a bug. But, I need to update the document.
