### ISSUE TITLE
Question: Loading Dataset from model

### ISSUE THREAD

**Issue by hougiebear** [takuseno/d3rlpy#71]
Hey Takuma

Quick question. I'm trying to run DiscreteCQL on saved DQN model. I've successfully trained the model however I didn't save the replay buffer. I can just simply re-run start to finish but to save time I'd like to take the existing pth model and convert to static dataset if possible? Is there a way to extract the buffer and policy from the saved model and convert it to a dataset? The environment is custom and works with d3rply.DQN fine.

```
algo = DQN.from_json(path_to_output + 'params.json')
#algo.build_with_env(env)
algo.load_model(path_to_output + 'model_200000.pt') #at snapshot 200k
dataset = to_mdp_dataset(algo.replay_buffer)
train_episodes, test_episodes = train_test_split(dataset, test_size=0.2)

cql = DiscreteCQL()
cql.fit(train_episodes,
            eval_episodes=test_episodes)

cql.save_model(exp_name)
```

I get an error

`AttributeError: 'DQN' object has no attribute 'replay_buffer'`

I've tested already end to end with online first and it works as I did manage to export replay buffer as MDPDataset using the buffer.to_mdp_dataset() and saved the model as h5 then load it

**Comment by takuseno** [comment]
Hello @hougiebear . Thanks for reporting this issue! Unfortunately, the replay buffer is not saved as snopshots during training. So you need to explicitly save it after training.
```py
import d3rlpy
import gym

env = gym.make('CartPole-v0')
dqn = d3rlpy.algos.DQN()
replay_buffer = d3rlpy.online.buffers.ReplayBuffer(100000, env=env)

dqn.fit_online(env, replay_buffer, n_steps=100000)

# convert to MDPDataset
dataset = replay_buffer.to_mdp_dataset()
# save as HDF5
dataset.dump('dataset.h5')
```

Then, you can load it when it's necessary.
```py
import d3rlpy

# load the saved dataset
dataset = d3rlpy.dataset.MDPDataset.load('dataset.h5')

cql = DiscreteCQL()
cql.fit(dataset)
```

**Comment by hougiebear** [comment]
Thanks for confirming. Yep that is what I am doing now. First set of experiments I never saved the replay buffer.
Just a question also on the SB3 wrapper

"
model = sb3.SAC("MlpPolicy", "Pendulum-v0", learning_rate=1e-3, verbose=1)
model.learn(6000)

# Convert to d3rlpy MDPDataset
dataset = to_mdp_dataset(model.replay_buffer)
"
That works in the same python session, however I assume it is not feasible to load the model.zip (SB3 stored on disk) from a previous session and convert to d3rply? It should be in the same session?
