### ISSUE TITLE
[REQUEST] Support For Online Evaluation

### ISSUE THREAD

**Issue by IanWangg** [takuseno/d3rlpy#75]
After I finish training the agent using datasets, how do I evaluate them online properly?

**Comment by takuseno** [comment]
@IanWangg Thanks for the issue! Here is an example of online evaluation during training.
```py
import d3rlpy

dataest, env = d3rlpy.datasets.get_pendulum()

cql = d3rlpy.algos.CQL()

cql.fit(dataset, eval_episodes=dataset, scorers={'environment': d3rlpy.metrics.evaluate_on_environment(env)})
```

If you want to execute the learned policy after training, you can do this as follows:
```py
mean_episode_returns = evaluate_on_environment(env)(cql)
```

**Comment by IanWangg** [comment]
> @IanWangg Thanks for the issue! Here is an example of online evaluation during training.
> 
> ```python
> import d3rlpy
> 
> dataest, env = d3rlpy.datasets.get_pendulum()
> 
> cql = d3rlpy.algos.CQL()
> 
> cql.fit(dataset, eval_episodes=dataset, scorers={'environment': d3rlpy.metrics.evaluate_on_environment(env)})
> ```
> 
> If you want to execute the learned policy after training, you can do this as follows:
> 
> ```python
> mean_episode_returns = d3rlpy.metrics.evaluate_on_environment(env)(cql)
> ```

**Comment by IanWangg** [comment]
> > @IanWangg Thanks for the issue! Here is an example of online evaluation during training.
> > ```python
> > import d3rlpy
> > 
> > dataest, env = d3rlpy.datasets.get_pendulum()
> > 
> > cql = d3rlpy.algos.CQL()
> > 
> > cql.fit(dataset, eval_episodes=dataset, scorers={'environment': d3rlpy.metrics.evaluate_on_environment(env)})
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you want to execute the learned policy after training, you can do this as follows:
> > ```python
> > mean_episode_returns = d3rlpy.metrics.evaluate_on_environment(env)(cql)
> > ```

Got it! Thank you so much for replying!
