### ISSUE TITLE
using Critic Reguralized Regression (CRR) to predict actions

### ISSUE THREAD

**Issue by icomeaman** [takuseno/d3rlpy#78]
**Describe the bug**
hello:
I have trained a model using crr. when I try to predict actions like other mothodes(they dont have problem,everything is same ,except chage the methode) :

from d3rlpy.algos import CRR
crr = CRR.from_json('params.json')
crr.load_model('model_100.pt')
action = crr.predict([observations])[0]

There is a problem:

**To Reproduce**
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-9-d98aa9c82752> in <module>
----> 1 action = cql.predict([observations])[0]

~/.env/venv_new/lib/python3.8/site-packages/d3rlpy/algos/base.py in predict(self, x)
    120         """
    121         assert self._impl is not None, IMPL_NOT_INITIALIZED_ERROR
--> 122         return self._impl.predict_best_action(x)
    123 
    124     def predict_value(

~/.env/venv_new/lib/python3.8/site-packages/d3rlpy/torch_utility.py in wrapper(self, *args, **kwargs)
    286     def wrapper(self: Any, *args: Any, **kwargs: Any) -> np.ndarray:
    287         set_eval_mode(self)
--> 288         return f(self, *args, **kwargs)
    289 
    290     return wrapper

~/.env/venv_new/lib/python3.8/site-packages/d3rlpy/torch_utility.py in wrapper(self, *args, **kwargs)
    276 
    277                 tensors.append(tensor)
--> 278             return f(self, *tensors, **kwargs)
    279 
    280         return wrapper

~/.env/venv_new/lib/python3.8/site-packages/d3rlpy/algos/torch/base.py in predict_best_action(self, x)
     45     def predict_best_action(self, x: torch.Tensor) -> np.ndarray:
     46         with torch.no_grad():
---> 47             action = self._predict_best_action(x)
     48 
     49             # transform action back to the original range

~/.env/venv_new/lib/python3.8/site-packages/d3rlpy/algos/torch/crr_impl.py in _predict_best_action(self, x)
    175 
    176         # (batch_size * N, 1)
--> 177         flat_values = self._q_func(flat_obs_t, flat_actions)
    178         # (batch_size * N, 1) -> (batch_size, N)
    179         reshaped_values = flat_values.view(x.shape[0], -1)

~/.env/venv_new/lib/python3.8/site-packages/d3rlpy/models/torch/q_functions.py in __call__(self, x, action, reduction)
   1023         self, x: torch.Tensor, action: torch.Tensor, reduction: str = "mean"
   1024     ) -> torch.Tensor:
-> 1025         return cast(torch.Tensor, super().__call__(x, action, reduction))
   1026 
   1027     def compute_target(

~/.env/venv_new/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

~/.env/venv_new/lib/python3.8/site-packages/d3rlpy/models/torch/q_functions.py in forward(self, x, action, reduction)
   1017         values = []
   1018         for q_func in self._q_funcs:
-> 1019             values.append(q_func(x, action).view(1, x.shape[0], 1))
   1020         return _reduce_ensemble(torch.cat(values, dim=0), reduction)
   1021 

~/.env/venv_new/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

~/.env/venv_new/lib/python3.8/site-packages/d3rlpy/models/torch/q_functions.py in forward(self, x, action)
    168 
    169     def forward(self, x: torch.Tensor, action: torch.Tensor) -> torch.Tensor:
--> 170         return cast(torch.Tensor, self._fc(self._encoder(x, action)))
    171 
    172     def compute_error(

~/.env/venv_new/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    887             result = self._slow_forward(*input, **kwargs)
    888         else:
--> 889             result = self.forward(*input, **kwargs)
    890         for hook in itertools.chain(
    891                 _global_forward_hooks.values(),

~/.env/venv_new/lib/python3.8/site-packages/d3rlpy/models/torch/encoders.py in forward(self, x, action)
    400                 action.view(-1).long(), num_classes=self.action_size
    401             ).float()
--> 402         x = torch.cat([x, action], dim=1)
    403         h = self._fc_encode(x)
    404         if self._use_batch_norm:

RuntimeError: Tensors must have same number of dimensions: got 3 and 2

**Expected behavior**

**Additional context**

**Comment by takuseno** [comment]
@icomeaman Thanks for the issue! Could you share `params.json` to reproduce the error on my side?

**Comment by icomeaman** [comment]
{
  "action_scaler": null,
  "actor_encoder_factory": {
    "type": "default",
    "params": {
      "activation": "relu",
      "use_batch_norm": false,
      "dropout_rate": null
    }
  },
  "actor_learning_rate": 0.0003,
  "actor_optim_factory": {
    "optim_cls": "Adam",
    "betas": [
      0.9,
      0.999
    ],
    "eps": 1e-08,
    "weight_decay": 0,
    "amsgrad": false
  },
  "advantage_type": "mean",
  "batch_size": 100,
  "beta": 1.0,
  "critic_encoder_factory": {
    "type": "default",
    "params": {
      "activation": "relu",
      "use_batch_norm": false,
      "dropout_rate": null
    }
  },
  "critic_learning_rate": 0.0003,
  "critic_optim_factory": {
    "optim_cls": "Adam",
    "betas": [
      0.9,
      0.999
    ],
    "eps": 1e-08,
    "weight_decay": 0,
    "amsgrad": false
  },
  "gamma": 0.99,
  "generated_maxlen": 100000,
  "max_weight": 20.0,
  "n_action_samples": 4,
  "n_critics": 1,
  "n_frames": 1,
  "n_steps": 1,
  "q_func_factory": {
    "type": "mean",
    "params": {
      "bootstrap": false,
      "share_encoder": false
    }
  },
  "real_ratio": 1.0,
  "scaler": null,
  "target_reduction_type": "min",
  "target_update_interval": 100,
  "update_actor_interval": 1,
  "use_gpu": 0,
  "weight_type": "exp",
  "algorithm": "CRR",
  "observation_shape": [
    10
  ],
  "action_size": 10
}

**Comment by takuseno** [comment]
Thank you! On my side, This works.
```
import d3rlpy
import numpy as np

crr = d3rlpy.algos.CRR.from_json('params.json')
observation = np.random.random(crr.observation_shape)
action = crr.predict([observation])
print(action)
```

Can you share the d3rlpy version? Sorry for the inconvenience.

**Comment by icomeaman** [comment]
thank you 
my version is :  d3rlpy   0.90

**Comment by takuseno** [comment]
Thanks! Now I reproduce the error like this.
```
import d3rlpy
import numpy as np

crr = d3rlpy.algos.CRR.from_json('params.json')
observation = np.random.random(crr.observation_shape)

# correct
action = crr.predict(np.array([observation])) # (1, 10)

# error
action = crr.predict(np.array([[observation]])) # (1, 1, 10)

print(action)
```
I believe your `obsevation` has an additional dimension.

**Comment by icomeaman** [comment]
thank you very much!!!
this is my observation dimension:
observations = dataset['observations']
actions = dataset['actions']
print(observations.shape)  # (26614, 10)

but when I try :
obs=observations[0]
action = crr.predict([obs])

there is no problem.
thank you very much!!!
