### ISSUE TITLE
try to use TensorBoard

### ISSUE THREAD

**Issue by icomeaman** [takuseno/d3rlpy#80]
**Describe the bug**
I try to use TensorBoard like in Logging/API Reference described:
The same information is also automatically saved for tensorboard under runs directory. You can interactively visualize training metrics easily.
$ tensorboard --logdir runs

**To Reproduce**
cql.fit(dataset.episodes, 
            n_epochs=10,
            logdir='custom_logs', 
            experiment_name='custom')

i didn't find any runs directory under this 'custom_20210628145218' file.

tensorboard --logdir='/home/ws/uzfka/d3rlpy/custom_logs/custom_20210628145218/runs' --port=16006
and tensorboard shows that:
No dashboards are active for the current data set.

**Expected behavior**

**Additional context**

**Comment by takuseno** [comment]
@icomeaman Thanks for the issue and sorry for the inconvenience. The documentation seems to be outdated. If you want to save tensorboard data, you need to give `tensorboard_dir` argument.
https://d3rlpy.readthedocs.io/en/v0.90/references/generated/d3rlpy.algos.CQL.html#d3rlpy.algos.CQL.fit

**Comment by icomeaman** [comment]
thank you very much!!!
