### ISSUE TITLE
[BUG] train_single_env and train_batch_env accumulates misaligned entries into buffers

### ISSUE THREAD

**Issue by osogami** [takuseno/d3rlpy#81]
**Describe the bug**
(observation, action, reward, terminal, clip_episode) appended to the buffer by `train_single_env` and `train_batch_env` in the following lines does not appear to be properly aligned:
https://github.com/takuseno/d3rlpy/blob/master/d3rlpy/online/iterators.py#L206
https://github.com/takuseno/d3rlpy/blob/master/d3rlpy/online/iterators.py#L392

**To Reproduce**
n/a

**Expected behavior**
`buffer.append` should be called after reward, terminal, and clip_episode are updated (also, do `prev_observation = observation` before `env.step()` and append `prev_observation` instead of updated observation).

**Additional context**
n/a

**Comment by takuseno** [comment]
@osogami Thanks for the issue. Actually, the implementation is correct. The buffers are designed to accept (s_t, a_t, r_t, done_t).

**Comment by osogami** [comment]
@takuseno Thank you very much for your response.  I have read the code more carefully and now understand that there is nothing wrong with the buffer.  I am sorry for raising a wrong issue, but your response was extremely helpful to me.
