### ISSUE TITLE
[BUG] Inconsistent behavior when calling fit multiple times

### ISSUE THREAD

**Issue by tesslerc** [takuseno/d3rlpy#82]
**Describe the bug**
Various algorithms, such as the DQN, have periodic behavior (update target network, update actor intervals, etc..).
This is decided based on 'total_step' variable as defined in base.py
https://github.com/takuseno/d3rlpy/blob/e7f61e1d02690409b5ac288aabf8072b463f72ed/d3rlpy/base.py#L552
this variable is initialized each time fit is called.

**To Reproduce**
Call fit once with `n_steps = 20000` and compare to calling fit 4 times with `n_steps = 5000`.

**Expected behavior**
I'd expect the exact same performance and training process.
In practice when calling fit with n_steps < target_update_interval, the target will never be updated.

**Additional context**
I'm plotting the performance of the agent as a function of the number of gradient steps. There is certain logic I need to perform outside of the fit operation and thus must call fit multiple times. I see that when fit is called multiple times for a small number of steps, the agent doesn't learn (compared to a single long fit which learns well).

Keeping a class variable _total_steps initialized upon creation of the base class (and not zeroing it upon calling fit) solves this issue.

**Comment by takuseno** [comment]
@tesslerc Thanks for the issue. I believe this is not a bug, but it's better to consider this issue. I'll add an option to start from an arbitrary `total_step`.

**Comment by takuseno** [comment]
@tesslerc I realized that this is a bit hard to deal with. The `fit` and `fit_online` methods have `callback` argument that is called every time step. I think you can use this instead of calling `fit` multiple times.
https://d3rlpy.readthedocs.io/en/v0.90/references/generated/d3rlpy.algos.SAC.html#d3rlpy.algos.SAC.fit

```
def callback(algo, epoch, total_step):
    # do what you want to do

sac = d3rlpy.algos.SAC()
sac.fit(dataset, n_steps=1000000, callback=callback)
```

**Comment by tesslerc** [comment]
@takuseno why would this be an issue? why not have a self._total_step initialized in base.py to 0. Then have a flag in fit to reset total_step to 0 or not.

I'm interchanging online and offline learning, data collection etc... non-trivial behavior.
I did the above suggestion on my end and it seems fine so far.

**Comment by takuseno** [comment]
@tesslerc I'm working on this branch to support this feature.
https://github.com/takuseno/d3rlpy/tree/refactor_grad_step

I hope you get what I meant from the commit.

**Comment by jamartinh** [comment]
@tesslerc if you need to call fit multiple times it should be equivalent to using fitter o iterate over epochs letting you make any code between active fitting

**Comment by tesslerc** [comment]
Awesome @jamartinh ! thanks for the quick responses! Love this repo!
