### ISSUE TITLE
[REQUEST] convert assertion to warning

### ISSUE THREAD

**Issue by jamartinh** [takuseno/d3rlpy#88]
@takuseno Could this assert be transformed to a warning?

When you update an MDPDataset of Discrete actions it could happend that the first dataset does not contain all the actions and the updating gives an assertion error.

https://github.com/takuseno/d3rlpy/blob/f279245e3c8dcd89bd8c8abafcfdf1dff50b7fce/d3rlpy/dataset.pyx#L451-L453

**Comment by takuseno** [comment]
@jamartinh I see. We can update the action_size property when it gets the action bigger than the current action_size. Would you want me to do this? Or could you PR for this change on your end? :)

**Comment by jamartinh** [comment]
I can do the PR!

**Comment by jamartinh** [comment]
@takuseno 

Fix in https://github.com/takuseno/d3rlpy/pull/92

**Comment by takuseno** [comment]
Let me close this since the PR is merged.
