### ISSUE TITLE
[Help wanted] mat1 and mat2 shapes cannot be multiplied (1x112 and 7x256)

### ISSUE THREAD

**Issue by Zaharah** [takuseno/d3rlpy#89]
Hello, I am trying to apply CQL on my custom environment. I have created a dataset using `MDPDataset` class. 
The dataset consists of following:
Observation (1000, 7) 
Actions (1000, 3) 
Rewards (1000,) 
Terminals (1000,)

However, when I run the following code 
`cql.fit(train_episodes,
        eval_episodes=test_episodes,
        n_epochs=1,
        scorers={
            'environment': evaluate_on_environment(env), # evaluate with CartPol-v0 environment
            'advantage': discounted_sum_of_advantage_scorer, # smaller is better
            'td_error': td_error_scorer # smaller is better
        })`

I run into following error.
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x112 and 7x256)

Can you please tell me what I doing wrong? Thanks in advance.

**Comment by takuseno** [comment]
@Zaharah Hello, thanks for the issue. Can you share the minimum working example code to reproduce the issue on my end?

**Comment by Zaharah** [comment]
Thanks for the prompt response @takuseno. I found that the problem was with my environment. It is working fine now.
