### ISSUE TITLE
[REQUEST] conda recipe for conda forge

### ISSUE THREAD

**Issue by jamartinh** [takuseno/d3rlpy#9]
**Describe the solution you'd like**
Able to install with conda install -c conda-forge d3rlpy

**Comment by takuseno** [comment]
@jamartinh Thank you for your request! I'll make this available on conda-forge.

**Comment by jamartinh** [comment]
Thanks ! Takuseno this will give lot of visibility to the proyect. 
I have it now installed on conda python 38 env without troubles I have installed it with pip install --no-deps

**Comment by takuseno** [comment]
@jamartinh Hi. I'm submitting a PR for conda-forge.
https://github.com/conda-forge/staged-recipes/pull/13143
I hope it gets accepted and available on conda-forge soon.

**Comment by jamartinh** [comment]
Great!!!

**Comment by takuseno** [comment]
@jamartinh Now, it's available on conda-forge!

https://anaconda.org/conda-forge/d3rlpy

**Comment by jamartinh** [comment]
Wow that's fast!!!

**Comment by jamartinh** [comment]
Mmm, when I install from conda-forge I get a core dump on linux.

**Comment by takuseno** [comment]
@jamartinh really...? can you share the error?

**Comment by jamartinh** [comment]
(python38) [~]$ ipython
Python 3.8.5 (default, Sep  4 2020, 07:30:14)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from d3rlpy.dataset import MDPDataset
Illegal instruction (core dumped)

**Comment by takuseno** [comment]
@jamartinh Thanks for sharing! This works on my linux machine. So I suspect the architecture difference since that module is built with Cython. Could you share your machine information? This will be quite helpful. Thanks!

**Comment by takuseno** [comment]
Now, I'm testing `import d3rlpy.dataset` in building conda package.
https://github.com/conda-forge/d3rlpy-feedstock/blob/8a6bb9f14bc2fee60a4ca0f9b61370dde5381467/recipe/meta.yaml#L39

So, I think architecture difference causes the problem....
