### ISSUE TITLE
Question regarding FQE

### ISSUE THREAD

**Issue by guyk1971** [takuseno/d3rlpy#93]
Hi,
First - well done on a great framework for offline RL !! Thanks a lot for sharing !
I have a question regarding fqe - according to [the paper](https://arxiv.org/abs/1903.08738) (algorithm 3) it looks like there's a mismatch with what's implemented in fqe.py (line 97) : 
`next_actions = self._algo.predict(batch.observations)`

If I understand the paper (and your implementation) correctly, I would expect to see:
`next_actions = self._algo.predict(batch.next_observations)`

can you please check ? I might have missed something, just wanted to make sure what's the right way.

Thanks a lot !

**Comment by takuseno** [comment]
@guyk1971 Oooops. Thanks for the good catch! This is something I did wrong at the recent refactoring. I'll fix this soon.

**Comment by guyk1971** [comment]
@takuseno , Thanks for the prompt response.
Whatever works best for you. I dont mind.
Thanks again for the great work on this library !

**Comment by takuseno** [comment]
@guyk1971 Hello, sorry for the late reply. I've fixed this in the latest commit.
https://github.com/takuseno/d3rlpy/commit/e27852664647b7774f56ec775437b0ca73a24f3f
