### ISSUE TITLE
[REQUEST] Reward transformer

### ISSUE THREAD

**Issue by tesslerc** [takuseno/d3rlpy#94]
**Is your feature request related to a problem? Please describe.**
I have seen reward transformations in offline RL in two distinct instances
1. Rewards are normalized -- either to [0,1] (like MinMaxScaler for obs), or based on the cumulative discounted reward to go (like OpenAI tend to do in online RL)
2. Pessimistic costs -- where some model predicts a score based on (s,a) and provides a cost c. The new reward: \hat r = r - c

**Describe the solution you'd like**
A reward scaler class that can be fitted on the current dataset and provided to the agent.
This class should receive (s, a, r) as the cost can also be a function of (s,a) and returns \hat r.

**Comment by takuseno** [comment]
@tesslerc Thanks for the issue! I think this could be useful. Please let me take time for this.

**Comment by takuseno** [comment]
@tesslerc Sorry for the late update. I've implemented `RewardScaler` in the master branch.
https://d3rlpy.readthedocs.io/en/latest/references/preprocessing.html#reward

For now, this provides normalization, standardization and clipping. For more comlex functionalities, please do it before creating datasets or build your own algorithm. For example, you can create a new class based on `SAC` and override the `_update` method.
https://github.com/takuseno/d3rlpy/blob/aa6a0d1fe8f862cd9080c63dd6b9a68c816e91f3/d3rlpy/algos/sac.py#L202

**Comment by takuseno** [comment]
Feel free to reopen this if you have further discussions. Thank you!
